### ISSUE TITLE
Inverse does not exist error in carpetplot resample_parc node

### ISSUE THREAD

**Issue by zhifangy** [nipreps/fmriprep#1127]
When I ran FMRIPrep 1.0.13, the process crashed on node `resample_parc`. 

> 180514-10:08:36,654 workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_02_wf.func_preproc_task_rest_wf.carpetplot_wf.resample_parc" (/brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/func_preproc_task_rest_wf/carpetplot_wf/resample_parc)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.13', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 314, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 520, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/interfaces/fixes.py", line 24, in _run_interface
    runtime, correct_return_codes)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 1020, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 957, in raise_exception
    ).format(**runtime.dictcopy()))
RuntimeError: Command:
antsApplyTransforms --default-value 0 --dimensionality 3 --float 1 --input /niworkflows_data/mni_icbm152_nlin_asym_09c/1mm_parc.nii.gz --interpolation MultiLabel --output 1mm_parc_trans.nii.gz --reference-image /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/func_preproc_task_rest_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/combine_masks2/ref_image_corrected_mask_dil_maths_maths.nii.gz --transform [ /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/func_preproc_task_rest_wf/bold_reg_wf/bbreg_wf/fsl2itk_fwd/affine.txt, 1 ] --transform [ /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/anat_preproc_wf/t1_2_mni/ants_t1_to_mniComposite.h5, 1 ]
Standard output:
Standard error:
Return code: 1

I tried to manually run the command `antsApplyTransforms --default-value 0 --dimensionality 3 --float 1 --input /niworkflows_data/mni_icbm152_nlin_asym_09c/1mm_parc.nii.gz --interpolation MultiLabel --output 1mm_parc_trans.nii.gz --reference-image /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/func_preproc_task_rest_wf/bold_bold_trans_wf/bold_reference_wf/enhance_and_skullstrip_bold_wf/combine_masks2/ref_image_corrected_mask_dil_maths_maths.nii.gz --transform [ /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/func_preproc_task_rest_wf/bold_reg_wf/bbreg_wf/fsl2itk_fwd/affine.txt, 1 ] --transform [ /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_02_wf/anat_preproc_wf/t1_2_mni/ants_t1_to_mniComposite.h5, 1 ]`, it crashed with following error.
> Inverse does not exist for /brain/guixue/zhifang/ds003/works/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/t1_2_mni/ants_t1_to_mniComposite.h5

I think this may related to the discussion https://neurostars.org/t/fmriprep-inverse-t1-to-mni-warp/882 and https://github.com/ANTsX/ANTs/issues/326.

Any suggestions? Thanks.

**Comment by effigies** [comment]
Yeah, looks like we were wrong about this in #1114. We'll fix this today and get a new release by tomorrow.
