### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by tragus1** [nipreps/fmriprep#1372]
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.0.8', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 267, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/workflows.py", line 602, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 168, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 68, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 487, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 571, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 650, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 516, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 152, in _run_interface
    intensity_normalization=self.inputs.intensity_normalization)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/algorithms/confounds.py", line 909, in compute_dvars
    np.float32), 1)[:, 0]
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 91, in apply_along_axis
    res = func1d(arr[tuple(i.tolist())], *args, **kwargs)
IndexError: index 0 is out of bounds for axis 0 with size 0

The dataset passed BIDS validation.
Do you have any idea how to solve this issue?

Thanks

**Comment by effigies** [comment]
Does this problem persist in the latest fMRIPrep (1.2.1)?

**Comment by tragus1** [comment]
Yes, I run the latest version.

**Comment by effigies** [comment]
Could you provide the traceback for the run with a recent version?

**Comment by tragus1** [comment]
It still gives me the old version again in the error prompt although I successfully run pip install --user --upgrade fmriprep-docker

 load_entry_point('fmriprep==1.0.6.post2', 'console_scripts', 'fmriprep')()

**Comment by effigies** [comment]
You might have a global installation of fmriprep-docker, in addition to the `--user` installation. Try `pip uninstall fmriprep-docker` a couple times, and then reinstall.

**Comment by tragus1** [comment]
This is what the new version produces:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 342, in main
    fmriprep_wf.run(**plugin_settings)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 162, in run
    self._clean_queue(jobid, graph, result=result))
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 224, in _clean_queue
    raise RuntimeError("".join(result['traceback']))
RuntimeError: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 129, in apply_along_axis
    ind0 = next(inds)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py", line 145, in _run_interface
    intensity_normalization=self.inputs.intensity_normalization)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nipype/algorithms/confounds.py", line 901, in compute_dvars
    np.float32), 1)[:, 0]
  File "/usr/local/miniconda/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 131, in apply_along_axis
    raise ValueError('Cannot apply_along_axis when any iteration dimensions are 0')
ValueError: Cannot apply_along_axis when any iteration dimensions are 0

**Comment by oesteban** [comment]
Hi @tragus1, could you share some data for us to replicate your issue?

**Comment by effigies** [comment]
Please open a new issue if this is still an issue.
