### ISSUE TITLE
Error in generating confounds 20.01

### ISSUE THREAD

**Issue by CalebRHaynes** [nipreps/fmriprep#2300]
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "", line 6, in _to_join
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/utils.py", line 785, in _run_interface
    raise ValueError("Number of columns in datasets do not match")
ValueError: Number of columns in datasets do not match

### What version of fMRIPrep are you using?
20.01
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
singularity 
### What is the exact command-line you used?
```
<place your command line here>
```

### Have you checked that your inputs are BIDS valid?
Yes
### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<please copy&paste all the information you can gather about errors>
```

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by effigies** [comment]
Sorry, "20.01" is not a version of fMRIPrep. Could you check your setup and report as much information as you can find?

**Comment by CalebRHaynes** [comment]
Apologies, I am using a singularity image 20.1.0

**Comment by effigies** [comment]
Can you verify that the problem persists in 20.1.3?

**Comment by CalebRHaynes** [comment]
Will update and respond, thank you

**Comment by CalebRHaynes** [comment]
Not getting error with updated version

**Comment by effigies** [comment]
Thanks for checking back in, and glad to hear that the issue was resolved.
