### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by soyfrien** [nipreps/fmriprep#2313]
### What version of fMRIPrep are you using?
v20.2.0

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity (Same behavior in Docker as well)

### What is the exact command-line you used?
```
singularity run --cleanenv -B /data:/data /opt/singularityImages/fmriprep-20.2.0.simg /data/NIAAA/fmri_data/sourcedata /data/NIAAA/fmri_data/derivatives/ participant --fs-license-file /data/Meg/generaltools/freesurfer_license.txt --fs-no-reconall -w /data/NIAAA/fmri_data/scratch --output-spaces MNI152NLin2009cAsym:res-2 --omp-nthreads 18 --nthreads 18
```

### Have you checked that your inputs are BIDS valid?
Yes

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
No

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```

/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 592, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 612, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 448, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 151, in __init__
    database_path, reset_database, config, init_args)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 48, in __init__
    self.reset_database(init_args, config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 105, in reset_database
    Base.metadata.create_all(self.engine)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4556, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2097, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 787, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE layout_info (
        root VARCHAR NOT NULL,
        absolute_paths BOOLEAN,
        _derivatives VARCHAR,
        _config VARCHAR,
        PRIMARY KEY (root),
        CHECK (absolute_paths IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

**Comment by mgxd** [comment]
Have you tried clearing your working directory?

**Comment by ppdac** [comment]
No, sorry I don't understand how to do this.

---
keybase.io/1of1

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by effigies** [comment]
The working directory in your command is `/data/NIAAA/fmri_data/scratch`. Make sure you have permissions there, and delete the contents.

**Comment by ppdac** [comment]
Yes, thank you. We get the same issue:

```
louis@meg:/data/NIAAA/fmri_data$ ls -lha scratch
total 0
drwxrwx--- 2 username groupname 0 Oct 26 03:06 .
drwxrwx--- 2 username groupname 0 Oct 26 03:06 ..
louis@meg:/data/NIAAA/fmri_data$ singularity run --cleanenv -B /data:/data /opt/singularityImages/fmriprep-20.2.0.simg /data/NIAAA/fmri_data/sourcedata /data/NIAAA/fmri_data/derivatives/ participant --fs-license-file /data/Meg/generaltools/freesurfer_license.txt --fs-no-reconall -w /data/NIAAA/fmri_data/scratch --output-spaces MNI152NLin2009cAsym:res-2 --omp-nthreads 18 --nthreads 18
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 592, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 612, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 448, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 151, in __init__
    database_path, reset_database, config, init_args)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 48, in __init__
    self.reset_database(init_args, config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 105, in reset_database
    Base.metadata.create_all(self.engine)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4556, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2097, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 787, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE layout_info (
        root VARCHAR NOT NULL,
        absolute_paths BOOLEAN,
        _derivatives VARCHAR,
        _config VARCHAR,
        PRIMARY KEY (root),
        CHECK (absolute_paths IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
louis@meg:/data/NIAAA/fmri_data$ ls -lha scratch
total 0
drwxrwx--- 2 username groupname 0 Oct 26 03:06 .
drwxrwx--- 2 username groupname 0 Oct 26 03:06 ..
drwxrwx--- 2 username groupname 0 Oct 26 03:06 20201026-030651_8e85ddb0-9e34-4fc7-a24f-3dbcd49f98be
```

**Comment by ppdac** [comment]
Yes, thank you. We get the same issue:

```
louis@host:/data/NIAAA/fmri_data$ ls -lha scratch
total 0
drwxrwx--- 2 username groupname 0 Oct 26 03:06 .
drwxrwx--- 2 username groupname 0 Oct 26 03:06 ..
louis@host:/data/NIAAA/fmri_data$ singularity run --cleanenv -B /data:/data /opt/singularityImages/fmriprep-20.2.0.simg /data/NIAAA/fmri_data/sourcedata /data/NIAAA/fmri_data/derivatives/ participant --fs-license-file /data/Meg/generaltools/freesurfer_license.txt --fs-no-reconall -w /data/NIAAA/fmri_data/scratch --output-spaces MNI152NLin2009cAsym:res-2 --omp-nthreads 18 --nthreads 18
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 592, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 612, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 448, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 151, in __init__
    database_path, reset_database, config, init_args)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 48, in __init__
    self.reset_database(init_args, config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 105, in reset_database
    Base.metadata.create_all(self.engine)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4556, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2097, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 787, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 832, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_ddl
    compiled,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
CREATE TABLE layout_info (
        root VARCHAR NOT NULL,
        absolute_paths BOOLEAN,
        _derivatives VARCHAR,
        _config VARCHAR,
        PRIMARY KEY (root),
        CHECK (absolute_paths IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
louis@host:/data/NIAAA/fmri_data$ ls -lha scratch
total 0
drwxrwx--- 2 username groupname 0 Oct 26 03:06 .
drwxrwx--- 2 username groupname 0 Oct 26 03:06 ..
drwxrwx--- 2 username groupname 0 Oct 26 03:06 20201026-030651_8e85ddb0-9e34-4fc7-a24f-3dbcd49f98be
```

**Comment by daJimenezPa** [comment]
Same problem here, any updates on this?

**Comment by daJimenezPa** [comment]
We solved changing filesystem into nfs from cifs. Furthermore with nolock option when mounting cifs was solved to

**Comment by Heechberri** [comment]
Hi guys,

I also had the same issue. But I managed to solve this issue by changing the scratch directory to a local disk (e.g /home/user/Documents), rather than a mounted disk.

**Comment by tiffanylinhy** [comment]
Hi, 
We had the same issue on our Ubuntu server. When the directory is a permanently mounted NAS drive(cifs), it showed the error. If we changed it to a local disk there is no error.
The mounted folder should be unlocked cause the user owns the folder and we can access it through the terminal.

I wonder if there are any other solutions than running fmriprep on a local disk...
Thank you.

**Comment by soyfrien** [comment]
It seems the solution is to run off a local drive. But I am 99% sure that /data in the example I used was a local [ZFS filesystem](https://openzfs.github.io/openzfs-docs/man/8/zpool-list.8.html) (drives were local) and this was using ssh.

**Comment by effigies** [comment]
Generally, it's fine to put inputs and outputs on any drive. The working directory can be more finicky, as filesystems that do not provide synchronization or file locking will either fail or slow things down.

I think the only thing that absolutely requires a fully featured filesystem is creating the bids database. If you check the docs, there are instructions for pre-creating it.

**Comment by soyfrien** [comment]
Okay, I can no longer test this so will close. Hoepfully it is no longer an issue.

**Comment by halphenfang** [comment]
> We solved changing filesystem into nfs from cifs. Furthermore with nolock option when mounting cifs was solved to

Hi, could you explain in more detailed about how to change the filesystem into nfs from cifs?

**Comment by soyfrien** [comment]
@halphenfang, just changing the way you mount it will do it. Depends on your operating system. On a Mac you would just change the path when opening a share.

Instead of nfs or smb for example: smb://server/share -> cifs://server/share

**Comment by JohannesWiesner** [comment]
Is there any plan to make it possible that the workin directory can be also placed under a file system using the cifs-protocol? We have the same problem as CIMH. The current work around is a quite complex io-operation where we copy the to-be-processed data first to a nfs-system, preprocess it there, copy the output back to the cifs-folder, delete the original in the nfs-folder, etc.

pinging our IT-hero @cbudziszewski here just for the docs

P.S.: We have the same problem with datalad:

https://github.com/datalad/datalad/issues/6917

**Comment by JohannesWiesner** [comment]
We are using linux environment modules + SLURM at CIMH. @effigies, this works:

```bash
sbatch \
 --job-name fmriprep_24.0.1_sub-SOSE1JGLP \
 --output /zi/home/johannes.wiesner/work/slurm/project_sosense/logfiles/fmriprep//fmriprep_24.0.1_sub-SOSE1JGLP.out \
 --cpus-per-task 8 \
 --mem 16 \
 --mail-user johannes.wiesner@zi-mannheim.de \
 --exclude zislhcn[0101-0108] \
 --wrap "bash -c 'kinit johannes.wiesner@ZI.LOCAL -k -t /zi/home/johannes.wiesner/johannes.wiesner.keytab && \
  module load fmriprep/24.0.1 && \
  fmriprep /zi/flstorage/group_csp/analyses/paul.grube/projects/project_sosense/data/mri/nifti/ /zi/flstorage/group_csp/data/sosense/mri/derivatives/fmriprep/ participant --fs-license-file /zi/home/johannes.wiesner/work/it/freesurfer_license.txt --n_cpus 8 --work-dir /zi/flstorage/group_csp/data/sosense/mri/workdir/ --bids-database-dir /zi/home/johannes.wiesner/work/slurm/project_sosense/workdir/fmriprep/ --participant-label SOSE1JGLP'"
```

In plain words:

Use a directory under `/zi/flstorage/` (which is a CIFS-share) as `--work-dir` AND also pass a NON-CIFS directory under `/zi/home/johannes.wiesner` (which is an NFS-share)  as `--bids-database-dir` so that fmriprep does not get SQL-Lite (and possibly also other) problems.
