### ISSUE TITLE
Templateflow file not downloading properly

### ISSUE THREAD

**Issue by jbwexler** [nipreps/fmriprep#2337]
I'm trying to run some subjects from openneuro ds001734 with fmriprep v20.2.1 and am running into errors due to the following file not downloading properly: /home1/03201/jbwexler/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz Any ideas on the cause of this? Here's the crashfile:

Node: fmriprep_wf.single_subject_002_wf.anat_preproc_wf.brain_extraction_wf.res_tmpl
Working directory: /scratch/03201/jbwexler/fmriprep-work/ds001734_sub-002-sub-002/fmriprep_wf/single_subject_002_wf/anat_preproc_wf/brain_extraction_wf/res_tmpl

Node inputs:

clip = True
in_file = /home1/03201/jbwexler/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz
order = 3
smooth = True
zooms = (4.0, 4.0, 4.0)

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/images.py", line 75, in _run_interface
    smooth=self.inputs.smooth,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/images.py", line 200, in resample_by_spacing
    data = gaussian_filter(in_file.get_fdata(), smooth)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/dataobj_images.py", line 355, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.7/site-packages/numpy/core/numeric.py", line 553, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 337, in _get_unscaled
    mmap=self._mmap)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/volumeutils.py", line 529, in array_from_file
    raise IOError(f"Expected {n_bytes} bytes, got {n_read} bytes from "
OSError: Expected 64364544 bytes, got 30029646 bytes from object
 - could the file be damaged?

**Comment by oesteban** [comment]
> * could the file be damaged?

yes, looks like. can you just `rm /home1/03201/jbwexler/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz` and rerun?
