### ISSUE TITLE
fmriprep failing with "Could not build path with entities" error message

### ISSUE THREAD

**Issue by soichih** [nipreps/fmriprep#2340]
Our user is running fmriprep version 20.2.0 via singularity/docker

```
singularity exec -e \
    docker://poldracklab/fmriprep:20.2.0 \
    /usr/local/miniconda/bin/fmriprep \
    --notrack \
    --resource-monitor \
    --skip-bids-validation \
    --md-only-boilerplate \
    --stop-on-first-crash \
    --use-plugin=multi_proc.yml \
    --output-spaces $output_space MNI152NLin2009cAsym \
    --cifti-output $cifti_output_resolution \
    --force-bbr \
    --use-syn-sdc \
    --skull-strip-template=NKI \
    --work-dir=$WORKDIRNAME \
```

A few minutes into the job, fmriprep crashes with the following log output.

```
Node: fmriprep_wf.single_subject_ALB1_wf.func_preproc_bold.ds_report_validation
Working directory: /N/project/brainlife/workdir/prod-carbonate/5faa6b8329699c9e7cef98fc/5fbf67fd47b8ca741730ff93/fmripworkdir/fmriprep_wf/single_subject_ALB1_wf/func_preproc_bold/ds_report_validation

Node inputs:

acquisition = <undefined>
atlas = <undefined>
base_directory = /N/project/brainlife/workdir/prod-carbonate/5faa6b8329699c9e7cef98fc/5fbf67fd47b8ca741730ff93/fmripout
ceagent = <undefined>
check_hdr = True
cohort = <undefined>
compress = <undefined>
data_dtype = <undefined>
datatype = figures
density = <undefined>
desc = validation
direction = <undefined>
dismiss_entities = ['echo']
echo = <undefined>
extension = <undefined>
fmap = <undefined>
from = <undefined>
hemi = <undefined>
in_file = ['/N/project/brainlife/workdir/prod-carbonate/5faa6b8329699c9e7cef98fc/5fbf67fd47b8ca741730ff93/fmripworkdir/fmriprep_wf/single_subject_ALB1_wf/func_preproc_bold/initial_boldref_wf/val_bold/mapflow/_val_bold0/report.html']
label = <undefined>
meta_dict = <undefined>
modality = <undefined>
mode = <undefined>
model = <undefined>
proc = <undefined>
reconstruction = <undefined>
recording = <undefined>
resolution = <undefined>
roi = <undefined>
run = <undefined>
scans = <undefined>
session = <undefined>
source_file = ['/N/project/brainlife/workdir/prod-carbonate/5faa6b8329699c9e7cef98fc/5fbf67fd47b8ca741730ff93/bids/sub-ALB1/func/sub-ALB1_bold.nii.gz']
space = <undefined>
subject = <undefined>
subset = <undefined>
suffix = <undefined>
task = <undefined>
to = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 432, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/bids.py", line 565, in _run_interface
    raise ValueError(f"Could not build path with entities {out_entities}.")
ValueError: Could not build path with entities {'subject': 'ALB1', 'suffix': 'bold', 'datatype': 'figures', 'extension': 'html', 'desc': 'validation'}.
```

Could you help understand what this error message means? What exactly is wrong with our entities in this case?

**Comment by notZaki** [comment]
It could be because the source filename `sub-ALB1_bold.nii.gz` is missing a `task` entity which is mandatory in the [BIDS specification](https://bids-specification.readthedocs.io/en/latest/99-appendices/04-entity-table.html#magnetic-resonance-imaging).
Try renaming the file to `sub-ALB1_task-rest_bold.nii.gz`---or whatever is appropriate as the task label---and retrying.

**Comment by soichih** [comment]
Oh thank you for noticing that. Yes it looks like that was the cause of the issue. I will track down why task isn't set for this data.

**Comment by soichih** [comment]
Actually, one more question.

Since fmriprep is a preprocessing pipeline, does it matter that the fmri data was rest or not - from preprocessing point of view? My appology if this is a stupid question..

**Comment by effigies** [comment]
No, fMRIPrep does not distinguish among any tasks (including rest). It's just a label to us.

**Comment by mgxd** [comment]
it's a problem of BIDS compliance, which fmriprep relies on - it probably would have been caught if `--skip-bids-validation` wasn't used.

**Comment by belfinrv** [comment]
I am having the same issue? Do you have a fix for this issue?
