### ISSUE TITLE
AttributeError: type object 'loggers' has no attribute 'warning'

### ISSUE THREAD

**Issue by giulia-berto** [nipreps/fmriprep#2344]
I got an error when running fMRIPrep version 20.2.0.

The command I ran is this:
```
singularity exec -e docker://poldracklab/fmriprep:20.2.0 /usr/local/miniconda/bin/fmriprep --notrack --resource-monitor --skip-bids-validation --md-only-boilerplate --stop-on-first-crash --use-plugin=multi_proc.yml --output-spaces MNI152NLin2009cAsym:res-2 MNI152NLin2009cAsym --cifti-output 91k --force-bbr --use-syn-sdc --skull-strip-template=NKI --work-dir=fmripworkdir --fs-license-file=license.txt bids fmripout participant
```
The error I got is this:
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 84, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
    config.loggers.warning(
AttributeError: type object 'loggers' has no attribute 'warning'
```

**Comment by giulia-berto** [comment]
sorry, duplicated issue of #2296
