### ISSUE TITLE
Help fmriprep- ValueError: operands could not be broadcast together with shapes 

### ISSUE THREAD

**Issue by shaymaadarawshy** [nipreps/fmriprep#2352]
Hi, 
I'm using fmriprep to preprocess my data, and I have a problem with registration. The problem started when I included a lesion file in my anat folder. this is the crash information:
Node: fmriprep_wf.single_subject_12_wf.anat_preproc_wf.anat_norm_wf.registration
Working directory: /tmp/work/fmriprep_wf/single_subject_12_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration

Node inputs:

explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
reference = T1w
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = <undefined>
template_spec = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 163, in _run_interface
    ants_args = self._get_ants_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 295, in _get_ants_args
    global_mask=self.inputs.explicit_masking,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 556, in create_cfm
    data = np.fmax(data - lm_img.dataobj, 0)
ValueError: operands could not be broadcast together with shapes (176,240,256) (173,201,148)

any help? 
thank you,
Shaymaa

**Comment by effigies** [comment]
Could you show the shapes of your lesion file and anat file? If you have nibabel installed, you can just run `nib-ls` on them.

**Comment by shaymaadarawshy** [comment]
Hi Chris, thank you very much for your response! 
Not sure I understand what you mean by "shape" though...
Is there a way to extract this information using an AFNI or an FSL command (since I don't have nibabel installed)?
Many thanks, 
Shaymaa

**Comment by effigies** [comment]
fslhd will show the necessary information.

**Comment by shaymaadarawshy** [comment]
Hi Chris, 
included are the error and fslhd information for both the anat and the lesion.

thank yiu,
shayamaa


**This is an error of subject 03, we have two crash errors:** 
**_error 1:_**
Node: fmriprep_wf.single_subject_03_wf.anat_preproc_wf.anat_norm_wf.registration
Working directory: /tmp/work/fmriprep_wf/single_subject_03_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin2009cAsym/registration

Node inputs:

explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
reference = T1w
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = <undefined>
template_spec = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 163, in _run_interface
    ants_args = self._get_ants_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 295, in _get_ants_args
    global_mask=self.inputs.explicit_masking,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 556, in create_cfm
    data = np.fmax(data - lm_img.dataobj, 0)
ValueError: operands could not be broadcast together with shapes (176,240,256) (176,186,176) 


**_error 2:_**
Node: fmriprep_wf.single_subject_03_wf.anat_preproc_wf.anat_norm_wf.registration
Working directory: /tmp/work/fmriprep_wf/single_subject_03_wf/anat_preproc_wf/anat_norm_wf/_template_MNI152NLin6Asym/registration

Node inputs:

explicit_masking = True
flavor = precise
float = True
initial_moving_transform = <undefined>
lesion_mask = <undefined>
moving = T1w
moving_image = <undefined>
moving_mask = <undefined>
num_threads = 8
orientation = RAS
reference = T1w
reference_image = <undefined>
reference_mask = <undefined>
settings = <undefined>
template = MNI152NLin2009cAsym
template_resolution = <undefined>
template_spec = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 163, in _run_interface
    ants_args = self._get_ants_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 295, in _get_ants_args
    global_mask=self.inputs.explicit_masking,
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/interfaces/mni.py", line 556, in create_cfm
    data = np.fmax(data - lm_img.dataobj, 0)
ValueError: operands could not be broadcast together with shapes (176,240,256) (176,186,176) 


 **fslhd infromation for the anat file:** 
shymaa@psylabhumants:~/Desktop/my_dataset/Participant/sub-03/anat$ fslhd -x sub-03_T1w.nii.gz
<nifti_image
  image_offset = '1184'
  ndim = '3'
  nx = '176'
  ny = '240'
  nz = '256'
  nt = '1'
  dx = '1'
  dy = '1'
  dz = '1'
  dt = '2.3'
  datatype = '4'
  nvox = '10813440'
  nbyper = '2'
  scl_slope = '1'
  scl_inter = '0'
  intent_code = '0'
  intent_p1 = '0'
  intent_p2 = '0'
  intent_p3 = '0'
  intent_name = 'tfl'
  toffset = '0'
  xyz_units = '2'
  time_units = '8'
  freq_dim = '3'
  phase_dim = '2'
  slice_dim = '1'
  descrip = 'phase=-y;TE=2.98;time=20120612143340.862;'
  aux_file = ';SIEMENS;anatomy_T1_1mm'
  qform_code = '1'
  qfac = '-1'
  quatern_b = '-0'
  quatern_c = '1'
  quatern_d = '0'
  qoffset_x = '86.1506'
  qoffset_y = '-133.169'
  qoffset_z = '-127.675'
  sform_code = '1'
  sto_xyz_matrix = '-1 -0 -0 86.1506 -0 1 -0 -133.169 0 -0 1 -127.675 0 0 0 1'
  slice_code = '0'
  slice_start = '0'
  scl_end = '0'
  scl_duration = '0'

** fslhd information for the lesion file:**
shymaa@psylabhumants:~/Desktop/my_dataset/Participant/sub-03/anat$ fslhd -x sub-03_T1w_label-lesion_roi.nii.gz
<nifti_image
  image_offset = '352'
  ndim = '3'
  nx = '176'
  ny = '186'
  nz = '176'
  nt = '1'
  dx = '1'
  dy = '1'
  dz = '1'
  dt = '0'
  datatype = '16'
  nvox = '5761536'
  nbyper = '4'
  scl_slope = '1'
  scl_inter = '0'
  intent_code = '1002'
  intent_p1 = '0'
  intent_p2 = '0'
  intent_p3 = '0'
  intent_name = ''
  toffset = '0'
  xyz_units = '2'
  time_units = '8'
  freq_dim = '0'
  phase_dim = '0'
  slice_dim = '0'
  descrip = '6.0.3:b862cdd5'
  aux_file = 'Red-Yellow'
  qform_code = '1'
  qfac = '1'
  quatern_b = '0'
  quatern_c = '0'
  quatern_d = '0'
  qoffset_x = '-88.8494'
  qoffset_y = '-111.169'
  qoffset_z = '-80.6747'
  sform_code = '1'
  sto_xyz_matrix = '1 0 0 -88.8494 0 1 0 -111.169 0 0 1 -80.6747 0 0 0 1'
  slice_code = '0'
  slice_start = '0'
  scl_end = '0'
  scl_duration = '0'

**Comment by shaymaadarawshy** [comment]
Hi Chris, 
Did you get my respond?

thank you,
Shaymaa

**Comment by effigies** [comment]
Ah yes, I did. Sorry, I was on holidays. These images are definitely not the same size or orientation, and fMRIPrep currently assumes they are. The idea would be that each voxel in the mask corresponds to a voxel in the T1w image that contains lesion tissue.

The problem is that unless the voxels are actually aligned (which we would need to check), the interpretation of a mask that is not voxel-for-voxel depends on the resampling algorithm. We would prefer users to simply provide known good masks that are 1-1 with the image being masked.
