### ISSUE TITLE
TraitsError Only When Passing PyBids DB in --bids-database-dir

### ISSUE THREAD

**Issue by smeisler** [nipreps/fmriprep#2375]
fMRIPrep version: 20.2.1
Installation: Singularity container on Linux HPC
#### pybids
`pybids layout ${bids_dir} ${bids_dir}/code/pybids_db --no-validate
`
#### fmriprep
`singularity run -B ${bids_dir} -B ${scratch_dir}:/workdir -B ${bids_dir}/code/fmriprep/license.txt:/license.txt ${fmriprep_img} --participant_label NDARAA306NT2 --use-aroma -w /workdir --skip-bids-validation --mem_mb 16000 --fs-license-file /license.txt --bids-database-dir ${bids_dir}/code/pybids_db ${bids_dir} ${bids_dir}/derivatives participant
`

16GB of Memory and 16 CPUs via SLURM job scheduler.
## Error
```
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
210220-14:46:13,978 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 20.2.1:
      * BIDS dataset path: /om4/group/gablab/data/HBN.
      * Participant list: ['NDARAA306NT2'].
      * Run identifier: 20210220-144439_645015e1-4e7f-48a6-b5e8-9e88fa27a9be.
      * Output spaces: MNI152NLin2009cAsym:res-native.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /om4/group/gablab/data/HBN/derivatives/freesurfer.
210220-14:46:22,537 nipype.workflow INFO:
	 No single-band-reference found for sub-NDARAA306NT2_task-movieDM_bold.nii.gz.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 272, in init_func_preproc_wf
    tr=metadata.get("RepetitionTime")),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 633, in __init__
    from_file=from_file, resource_monitor=resource_monitor, **inputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 183, in __init__
    self.inputs = self.input_spec(**inputs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/specs.py", line 66, in __init__
    super(BaseTraitedSpec, self).__init__(**kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'tr' trait of a FunctionalSummaryInputSpec instance must be a float, but a value of None <class 'NoneType'> was specified.

```
## Notes
Bids-Validator raises no errors that relate to this subject (or others that have this error).

Running without the `--bids-database-dir` does not create this error, but I am working with a large dataset and do not want to recreate the PyBids database for each participant.

There are no previously computed results (e.g. FreeSurfer) and the work directory cache was cleared. 

I could see this also being a problem with PyBids, so [I have opened an issue there too.](https://github.com/bids-standard/pybids/issues/701)

I have replicated this error in two different datasets

**Comment by effigies** [comment]
It looks like you created the database separately. Could you try passing an empty directory, and letting fMRIPrep create the database? That will ensure there isn't a compatibility issue.

**Comment by smeisler** [comment]
> It looks like you created the database separately. Could you try passing an empty directory, and letting fMRIPrep create the database? That will ensure there isn't a compatibility issue.

Thanks for the quick reply! Unfortunately that doesn't seem to work:
`fmriprep: error: One or more participant labels were not found in the BIDS directory:` then it lists the subject name

**Comment by smeisler** [comment]
I am now trying to have fmriprep create the database by removing the --bids-database-dir argument entirely, and then save the database created in the work directory to use for other subjects.

**Comment by oesteban** [comment]
As I was mentioning in PyBIDS, it looks like your dataset is not BIDS valid. Please try without the flag `--skip-bids-validation`

**Comment by smeisler** [comment]
Sorry to revive an old thread, but I am getting this same error on version 20.2.3 even when using an Openneuro BIDS-validated dataset (https://openneuro.org/datasets/ds003604/versions/1.0.2). The dataset was additionally locally validated after I downloaded it, as well as during the pybids layout creation (I removed the `--no-validate` flag). The dataset is large enough that default runs of BIDS-validator run into maximum call stack errors, which I can avoid by using the `--ignoreSubjectConsistency` flag:

```
1: [ERR] Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED (code: 0 - INTERNAL ERROR)
		.undefined
			Evidence: RangeError: Maximum call stack size exceeded
    at missingSessionFiles (/src/validators/session.js:20:10)
    at /src/validators/bids/fullTest.js:199:42
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by mgxd** [comment]
I think it's reasonable to add the `--ignoreSubjectConsistency` flag (which [seems to be the recommendation](https://github.com/bids-standard/bids-validator/issues/1083) when working with large datasets) to the bids-validator check: https://github.com/nipreps/fmriprep/blob/1ac52cf8fb59cc5a3a7be01ae9e7186ab246f128/fmriprep/utils/bids.py#L73

Checking that any given file for one subject is present for all other subjects seems a bit excessive for fMRIPrep anyways
