### ISSUE TITLE
 - could the file be damaged?

### ISSUE THREAD

**Issue by miladseyfi** [nipreps/fmriprep#2381]
Hi dear developers 
I got following error 
File: /home/milad/Desktop/test/result/fmriprep/sub-08/log/20210304-221324_8b77a574-cdeb-4299-befe-57d549bc0e9a/crash-20210304-221402-milad-res_tmpl-29740927-47ae-498b-ab8a-66a9457776d8.txt
Working Directory: /home/milad/Desktop/test/work/fmriprep_wf/single_subject_08_wf/anat_preproc_wf/brain_extraction_wf/res_tmpl
Inputs:
clip: True
in_file: /home/milad/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz
order: 3
smooth: True
zooms: (4.0, 4.0, 4.0)
Traceback (most recent call last):
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 434, in run
    runtime = self._run_interface(runtime)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/niworkflows/interfaces/images.py", line 75, in _run_interface
    smooth=self.inputs.smooth,
  File "/home/milad/anaconda3/lib/python3.7/site-packages/niworkflows/utils/images.py", line 200, in resample_by_spacing
    data = gaussian_filter(in_file.get_fdata(), smooth)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nibabel/dataobj_images.py", line 356, in get_fdata
    data = np.asanyarray(self._dataobj, dtype=dtype)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 393, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 360, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nibabel/arrayproxy.py", line 339, in _get_unscaled
    mmap=self._mmap)
  File "/home/milad/anaconda3/lib/python3.7/site-packages/nibabel/volumeutils.py", line 534, in array_from_file
    getattr(infile, 'name', 'object')))
OSError: Expected 64364544 bytes, got 2249417 bytes from object
 - could the file be damaged?

Any help will be appreciated

**Comment by effigies** [comment]
I would try deleting `/home/milad/.cache/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz` and letting fMRIPrep re-download it.

**Comment by miladseyfi** [comment]
thanks for quick reply 
I did as you said but the processing stopped  again with new error : 


error tab in HTML file : 

 mri_cc -aseg aseg.auto_noCCseg.mgz -o aseg.auto.mgz -lta /home/milad/Desktop/test/result/freesurfer/sub-08/mri/transforms/cc_up.lta sub-08 

will read input aseg from aseg.auto_noCCseg.mgz
writing aseg with cc labels to aseg.auto.mgz
will write lta as /home/milad/Desktop/test/result/freesurfer/sub-08/mri/transforms/cc_up.lta
reading aseg from /home/milad/Desktop/test/result/freesurfer/sub-08/mri/aseg.auto_noCCseg.mgz
reading norm from /home/milad/Desktop/test/result/freesurfer/sub-08/mri/norm.mgz
45862 voxels in left wm, 53689 in right wm, xrange [168, 195]
searching rotation angles z=[-20 -6], y=[-4 10]

searching scale 1 Z rot -20.4  
searching scale 1 Z rot -20.2  
searching scale 1 Z rot -19.9  
searching scale 1 Z rot -19.7  
searching scale 1 Z rot -19.4  
searching scale 1 Z rot -19.2  
searching scale 1 Z rot -18.9  
searching scale 1 Z rot -18.7  
searching scale 1 Z rot -18.4  
searching scale 1 Z rot -18.2  
searching scale 1 Z rot -17.9  
searching scale 1 Z rot -17.7  
searching scale 1 Z rot -17.4  
searching scale 1 Z rot -17.2  
searching scale 1 Z rot -16.9  
searching scale 1 Z rot -16.7  
searching scale 1 Z rot -16.4  
searching scale 1 Z rot -16.2  
searching scale 1 Z rot -15.9  
searching scale 1 Z rot -15.7  
searching scale 1 Z rot -15.4  
searching scale 1 Z rot -15.2  
searching scale 1 Z rot -14.9  
searching scale 1 Z rot -14.7  
searching scale 1 Z rot -14.4  
searching scale 1 Z rot -14.2  
searching scale 1 Z rot -13.9  
searching scale 1 Z rot -13.7  
searching scale 1 Z rot -13.4  
searching scale 1 Z rot -13.2  
searching scale 1 Z rot -12.9  
searching scale 1 Z rot -12.7  
searching scale 1 Z rot -12.4  
searching scale 1 Z rot -12.2  
searching scale 1 Z rot -11.9  
searching scale 1 Z rot -11.7  
searching scale 1 Z rot -11.4  
searching scale 1 Z rot -11.2  
searching scale 1 Z rot -10.9  
searching scale 1 Z rot -10.7  
searching scale 1 Z rot -10.4  
searching scale 1 Z rot -10.2  
searching scale 1 Z rot -9.9  
searching scale 1 Z rot -9.7  
searching scale 1 Z rot -9.4  
searching scale 1 Z rot -9.2  
searching scale 1 Z rot -8.9  
searching scale 1 Z rot -8.7  
searching scale 1 Z rot -8.4  
searching scale 1 Z rot -8.2  
searching scale 1 Z rot -7.9  
searching scale 1 Z rot -7.7  
searching scale 1 Z rot -7.4  
searching scale 1 Z rot -7.2  
searching scale 1 Z rot -6.9  
searching scale 1 Z rot -6.7  
searching scale 1 Z rot -6.4  global minimum found at slice 183.0, rotations (3.23, -13.20)
final transformation (x=183.0, yr=3.230, zr=-13.197):
 0.97204   0.22830   0.05485  -79.26068;
-0.22794   0.97359  -0.01286   77.99773;
-0.05634   0.00000   0.99841   2.52578;
 0.00000   0.00000   0.00000   1.00000;
error: No such file or directory
error: mri_cc: no WM voxels found with norm > 40 -- check skull stripping

Command exited with non-zero status 253
@#@FSTIME  2021:03:05:01:19:42 mri_cc N 7 e 49.43 S 0.13 U 50.61 P 102% M 228632 F 6 R 72214 W 0 c 376 w 19 I 1336 O 0 L 3.19 2.79 2.70
@#@FSLOADPOST 2021:03:05:01:20:32 mri_cc N 7 2.85 2.75 2.69
Linux milad-Aspire-A715-71G 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-08 exited with ERRORS at ‫جۆمعه ۰۵ مارس ۲۱، ساعات ۰۱:۲۰:۳۲ (+0330)‬

For more details, see the log file /home/milad/Desktop/test/result/freesurfer/sub-08/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1



---------------------

error in the terminal : 

210305-01:20:34,768 nipype.workflow ERROR:
	 could not run node: fmriprep_wf.single_subject_08_wf.anat_preproc_wf.surface_recon_wf.autorecon_resume_wf.autorecon2_vol
210305-01:20:34,818 nipype.workflow CRITICAL:
	 fMRIPrep failed: Workflow did not execute cleanly. Check log for details
210305-01:20:35,409 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: 08 (1). Check the HTML reports for details.

**Comment by effigies** [comment]
```
error: No such file or directory
error: mri_cc: no WM voxels found with norm > 40 -- check skull stripping
```

In your FreeSurfer output directory, can you examine `mri/T1.mgz` and `mri/brain.mgz` to check the quality of the brain mask?

**Comment by miladseyfi** [comment]
It was not similar to the brain mask at all !! the mask was only local noisy regions .
So what is the solution ? Why the mask should be like this ?

**Comment by effigies** [comment]
Sorry for letting this fall by the wayside. It sounds like skull-stripping went poorly. Would you mind posting some screenshots of your T1w image? If you're able to share the image, we can try to reproduce the issue.
