### ISSUE TITLE
Duplicate node found' when trying to re-run fmriprep but after deleting output folder

### ISSUE THREAD

**Issue by mamuerie** [nipreps/fmriprep#2396]
### What version of fMRIPrep are you using?
20.2.1
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker (on windows with wsl2)
### What is the exact command-line you used?
```
docker run --rm -e DOCKER_VERSION_8395080871=20.10.5 -it -v C:\Users\Marie\Documents\license.txt:/opt/freesurfer/license.txt:ro -v c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP\sourcedata:/data:ro -v c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP\derivatives:/out -v c:\Users\Marie\Documents\IPU\Experiment\fMRIPrep\datasets\MOMAP\temp:/scratch nipreps/fmriprep:20.2.1 /data /out participant -vvv --participant-label 101 --md-only-boilerplate --dummy-scans 3 --skip-bids-validation --use-aroma --stop-on-first-crash --return-all-components -w /scratch --output-spaces MNI152NLin2009cAsym:res-2
```

### Have you checked that your inputs are BIDS valid?
Yes
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?

No
### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
210412-10:02:14,427 nipype.workflow WARNING:
         Previous output generated by version 0+unknown found.
210412-10:02:16,21 nipype.workflow IMPORTANT:

    Running fMRIPREP version 20.2.1:
      * BIDS dataset path: /data.
      * Participant list: ['101'].
      * Run identifier: 20210412-100157_dd88af26-6793-4ef3-9d6f-85131e864a0f.
      * Output spaces: MNI152NLin2009cAsym:res-2.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /out/freesurfer.
210412-10:02:17,317 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-0back_run-01_bold.nii.gz.
210412-10:02:18,167 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:18,263 nipype.interface INFO:
         We advise you to upgrade DIPY version. This upgrade will open access to more function
210412-10:02:18,267 nipype.interface INFO:
         We advise you to upgrade DIPY version. This upgrade will open access to more function
210412-10:02:18,269 nipype.interface INFO:
         We advise you to upgrade DIPY version. This upgrade will open access to more models
210412-10:02:18,553 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-0back_run-02_bold.nii.gz.
210412-10:02:19,201 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:19,480 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-aachen_run-01_bold.nii.gz.
210412-10:02:20,126 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:20,390 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-aachen_run-02_bold.nii.gz.
210412-10:02:21,52 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:21,327 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-main_run-01_bold.nii.gz.
210412-10:02:22,106 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:22,383 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-main_run-02_bold.nii.gz.
210412-10:02:23,64 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:23,343 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-main_run-03_bold.nii.gz.
210412-10:02:24,1 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:24,275 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-main_run-04_bold.nii.gz.
210412-10:02:24,936 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:25,214 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-main_run-05_bold.nii.gz.
210412-10:02:25,858 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:26,133 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-main_run-06_bold.nii.gz.
210412-10:02:26,800 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:27,134 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-rest_run-01_bold.nii.
210412-10:02:27,499 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:27,722 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-rest_run-01_bold.nii.gz.
210412-10:02:28,394 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 321, in init_single_subject_wf
    ('outputnode.fsnative2t1w_xfm', 'inputnode.fsnative2t1w_xfm')]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 158, in connect
    self._check_nodes(newnodes)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 766, in _check_nodes    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "func_preproc_task_rest_run_01_wf" found.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
Kind of. A few months ago I already analyzed this subject but I deleted the derivatives and temp folder (it was the first try of using the pipeline with different parameters).

It seems to be a similar problem as in issue #2063 but unfortunately, I can not solve it by deleting the old files (or restarting pc and docker). Or are there somewhere hidden files I need to remove as well? 
Thanks for your help and your awesome work so far!

**Comment by effigies** [comment]
```
         No single-band-reference found for sub-101_task-rest_run-01_bold.nii.
210412-10:02:27,499 nipype.workflow IMPORTANT:
         Slice-timing correction will be included.
210412-10:02:27,722 nipype.workflow INFO:
         No single-band-reference found for sub-101_task-rest_run-01_bold.nii.gz.
```

It looks like you have compressed and uncompressed versions of this image. Since the subworkflows are based on the filenames (but not extensions), when fMRIPrep tried to create the second, it collided. Probably better than running everything twice, but we could try to give a clearer error here.

**Comment by mamuerie** [comment]
Ah, I was not aware of the second uncompressed version, that explains a lot. Thanks for the fast response! 
And yes, I agree a more specific error message would be helpful here.
