### ISSUE TITLE
Talairach Failure Detection

### ISSUE THREAD

**Issue by shaymaadarawshy** [nipreps/fmriprep#2404]
Hi, 
I'm running Fmriprep on patients with huge brain lesions, and I got this error for two of my patients.
This is the code I'm running: **fmriprep-docker /home/shymaa/Desktop/my_dataset/Participant /home/shymaa/Desktop/my_dataset/Participant/derivative participant --participant-label 07 --fs-license-file /home/shymaa/Desktop/license.txt --use-aroma --cifti-outputs**

Error: 
Node: fmriprep_wf.single_subject_07_wf.anat_preproc_wf.surface_recon_wf.autorecon1
Working directory: /tmp/work/fmriprep_wf/single_subject_07_wf/anat_preproc_wf/surface_recon_wf/autorecon1

Node inputs:

FLAIR_file = <undefined>
T1_files = <undefined>
T2_file = <undefined>
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = autorecon1
environ = {}
expert = <undefined>
flags = <undefined>
hemi = <undefined>
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = <undefined>
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
steps = <undefined>
subject_id = recon_all
subjects_dir = <undefined>
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 745, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
recon-all -autorecon1 -i /data/sub-07/anat/sub-07_T1w.nii.gz -noskullstrip -openmp 8 -subjid sub-07 -sd /out/freesurfer
Standard output:
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /out/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
Linux 1f98b6a77b48 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/out/freesurfer/sub-07/scripts/recon-all.local-copy'
/out/freesurfer/sub-07

 mri_convert /data/sub-07/anat/sub-07_T1w.nii.gz /out/freesurfer/sub-07/mri/orig/001.mgz 

mri_convert.bin /data/sub-07/anat/sub-07_T1w.nii.gz /out/freesurfer/sub-07/mri/orig/001.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /data/sub-07/anat/sub-07_T1w.nii.gz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (0.990846, 0.00867391, -0.134721)
j_ras = (-0.0205356, 0.996005, -0.086908)
k_ras = (0.133429, 0.088879, 0.987065)
writing to /out/freesurfer/sub-07/mri/orig/001.mgz...
#--------------------------------------------
#@# MotionCor Mon Apr  5 09:47:52 UTC 2021
Found 1 runs
/out/freesurfer/sub-07/mri/orig/001.mgz
Checking for (invalid) multi-frame inputs...
WARNING: only one run found. This is OK, but motion
correction cannot be performed on one run, so I'll
copy the run to rawavg and continue.

 cp /out/freesurfer/sub-07/mri/orig/001.mgz /out/freesurfer/sub-07/mri/rawavg.mgz 

/out/freesurfer/sub-07

 mri_convert /out/freesurfer/sub-07/mri/rawavg.mgz /out/freesurfer/sub-07/mri/orig.mgz --conform 

mri_convert.bin /out/freesurfer/sub-07/mri/rawavg.mgz /out/freesurfer/sub-07/mri/orig.mgz --conform 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /out/freesurfer/sub-07/mri/rawavg.mgz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (0.990846, 0.00867391, -0.134721)
j_ras = (-0.0205356, 0.996005, -0.086908)
k_ras = (0.133429, 0.088879, 0.987065)
changing data type from float to uchar (noscale = 0)...
MRIchangeType: Building histogram 
Reslicing using trilinear interpolation 
writing to /out/freesurfer/sub-07/mri/orig.mgz...

 mri_add_xform_to_header -c /out/freesurfer/sub-07/mri/transforms/talairach.xfm /out/freesurfer/sub-07/mri/orig.mgz /out/freesurfer/sub-07/mri/orig.mgz 

INFO: extension is mgz
#--------------------------------------------
#@# Talairach Mon Apr  5 09:48:04 UTC 2021
/out/freesurfer/sub-07/mri

 mri_nu_correct.mni --no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50 

/out/freesurfer/sub-07/mri
/opt/freesurfer/bin/mri_nu_correct.mni
--no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50
nIters 1
$Id: mri_nu_correct.mni,v 1.27 2016/02/26 16:19:49 mreuter Exp $
Linux 1f98b6a77b48 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Mon Apr  5 09:48:04 UTC 2021
Program nu_correct, built from:
Package MNI N3, version 1.12.0, compiled by nicks@terrier (x86_64-unknown-linux-gnu) on 2015-06-19 at 01:25:34
/usr/bin/bc
tmpdir is ./tmp.mri_nu_correct.mni.548
/out/freesurfer/sub-07/mri
mri_convert orig.mgz ./tmp.mri_nu_correct.mni.548/nu0.mnc -odt float
mri_convert.bin orig.mgz ./tmp.mri_nu_correct.mni.548/nu0.mnc -odt float 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from orig.mgz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
changing data type from uchar to float (noscale = 0)...
writing to ./tmp.mri_nu_correct.mni.548/nu0.mnc...
 
--------------------------------------------------------
Iteration 1 Mon Apr  5 09:48:07 UTC 2021
nu_correct -clobber ./tmp.mri_nu_correct.mni.548/nu0.mnc ./tmp.mri_nu_correct.mni.548/nu1.mnc -tmpdir ./tmp.mri_nu_correct.mni.548/0/ -iterations 1000 -distance 50
[root@1f98b6a77b48:/out/freesurfer/sub-07/mri/] [2021-04-05 09:48:07] running:
  /opt/freesurfer/mni/bin/nu_estimate_np_and_em -parzen -log -sharpen 0.15 0.01 -iterations 1000 -stop 0.001 -shrink 4 -auto_mask -nonotify -b_spline 1.0e-7 -distance 50 -quiet -execute -clobber -nokeeptmp -tmpdir ./tmp.mri_nu_correct.mni.548/0/ ./tmp.mri_nu_correct.mni.548/nu0.mnc ./tmp.mri_nu_correct.mni.548/nu1.imp

Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Number of iterations: 40 
CV of field change: 0.000988835
 
 
 
mri_convert ./tmp.mri_nu_correct.mni.548/nu1.mnc orig_nu.mgz --like orig.mgz --conform
mri_convert.bin ./tmp.mri_nu_correct.mni.548/nu1.mnc orig_nu.mgz --like orig.mgz --conform 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from ./tmp.mri_nu_correct.mni.548/nu1.mnc...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
INFO: transform src into the like-volume: orig.mgz
changing data type from float to uchar (noscale = 0)...
MRIchangeType: Building histogram 
writing to orig_nu.mgz...
 
 
Mon Apr  5 09:50:29 UTC 2021
mri_nu_correct.mni done

 talairach_avi --i orig_nu.mgz --xfm transforms/talairach.auto.xfm 

talairach_avi log file is transforms/talairach_avi.log...
Started at Mon Apr 5 09:50:29 UTC 2021
Ended   at Mon Apr  5 09:51:17 UTC 2021
talairach_avi done

 cp transforms/talairach.auto.xfm transforms/talairach.xfm 

#--------------------------------------------
#@# Talairach Failure Detection Mon Apr  5 09:51:19 UTC 2021
/out/freesurfer/sub-07/mri

 talairach_afd -T 0.005 -xfm transforms/talairach.xfm 

ERROR: talairach_afd: Talairach Transform: transforms/talairach.xfm ***FAILED*** (p=0.0000, pval=0.0000 < threshold=0.0050)

Manual Talairach alignment may be necessary, or
include the -notal-check flag to skip this test,
making sure the -notal-check flag follows -all
or -autorecon1 in the command string.
See:

http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Talairach

INFO: Retrying Talairach align using 3T-based atlas...

#--------------------------------------------
#@# Talairach Mon Apr  5 09:51:19 UTC 2021
/out/freesurfer/sub-07/mri

 mri_nu_correct.mni --no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50 

/out/freesurfer/sub-07/mri
/opt/freesurfer/bin/mri_nu_correct.mni
--no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50
nIters 1
$Id: mri_nu_correct.mni,v 1.27 2016/02/26 16:19:49 mreuter Exp $
Linux 1f98b6a77b48 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Mon Apr  5 09:51:19 UTC 2021
Program nu_correct, built from:
Package MNI N3, version 1.12.0, compiled by nicks@terrier (x86_64-unknown-linux-gnu) on 2015-06-19 at 01:25:34
/usr/bin/bc
tmpdir is ./tmp.mri_nu_correct.mni.4743
/out/freesurfer/sub-07/mri
mri_convert orig.mgz ./tmp.mri_nu_correct.mni.4743/nu0.mnc -odt float
mri_convert.bin orig.mgz ./tmp.mri_nu_correct.mni.4743/nu0.mnc -odt float 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from orig.mgz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
changing data type from uchar to float (noscale = 0)...
writing to ./tmp.mri_nu_correct.mni.4743/nu0.mnc...
 
--------------------------------------------------------
Iteration 1 Mon Apr  5 09:51:22 UTC 2021
nu_correct -clobber ./tmp.mri_nu_correct.mni.4743/nu0.mnc ./tmp.mri_nu_correct.mni.4743/nu1.mnc -tmpdir ./tmp.mri_nu_correct.mni.4743/0/ -iterations 1000 -distance 50
[root@1f98b6a77b48:/out/freesurfer/sub-07/mri/] [2021-04-05 09:51:23] running:
  /opt/freesurfer/mni/bin/nu_estimate_np_and_em -parzen -log -sharpen 0.15 0.01 -iterations 1000 -stop 0.001 -shrink 4 -auto_mask -nonotify -b_spline 1.0e-7 -distance 50 -quiet -execute -clobber -nokeeptmp -tmpdir ./tmp.mri_nu_correct.mni.4743/0/ ./tmp.mri_nu_correct.mni.4743/nu0.mnc ./tmp.mri_nu_correct.mni.4743/nu1.imp

Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Number of iterations: 40 
CV of field change: 0.000988835
 
 
 
mri_convert ./tmp.mri_nu_correct.mni.4743/nu1.mnc orig_nu.mgz --like orig.mgz --conform
mri_convert.bin ./tmp.mri_nu_correct.mni.4743/nu1.mnc orig_nu.mgz --like orig.mgz --conform 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from ./tmp.mri_nu_correct.mni.4743/nu1.mnc...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
INFO: transform src into the like-volume: orig.mgz
changing data type from float to uchar (noscale = 0)...
MRIchangeType: Building histogram 
writing to orig_nu.mgz...
 
 
Mon Apr  5 09:54:03 UTC 2021
mri_nu_correct.mni done

 talairach_avi --i orig_nu.mgz --xfm transforms/talairach.auto.xfm --atlas 3T18yoSchwartzReactN32_as_orig 

talairach_avi log file is transforms/talairach_avi.log...
Started at Mon Apr 5 09:54:04 UTC 2021
Ended   at Mon Apr  5 09:54:49 UTC 2021
talairach_avi done

 cp transforms/talairach.auto.xfm transforms/talairach.xfm 

#--------------------------------------------
#@# Talairach Failure Detection Mon Apr  5 09:54:52 UTC 2021
/out/freesurfer/sub-07/mri

 talairach_afd -T 0.005 -xfm transforms/talairach.xfm 

talairach_afd: Talairach Transform: transforms/talairach.xfm OK (p=0.4905, pval=0.1531 >= threshold=0.0050)

 awk -f /opt/freesurfer/bin/extract_talairach_avi_QA.awk /out/freesurfer/sub-07/mri/transforms/talairach_avi.log 

 tal_QC_AZS /out/freesurfer/sub-07/mri/transforms/talairach_avi.log 

TalAviQA: 0.85645
z-score: -27
WARNING: Talairach QA check failed!
z-score of -27 is <= threshold of -9

Manual Talairach alignment may be necessary, or
include the -notal-check flag to skip this test,
making sure the -notal-check flag follows -all
or -autorecon1 in the command string.
See:

http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Talairach

INFO: Trying MINC mritotal to perform Talairach align...

#--------------------------------------------
#@# Talairach Mon Apr  5 09:54:52 UTC 2021
/out/freesurfer/sub-07/mri

 mri_nu_correct.mni --no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50 

/out/freesurfer/sub-07/mri
/opt/freesurfer/bin/mri_nu_correct.mni
--no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50
nIters 1
$Id: mri_nu_correct.mni,v 1.27 2016/02/26 16:19:49 mreuter Exp $
Linux 1f98b6a77b48 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Mon Apr  5 09:54:52 UTC 2021
Program nu_correct, built from:
Package MNI N3, version 1.12.0, compiled by nicks@terrier (x86_64-unknown-linux-gnu) on 2015-06-19 at 01:25:34
/usr/bin/bc
tmpdir is ./tmp.mri_nu_correct.mni.6926
/out/freesurfer/sub-07/mri
mri_convert orig.mgz ./tmp.mri_nu_correct.mni.6926/nu0.mnc -odt float
mri_convert.bin orig.mgz ./tmp.mri_nu_correct.mni.6926/nu0.mnc -odt float 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from orig.mgz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
changing data type from uchar to float (noscale = 0)...
writing to ./tmp.mri_nu_correct.mni.6926/nu0.mnc...
 
--------------------------------------------------------
Iteration 1 Mon Apr  5 09:54:55 UTC 2021
nu_correct -clobber ./tmp.mri_nu_correct.mni.6926/nu0.mnc ./tmp.mri_nu_correct.mni.6926/nu1.mnc -tmpdir ./tmp.mri_nu_correct.mni.6926/0/ -iterations 1000 -distance 50
[root@1f98b6a77b48:/out/freesurfer/sub-07/mri/] [2021-04-05 09:54:55] running:
  /opt/freesurfer/mni/bin/nu_estimate_np_and_em -parzen -log -sharpen 0.15 0.01 -iterations 1000 -stop 0.001 -shrink 4 -auto_mask -nonotify -b_spline 1.0e-7 -distance 50 -quiet -execute -clobber -nokeeptmp -tmpdir ./tmp.mri_nu_correct.mni.6926/0/ ./tmp.mri_nu_correct.mni.6926/nu0.mnc ./tmp.mri_nu_correct.mni.6926/nu1.imp

Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Processing:.................................................................Done
Number of iterations: 40 
CV of field change: 0.000988835
 
 
 
mri_convert ./tmp.mri_nu_correct.mni.6926/nu1.mnc orig_nu.mgz --like orig.mgz --conform
mri_convert.bin ./tmp.mri_nu_correct.mni.6926/nu1.mnc orig_nu.mgz --like orig.mgz --conform 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from ./tmp.mri_nu_correct.mni.6926/nu1.mnc...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
INFO: transform src into the like-volume: orig.mgz
changing data type from float to uchar (noscale = 0)...
MRIchangeType: Building histogram 
writing to orig_nu.mgz...
 
 
Mon Apr  5 09:57:40 UTC 2021
mri_nu_correct.mni done

 talairach --i orig_nu.mgz --xfm transforms/talairach.auto.xfm 

/out/freesurfer/sub-07/mri
/opt/freesurfer/bin/talairach
--i orig_nu.mgz --xfm transforms/talairach.auto.xfm
$Id: talairach,v 1.8 2016/02/16 17:17:20 zkaufman Exp $
Linux 1f98b6a77b48 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Mon Apr  5 09:57:40 UTC 2021
tmpdir is transforms/tmp.talairach.7643
/out/freesurfer/sub-07/mri
mri_convert orig_nu.mgz transforms/tmp.talairach.7643/src.mnc
mri_convert.bin orig_nu.mgz transforms/tmp.talairach.7643/src.mnc 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from orig_nu.mgz...
TR=0.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 7.45058e-09, -1)
k_ras = (-9.31323e-10, 1, -7.45058e-09)
writing to transforms/tmp.talairach.7643/src.mnc...
--------------------------------------------
mritotal -verbose -debug -clobber -modeldir /opt/freesurfer/mni/bin/../share/mni_autoreg -protocol icbm transforms/tmp.talairach.7643/src.mnc transforms/talairach.auto.xfm
Transforming slices:................................................................................................................................Done
Copying chunks:......................................................................................................................................................Done.
Copying chunks:..........................................................................................................Done.
Transforming slices:......................................................................................................................................................Done
Copying chunks:....................................................................................................................Done.
Copying chunks:....................................................................................................................Done.
Source volume size:  74  by 106  by 106 
Source voxel size =    2.000    2.000    2.000
Source min/max real range =   -0.000  157.547
Source min/max voxel=   -0.000  157.547

Target volume size:  58  by 110  by 86 
Target voxel =    2.000    2.000    2.000
Target min/max real range=    0.970  123.710
Target min/max voxel =   -0.000  123.710

AFTER init_params()
Transform matrix    =    1.0000    0.0000    0.0000    4.1908 
                         0.0000    1.0000    0.0000  -10.2661 
                         0.0000    0.0000    1.0000   33.3827 

Transform center   =   -3.863   -7.325  -23.928
Transform rotations  =    0.000    0.000    0.000
Transform trans    =    4.191  -10.266   33.383
Transform scale    =    1.000    1.000    1.000
Transform shear    =    0.000    0.000    0.000

Target volume is smallest
Lattice step size  =    4.000    4.000    4.000
Lattice start      =  -85.095 -125.510  -47.250
Lattice count      =       43       55       29

Source volume size:  84  by 116  by 116 
Source voxel size =    2.000    2.000    2.000
Source min/max real range =   -0.000  214.907
Source min/max voxel=   -0.000  214.907

Target volume size:  68  by 110  by 86 
Target voxel =    2.000    2.000    2.000
Target min/max real range=   -0.000  144.070
Target min/max voxel =   -0.000  144.070

AFTER init_params()
Transform matrix    =    0.8973   -0.2092   -0.1398   -1.3581 
                         0.1477    0.8571   -0.3348  -11.7152 
                         0.2037    0.3002    0.8584   46.4240 

Transform center   =   -3.863   -7.325  -23.928
Transform rotations  =    0.336   -0.220    0.163
Transform trans    =    3.916   -3.227   46.826
Transform scale    =    0.932    0.932    0.932
Transform shear    =   -0.000    0.000   -0.000

Target volume is smallest
Lattice step size  =    4.000    4.000    4.000
Lattice start      =  -85.095 -125.510  -57.250
Lattice count      =       43       55       34

Source volume size:  84  by 116  by 116 
Source voxel size =    2.000    2.000    2.000
Source min/max real range =    0.023   24.915
Source min/max voxel=    0.023   24.915

Target volume size:  68  by 110  by 86 
Target voxel =    2.000    2.000    2.000
Target min/max real range=    0.037   11.652
Target min/max voxel =    0.037   11.652

AFTER init_params()
Transform matrix    =    0.8493   -0.3524   -0.1329   -1.8151 
                         0.2467    0.7682   -0.4605  -13.8695 
                         0.2846    0.3857    0.7959   37.7361 

Transform center   =   -3.863   -7.325  -23.928
Transform rotations  =    0.451   -0.311    0.283
Transform trans    =    4.529   -2.106   38.697
Transform scale    =    0.929    0.929    0.929
Transform shear    =   -0.000    0.000    0.000

Target volume is smallest
Lattice step size  =    4.000    4.000    4.000
Lattice start      =  -65.095 -105.510  -57.250
Lattice count      =       35       46       34

Source volume size:  84  by 116  by 116 
Source voxel size =    2.000    2.000    2.000
Source min/max real range =    0.023   24.915
Source min/max voxel=    0.023   24.915

Target volume size:  68  by 110  by 86 
Target voxel =    2.000    2.000    2.000
Target min/max real range=    0.037   11.652
Target min/max voxel =    0.037   11.652

AFTER init_params()
Transform matrix    =    0.8413   -0.3229    0.1654  -19.8003 
                         0.3494    0.8335   -0.1501   23.9121 
                        -0.0976    0.2009    0.8885   10.4402 

Transform center   =   -3.863   -7.325  -23.928
Transform rotations  =    0.222    0.107    0.394
Transform trans    =  -20.779   27.373   12.013
Transform scale    =    0.916    0.916    0.916
Transform shear    =   -0.000   -0.000    0.000

Target volume is smallest
Lattice step size  =    4.000    4.000    4.000
Lattice start      =  -65.095 -105.510  -57.250
Lattice count      =       35       46       34

Source volume size:  84  by 116  by 116 
Source voxel size =    2.000    2.000    2.000
Source min/max real range =    0.023   24.915
Source min/max voxel=    0.023   24.915

Target volume size:  68  by 110  by 86 
Target voxel =    2.000    2.000    2.000
Target min/max real range=    0.037   11.652
Target min/max voxel =    0.037   11.652

AFTER init_params()
Transform matrix    =    0.7832   -0.3616    0.0905  -12.9926 
                         0.5471    1.1481   -0.1464   21.9242 
                        -0.0406    0.1307    0.8739    2.7341 

Transform center   =   -3.863   -7.325  -23.928
Transform rotations  =    0.149    0.046    0.442
Transform trans    =  -11.671   22.228    4.950
Transform scale    =    0.867    1.280    0.885
Transform shear    =    0.000    0.000   -0.000

Target volume is smallest
Lattice step size  =    4.000    4.000    4.000
Lattice start      =  -65.095 -105.510  -57.250
Lattice count      =       35       46       34

Source volume size:  84  by 116  by 116 
Source voxel size =    2.000    2.000    2.000
Source min/max real range =    0.023   24.915
Source min/max voxel=    0.023   24.915

Target volume size:  68  by 110  by 86 
Target voxel =    2.000    2.000    2.000
Target min/max real range=    0.037   11.652
Target min/max voxel =    0.037   11.652

AFTER init_params()
Transform matrix    =    0.7722   -0.3700    0.0882  -13.1052 
                         0.5643    1.1383   -0.1659   21.3297 
                        -0.0313    0.1427    0.8723    3.0791 

Transform center   =   -3.863   -7.325  -23.928
Transform rotations  =    0.162    0.035    0.456
Transform trans    =  -11.625   22.108    5.209
Transform scale    =    0.861    1.281    0.884
Transform shear    =   -0.000   -0.000    0.000

Target volume is smallest
Lattice step size  =    4.000    4.000    4.000
Lattice start      =  -65.095 -105.510  -57.250
Lattice count      =       35       46       34

 
 
Mon Apr  5 09:57:52 UTC 2021
talairach done

 cp transforms/talairach.auto.xfm transforms/talairach.xfm 

#--------------------------------------------
#@# Talairach Failure Detection Mon Apr  5 09:57:54 UTC 2021
/out/freesurfer/sub-07/mri

 talairach_afd -T 0.005 -xfm transforms/talairach.xfm 

ERROR: talairach_afd: Talairach Transform: transforms/talairach.xfm ***FAILED*** (p=0.0442, pval=0.0034 < threshold=0.0050)

Manual Talairach alignment may be necessary, or
include the -notal-check flag to skip this test,
making sure the -notal-check flag follows -all
or -autorecon1 in the command string.
See:

http://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/Talairach

ERROR: Talairach failed!

Linux 1f98b6a77b48 5.8.0-45-generic #51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-07 exited with ERRORS at Mon Apr  5 09:57:55 UTC 2021

For more details, see the log file /out/freesurfer/sub-07/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1

**How can I fix this error?** 

**thank you,
Shaymaa**

**Comment by shaymaadarawshy** [comment]
@effigies Dear Chris, can you help with this error? 
Thank you,
Shaymaa

**Comment by effigies** [comment]
Hi, thanks for the nudge. Could you share a screenshot of the subject's T1w image? If Talairach registration fails, there's often a visible issue with the image.

**Comment by shaymaadarawshy** [comment]
Dear Chris, 
Attached are  the T1 of both subject who failed the Talariach alignment.
![T1-07](https://user-images.githubusercontent.com/76255721/117568830-52447580-b0cb-11eb-9816-8a211df61523.png)
![T1-09](https://user-images.githubusercontent.com/76255721/117568835-56709300-b0cb-11eb-8f9f-9be48164c39a.png)

**Comment by effigies** [comment]
Sorry for letting this one fall by the wayside. I'm not an expert in FreeSurfer, so I would recommend working with the FreeSurfer team to process subjects with such severe lesions. You can then provide the pre-computed FreeSurfer directory to fMRIPrep.

You will also probably want to have a [lesion mask](https://fmriprep.org/en/stable/workflows.html?highlight=lesion#cost-function-masking-during-spatial-normalization) in your dataset to improve spatial normalization.
