### ISSUE TITLE
Files with such naming scheme are not part of BIDS specification

### ISSUE THREAD

**Issue by saiprasanna06** [nipreps/fmriprep#2413]
```
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.6 -it -v C:\Users\saipr\Desktop\dataset:/data:ro -v C:\Users\saipr\Desktop\op:/out nipreps/fmriprep:20.2.1 /data /out participant
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
bids-validator@1.4.0

        1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./sub-pddn11/func/sub-pddn11_task-rest_bold.nii/sub-pddn11_task-rest_bold.nii
                        Evidence: sub-pddn11_task-rest_bold.nii

        Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.

        1: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered based on the presence of only one author field. Please ignore if all contributors are already properly listed. (code: 102 - TOO_FEW_AUTHORS)

        Please visit https://neurostars.org/search?q=TOO_FEW_AUTHORS for existing conversations about this issue.


        Summary:                 Available Tasks:        Available Modalities:
        146 Files, 1.46GB        rest                    T1w
        28 - Subjects                                    bold
        1 - Session                                      physio


        If you have any questions, please post on https://neurostars.org/tags/bids.

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 703, in parse_args
    config.environment.exec_env, opts.bids_dir, opts.participant_label
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/utils/bids.py", line 155, in validate_input_dir
    subprocess.check_call(['bids-validator', bids_dir, '-c', temp.name])
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', PosixPath('/data'), '-c', '/tmp/tmpzvyqf1fx']' returned non-zero exit status 1.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues



```

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by effigies** [comment]
Looks like a directory got created and the file got dropped inside:

```
./sub-pddn11/func/sub-pddn11_task-rest_bold.nii/sub-pddn11_task-rest_bold.nii
```

Should probably be:

```
./sub-pddn11/func/sub-pddn11_task-rest_bold.nii
```

**Comment by saiprasanna06** [comment]
You're right ! I have over looked. Thanks so much.
