### ISSUE TITLE
error while converting to bids format 

### ISSUE THREAD

**Issue by Kang1448** [nipreps/fmriprep#2479]
please see the content of the JSON file required for conversion here: https://drive.google.com/file/d/1HIAJF-0a7rLGqgI4vOagiP-9N6ETYbQD/view?usp=sharing

MacdeMacBook-Pro:build mac$ dcm2bids -d $HOME/learning/sub-08 -p 01 -c $HOME/learning/config3.json -o $HOME/learning --forceDcm2niix
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/dcm2bids", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dcm2bids/dcm2bids.py", line 290, in main
    app = Dcm2bids(**vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dcm2bids/dcm2bids.py", line 51, in __init__
    self.config = load_json(config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dcm2bids/utils.py", line 55, in load_json
    data = json.load(f, object_pairs_hook=OrderedDict)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 83 column 7 (char 1873)
MacdeMacBook-Pro:build mac$

**Comment by effigies** [comment]
Hi, this would be better targeted at the dcm2bids project.

**Comment by effigies** [comment]
https://github.com/unfmontreal/Dcm2Bids/issues
