### ISSUE TITLE
trouble running singularity batch with 20.2.3

### ISSUE THREAD

**Issue by tanya-wen** [nipreps/fmriprep#2498]
### What version of fMRIPrep are you using?

20.2.3

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

Singularity

### What is the exact command-line you used?
```
#!/bin/bash
#
#SBATCH -J fmriprep
#SBATCH --time=100:00:00
#SBATCH -n 1
#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=4G
#SBATCH -p common  # Queue names you can submit to
# Outputs ----------------------------------
#SBATCH -o slurm_%A_%a.out
#SBATCH -e slurm_%A_%a.err
#SBATCH --mail-user=tanya.wen@duke.edu
#SBATCH --mail-type=ALL
# ------------------------------------------
##SBATCH --requeue
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.

BIDS_DIR="$STUDY/tw260/TreeTask.01/Nifti"

# Prepare some writeable bind-mount points.
TEMPLATEFLOW_HOST_HOME=$HOME/.cache/templateflow
FMRIPREP_HOST_CACHE=$HOME/.cache/fmriprep
mkdir -p ${TEMPLATEFLOW_HOST_HOME}
mkdir -p ${FMRIPREP_HOST_CACHE}

# Make sure FS_LICENSE is defined in the container.
export SINGULARITYENV_FS_LICENSE=$STUDY/.freesurfer.txt

# Designate a templateflow bind-mount point
export SINGULARITYENV_TEMPLATEFLOW_HOME="/templateflow"

#Specify the singularity command which sets up the environment, binds the $STUDY path to the bind mount point inside the container, and specifies the singularity image
SINGULARITY_CMD="singularity run --cleanenv -B $STUDY:/study -B ${TEMPLATEFLOW_HOST_HOME}:${SINGULARITYENV_TEMPLATEFLOW_HOME} -B /work:/mnt $STUDY/my_images/fmriprep-20.2.3.simg"

# Parse the participants.tsv file and extract one subject ID from the line corresponding to this SLURM task.
subject=$( sed -n -E "$((${SLURM_ARRAY_TASK_ID} + 1))s/sub-(\S*)\>.*/\1/gp" ${BIDS_DIR}/participants.tsv )

# Compose the command line
cmd="${SINGULARITY_CMD} /study/tw260/TreeTask.01/Nifti /study/tw260/TreeTask.01/derivatives participant --participant-label $subject -w /mnt --dummy-scans 5 -vv --omp-nthreads 8 --nthreads 12 --mem_mb 50000 --fs-license-file /study/freesurfer.txt"

# Setup done, run the command
echo Running task ${SLURM_ARRAY_TASK_ID}
echo Commandline: $cmd
eval $cmd
exitcode=$?

# Output results to a table
echo "sub-$subject   ${SLURM_ARRAY_TASK_ID}    $exitcode" \
      >> ${SLURM_JOB_NAME}.${SLURM_ARRAY_JOB_ID}.tsv
echo Finished tasks ${SLURM_ARRAY_TASK_ID} with exit code $exitcode
exit $exitcode
```

### Have you checked that your inputs are BIDS valid?

Yes

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
https://drive.google.com/file/d/1qaOYK6Y5h4wlm6W25Wu0jxniOMYpIXWO/view?usp=sharing

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
Node Name: fmriprep_wf.single_subject_bNShh19_wf.anat_preproc_wf.brain_extraction_wf.inu_n4
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 292, in _send_procs_to_workers
    num_subnodes = self.procs[jobid].num_subnodes()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1308, in num_subnodes
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1322, in _get_inputs
    super(MapNode, self)._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 580, in _get_inputs
    outputs = _load_resultfile(results_fname).outputs
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 293, in load_resultfile
    result = loadpkl(results_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 666, in loadpkl
    raise e
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/filemanip.py", line 643, in loadpkl
    unpkl = pickle.loads(pkl_contents)
ModuleNotFoundError: No module named 'niworkflows.interfaces.ants'

```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

https://drive.google.com/file/d/1wyDsCEMw6uoPkSJqPABZGaW-qVUUdU0p/view?usp=sharing

I only recently switched to version 20.2.3 because of the bug associated with 20.1.1 (https://github.com/nipreps/fmriprep/issues/2307). I was able to run my singularity batch code with version 20.1.1 without any crashes, but after the update, it seems to not be able to run pass even the anatomical preprocessing. I thought to debug with just running a single subject with the command:

```
singularity run --cleanenv -B /hpc/group/egnerlab:/mnt \
/hpc/group/egnerlab/my_images/fmriprep-20.2.3.simg \
/mnt/tw260/TreeTask.01/Nifti \
/mnt/tw260/TreeTask.01/derivatives \
participant \
--fs-license-file /mnt/freesurfer.txt \
--participant-label bNShh03 \
--dummy-scans 5
```

And when doing so with a single subject, there are no crashes, and can run successfully. So I'm not sure what the problem is. 

In the .out file generated from the batch submission, is seems to be putting everything into cache:

```
210806-06:48:18,809 nipype.workflow IMPORTANT:
	 fMRIPrep started!
210806-06:48:19,549 nipype.workflow INFO:
	 Workflow fmriprep_wf settings: ['check', 'execution', 'logging', 'monitoring']
210806-06:48:21,276 nipype.workflow INFO:
	 Running in parallel.
210806-06:48:21,302 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 33 jobs ready. Free memory (GB): 50.00/50.00, Free processors: 12/12.
210806-06:48:21,470 nipype.workflow INFO:
	 [Job 0] Cached (fmriprep_wf.single_subject_bNShh19_wf.func_preproc_task_tree_run_04_wf.bold_std_trans_wf.select_tpl).
210806-06:48:21,474 nipype.workflow INFO:
	 [Job 1] Cached (fmriprep_wf.single_subject_bNShh19_wf.func_preproc_task_tree_run_04_wf.bold_std_trans_wf.split_target).
210806-06:48:21,477 nipype.workflow INFO:
	 [Job 2] Cached (fmriprep_wf.single_subject_bNShh19_wf.func_preproc_task_tree_run_04_wf.func_derivatives_wf.spacesource).
210806-06:48:21,479 nipype.workflow INFO:
	 [Job 3] Cached (fmriprep_wf.single_subject_bNShh19_wf.func_preproc_task_tree_run_03_wf.bold_std_trans_wf.select_tpl).
210806-06:48:21,482 nipype.workflow INFO:
	 [Job 4] Cached (fmriprep_wf.single_subject_bNShh19_wf.func_preproc_task_tree_run_03_wf.bold_std_trans_wf.split_target).
```

And I get very strange errors like:

```
210806-06:48:27,515 nipype.workflow VERBOSE:
	           Some dictionary entries had differing values:
            * fixed_image_mask: ('/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask.nii.gz', '48bbd4b7c6f5447382d5fa3dd365e4a9') != ['/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-brain_mask.nii.gz', 'b7c25f9c79a321b2fd6f423ffca96d89']
            * fixed_image: ('/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz', '2ea4ef50237a11ec82d1164fb77392f3') != ['/templateflow/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_desc-fMRIPrep_boldref.nii.gz', '5117fa3c527de14ea32afb10d4b0850e']
            * search_grid: ('40.0000000000', ('0.0000000000', '40.0000000000', '40.0000000000')) != ['40.0000000000', ['0.0000000000', '40.0000000000', '40.0000000000']]
```

I would be grateful for any suggestions. I hope it's something simple and can be fixed with some change in my code.

**Comment by effigies** [comment]
Are you reusing your working directory from 20.1.1? That would be a likely cause for an error like this.

**Comment by tanya-wen** [comment]
Thanks so much for your quick response! I didn't realized I was reusing the work directory from 20.1.1. After deleting everything from the work directory and re-running again, it's working fine now.
