### ISSUE TITLE
fmriprep version 20.2.3  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by LJWilliams** [nipreps/fmriprep#2506]
When running version 20.2.3 I get the above error (see below for trace).  I am not sure where fmriprep is trying to find the database to allow permissions to write. Any help would be greatly appreciated.

which sqlite3
/Users/[username]/opt/anaconda3/bin/sqlite3

docker run --rm -e DOCKER_VERSION_8395080871=20.10.7 -it -v /Applications/freesurfer/7.1.1/license.txt:/opt/freesurfer/license.txt:ro -v /Users/lwilliams/Documents/Studies/Bruce/BHBMEG/BHBMEG007A:/data:ro -v /Users/lwilliams/Documents/Studies/Bruce/BHBMEG/BHBMEG007A/derivatives:/out -v /Users/lwilliams/Documents/Studies/Bruce/BHBMEG/BHBMEG007A/derivatives/freesurfer:/opt/subjects -v /Users/lwilliams/Documents/Studies/Bruce/BHBMEG/tmp:/scratch nipreps/fmriprep:20.2.3 /data /out participant --skip_bids_validation --nprocs=4 --force-no-bbr --dummy-scans=0 --use-aroma --clean-workdir --resource-monitor --fs-subjects-dir /opt/subjects -w /scratch
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 735, in parse_args
    all_subjects = config.execution.layout.get_subjects()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 174, in __getattr__
    entities = self.get_entities()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 373, in get_entities
    results = query.all()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

**Comment by LJWilliams** [comment]
Discovered that the path /usr/local/miniconda does not exist on my machine.

**Comment by bwinsto2** [comment]
Hi Lynne, would you mind elaborating? Did Chris's solution work for you? Or did you change the permissions on for your data, perhaps? I'm experiencing the same issue on an HPC, so I can't change permissions without going through the sysadmin. Thanks.

**Comment by bwinsto2** [comment]
@LJWilliams do you remember which permissions were the issue? Did you follow @effigies 's advice? Personally I'm not sure how to change the permissions of the container software since I'm using singularity as opposed to Docker.

**Comment by LJWilliams** [comment]
It was the permissions of my work and derivatives folders that were the
problem.

**Comment by bwinsto2** [comment]
Thanks. I was able to address this by deleting my old work directory and setting a new work directory for each participant I run.

**Comment by effigies** [comment]
Sounds like this is resolved for now. If this problem resurfaces, we can open a new issue.
