### ISSUE TITLE
Singularity 2.4 with linux 2.6 can’t assign to a working directory outside of /tmp

### ISSUE THREAD

**Issue by yusaiwen** [nipreps/fmriprep#2511]
### What version of fMRIPrep are you using?

20.2.3

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?

singularity 2.4.6-dit  
I ran it on a HPC cluster

### What is the exact command-line you used?

```bash
#!/bin/bash
#test batch

#PBS -N 30-99
#PBS -l nodes=1:ppn=15,mem=10gb
#PBS -q long 
#PBS -V

unset PYTHONPATH

PROJECT_DIR=/brain/lilyliulab/seven/life/Nifti
OUTPUT_DIR=$PROJECT_DIR/derivatives/seven1
CODE_DIR=$PROJECT_DIR/code

nthreads=15
mem=10
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing

TEMPLATE_FLOW_DIR=$CODE_DIR/templateflow

export TEMPLATEFLOW_HOME=$TEMPLATE_FLOW_DIR # offline template dir

subject=1 # for the test of a single subject

singularity run \
  $CODE_DIR/img/fmriprep-20.2.3.simg \
  $PROJECT_DIR $OUTPUT_DIR participant \
  --skip-bids-validation \
  --participant-label $subject \
  --fs-no-reconall \
  --fs-license-file $CODE_DIR/license.txt \
  --nthreads $nthreads\
  --mem_mb $mem_mb \
  --use-syn-sdc \
  --output-spaces MNI152NLin2009cAsym:res-2 \
  --stop-on-first-crash \
  --notrack \
  -w /brain/lilyliulab/seven/tmp \
  -vv 

```

The problem is that if the -w option which sets the working directory is set outside of /tmp, error will occur. But the /tmp has the capacity of only 10gb and I don’t have an access to it. The lower Linux kernel version :

[lilyliulab@cu72 ~]$ uname -a
Linux cu72 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

limits the singularity version and binding function(-B option is omitted if I set it). Also my HPC is cut off from Internet(maybe for the safety concern). So I was wondering if there is a magic singularity environmental variable which be assigned to the working directory, like TEMPLATEFLOW_HOME ?

### Have you checked that your inputs are BIDS valid?
Yes
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
no

### Can you find some traces of the error reported in the visual report (at the bottom) or in crashfiles?
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 611, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 634, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 459, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 152, in __init__
    database_path, reset_database, config, init_args)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 48, in __init__
    self.reset_database(init_args, config)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/db.py", line 106, in reset_database
    Base.metadata.drop_all(self.engine)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4691, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 889, in visit_metadata
    unsorted_tables = [t for t in tables if self._can_drop_table(t)]
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 889, in <listcomp>
    unsorted_tables = [t for t in tables if self._can_drop_table(t)]
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 982, in _can_drop_table
    self.connection, table.name, schema=effective_schema
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1669, in has_table
    connection, "table_info", table_name, schema=schema
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2183, in _get_table_pragma
    cursor = connection.execute(statement)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) disk I/O error
[SQL: PRAGMA main.table_info("layout_info")]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

For some days’ search, I failed to find some solutions, I will be sorry if the similar problem has been raised and solved before.

**Comment by effigies** [comment]
Are you unable to use `-B /brain:/brain` to bind `/brain` into the container?
