### ISSUE TITLE
No space left on device error with singularity when using --cifti-output 170k command

### ISSUE THREAD

**Issue by mszinte** [nipreps/fmriprep#2521]
### What version of fMRIPrep are you using?
I use 20.2.3 but i also faced the same error with 20.1.1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
I use singularity on a university server (mesocentre amu: https://mesocentre.univ-amu.fr/)

### What is the exact command-line you used?
```singularity run --cleanenv -B /scratch/mszinte/data:/work_dir -B /scratch/mszinte/ /scratch/mszinte/softwares/fmriprep-20.2.3.simg --fs-license-file /work_dir/freesurfer/license.txt /work_dir/PredictEye/bids_data/ /work_dir/PredictEye/deriv_data/fmriprep_new/ participant --participant-label 01 -w /scratch/mszinte/ --bold2t1w-dof 12 --ignore sbref --output-spaces T1w --cifti-output 170k --low-mem --mem-mb 64000 --nthreads 32```

### Have you checked that your inputs are BIDS valid?
YES

### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
no the error comes at the very beginning 

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
Downloading https://templateflow.s3.amazonaws.com/tpl-fsLR/tpl-fsLR_space-fsaverage_hemi-L_den-59k_sphere.surf.gii
  0%|          | 0.00/1.40M [00:00<?, ?B/s]
  2%|▏         | 25.6k/1.40M [00:00<00:09, 148kB/s]
 14%|█▍        | 200k/1.40M [00:00<00:01, 638kB/s] 
 55%|█████▌    | 774k/1.40M [00:00<00:00, 1.82MB/s]
 75%|███████▌  | 1.05M/1.40M [00:00<00:00, 1.95MB/s]
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 233, in _s3_get
    f.write(data)
OSError: [Errno 28] [log.txt](https://github.com/nipreps/fmriprep/files/7065698/log.txt)
[log.txt](https://github.com/nipreps/fmriprep/files/7065701/log.txt)
[log.txt](https://github.com/nipreps/fmriprep/files/7065703/log.txt)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 803, in init_func_preproc_wf
    repetition_time=metadata['RepetitionTime'])
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/resampling.py", line 634, in init_bold_grayords_wf
    for hemi in 'LR'
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/resampling.py", line 634, in <listcomp>
    for hemi in 'LR'
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 78, in get
    _s3_get(filepath)
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 234, in _s3_get
    t.update(len(data))
OSError: [Errno 28] [log.txt](https://github.com/nipreps/fmriprep/files/7065698/log.txt)

```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
Yes anatomy segmentation previously ran with fmriprep and put in the right folders.

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

The bug is generated as long as i put the --cifti-output 170k command, otherwise there is no error. 
I checked first over the web and found problems relative to the temp data folder specified using -w command. I tried without specifying (same error), with specifying the server temp folder (/tmp/mszinte/ same error) by binding another folder (see command above -> same error). I also tried on another server with the same data and replicated the error again.

I would need to ouput my data in this format so at the moment i'm getting stuck, did anyone face the same problem ?

Thank you very much for your help and for the tremendous work done with fmriprep !

**Comment by mszinte** [comment]
Thanks @effigies 

I used one of the method proposed on [your link](https://fmriprep.org/en/20.2.2/singularity.html#templateflow-and-singularity) and it worked !

I thus created a folder where the template will be downloaded and used the follwing lines of code to bind it after specifying where these template are located.
`export SINGULARITYENV_TEMPLATEFLOW_HOME=/opt/templateflow` 
in the singularity command : `-B /scratch/mszinte/softwares/fmriprep_tf/:/opt/templateflow`

Here is the full command:
```
export SINGULARITYENV_TEMPLATEFLOW_HOME=/opt/templateflow

singularity run --cleanenv -B /scratch/mszinte/softwares/fmriprep_tf/:/opt/templateflow
-B /scratch/mszinte/data:/work_dir /scratch/mszinte/softwares/fmriprep-20.2.3.simg 
--fs-license-file /work_dir/freesurfer/license.txt /work_dir/PredictEye/bids_data/ 
/work_dir/PredictEye/deriv_data/fmriprep_new/ participant --participant-label 01 
-w /work_dir/PredictEye/temp_data/ 
--bold2t1w-dof 12 --ignore sbref --output-spaces T1w fsnative fsaverage MNI152NLin2009cAsym:res-1 
--cifti-output 170k --low-mem --mem-mb 64000 --nthreads 32
```

Thanks again.
