### ISSUE TITLE
sqlite3.OperationalError: database or disk is full

### ISSUE THREAD

**Issue by m-petersen** [nipreps/fmriprep#2525]
What are you trying to accomplish?
I want to preprocess rsfMRI data on a HPC using a singularity container with fmriprep (20.2.3) on our local HPC. When running fmriprep on a single subject from a 3000 subject bids dataset the following error occurs which leads to the command terminating prematurely. 

```
++ CMD='
   singularity run --cleanenv --userns -B /work/fatx405/projects/CSI_HCHS -B /scratch/fatx405.1466836/sub-003cb60d/tmp//:/tmp    /work/fatx405/projects/CSI_HCHS/envs/fmriprep-20.2.3    data/raw_bids data participant    -w /tmp    --participant-label sub-003cb60d    --output-spaces fsnative fsaverage MNI152NLin6Asym    --nthreads 8    --omp-nthreads 7    --mem-mb 16000
   --stop-on-first-crash    --ignore t2w    --skip-bids-validation    --fs-subjects-dir data/freesurfer    --use-aroma    --random-seed 12345    --use-syn-sdc    --fs-license-file envs/freesurfer_license.txt'
++ singularity run --cleanenv --userns -B /work/fatx405/projects/CSI_HCHS -B /scratch/fatx405.1466836/sub-003cb60d/tmp//:/tmp /work/fatx405/projects/CSI_HCHS/envs/fmriprep-20.2.3 data/raw_bids data participant -w /tmp --participant-label sub-003cb60d --output-spaces fsnative fsaverage MNI152NLin6Asym --nthreads 8 --omp-nthreads 7 --mem-mb 16000 --stop-on-first-crash --ignore t2w --skip-bids-validation --fs-subjects-dir data/freesurfer --use-aroma --random-seed 12345 --use-syn-sdc --fs-license-file envs/freesurfer_license.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database or disk is full

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 611, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 634, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 459, in init
    re.compile(r"^\."),
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 156, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 112, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 247, in _index_metadata
    all_files = self._layout.get(absolute_paths=True, **filters)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 658, in get
    results.extend(query.all())
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL: SELECT files.path AS files_path, files.filename AS files_filename, files.dirname AS files_dirname, files.is_dir AS files_is_dir, files.class_ AS files_class_ 
FROM files 
WHERE files.is_dir = 0 GROUP BY files.path]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/miniconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database or disk is full
```

Grateful for any input. Happy to provide further details.

Cheers,
Marvin

**Comment by effigies** [comment]
It looks like you're maxing out your disk quota on `/scratch/fatx405.1466836/sub-003cb60d/tmp`, since you have that mapped to `/tmp`, and are using `-w /tmp`.

For a 3000 subject dataset, I would recommend [pre-computing a BIDS database](https://fmriprep.org/en/stable/faq.html?highlight=database#how-to-decrease-fmriprep-runtime-when-working-with-large-datasets). Note that you'll need a version of pybids between 0.12.1 and <0.14. To use the same version as is in your fMRIPrep image:

```Shell
 singularity exec [OPTIONS] [IMAGE] pybids layout [BIDSDIR] [DATABASE] --no-validate
```

You'll use the same database for all subjects, so you might use something like `/work/fatx405/projects/CSI_HCHS/bidsdb` instead of a subject-specific location.

**Comment by m-petersen** [comment]
Dear Chris,

thanks for your reply and the recommendation with the pybids version. This morning I've had an issue with a precomputed bids database. Maybe it was due to version inconsistencies.

After the issue occurred I have 90gb available on /scratch where /tmp is located so not sure whether that is the culprit. I'll check  what happens if I mount /tmp on another partition.
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        92G  847M   91G   1% /scratch
```

**Comment by effigies** [comment]
> This morning I've had an issue with a precomputed bids database. Maybe it was due to version inconsistencies.

The database schema has changed recently. It's possible that it was in 0.13.1 or 0.13.2, so it would definitely be safest to use the version bundled with fmriprep.

**Comment by m-petersen** [comment]
Although /scratch seems to have 90gb of unoccupied storage space setting -w to another partition solves the issue.
