### ISSUE TITLE
Error with version 21.0.0rc0

### ISSUE THREAD

**Issue by zugmana** [nipreps/fmriprep#2527]
Hi all,

### What version of fMRIPrep are you using?
21.0.0rc0
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
I've tried both singularity and bare-metal. Got the same error message.
### What is the exact command-line you used?''''
'''
fmriprep BIDS/ temp/ participant --participant-label s22686
'''
### Have you checked that your inputs are BIDS valid?
Yes, and it was working on previous fmriprep versions

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No.

### fMRIPrep log

Process Process-2:
Traceback (most recent call last):
  File "/code/conda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/code/conda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/code/conda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/code/conda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/code/conda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 328, in init_single_subject_wf
    force_fmapless=False,  # config.workflow.force_syn,
  File "/code/conda/lib/python3.7/site-packages/sdcflows/utils/wrangler.py", line 265, in find_estimators
    fm.FieldmapFile(fmap.path, metadata=fmap.get_metadata())
AttributeError: 'NoneType' object has no attribute 'path'

Hi all,
I'm getting the above error when trying to run the new candidate version. As I mentioned this dataset was working fine for other fmriprep versions. The reason I want to test the new version is because many of our subjects had bad results with the SDC.
Any ideas what might be causing this or how to fix it?

Many thanks,

**Comment by effigies** [comment]
Could you share the metadata for your fieldmap and BOLD files?

**Comment by zugmana** [comment]
I've included the json on this zip file.
Thanks!
[test_subject.zip](https://github.com/nipreps/fmriprep/files/7111502/test_subject.zip)

**Comment by effigies** [comment]
Okay, this looks like an issue with resolving `IntendedFor` links in multi-session datasets. Specifically, [this line](https://github.com/nipreps/sdcflows/blob/master/sdcflows/utils/wrangler.py#L255) is finding `<BIDS>/sub-s22686/ses-1` instead of `<BIDS>/sub-s22686`.

Thanks for the report! We should be able to fix this one pretty quickly.
