### ISSUE TITLE
Integrating CIFTI templates into FMRIPREP installation (without online download)

### ISSUE THREAD

**Issue by BlackHoleExelion** [nipreps/fmriprep#2528]
Hi there,
I am using FMRIPREP under a HPC environment with no Internet connection, and processing failed during CIFTI generating stage because of the restriction of connection, as attached below. I am just wondering if it is possible to integrate CIFTI templates (and other possibly required templates) into FMRIPREP installation (and container) so it can be run without Internet completely. Thank you!

================================================================
```bash
Node: fmriprep_wf.single_subject_C207_wf.func_preproc_ses_Baseline_task_nback02_run_01_wf.bold_grayords_wf.gen_cifti
Working directory: /project/oathes_group/fmriprep/temp_fmriprep/fmriprep_wf/single_subject_C207_wf/func_preproc_ses_Baseline_task_nback02_run_01_wf/bold_grayords_wf/gen_cifti

Node inputs:

TR = 1.0
bold_file = <undefined>
subjects_dir = <undefined>
surface_bolds = <undefined>
surface_density = 32k
surface_target = fsLR
volume_target = MNI152NLin6Asym

Traceback (most recent call last):
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2b7b826e71f0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/python-3.9/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/appl/python-3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='templateflow.s3.amazonaws.com', port=443): Max retries exceeded with url: /tpl-fsLR/tpl-fsLR_hemi-L_den-32k_desc-nomedialwall_dparc.label.gii (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7b826e71f0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appl/python-3.9/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/appl/python-3.9/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/appl/python-3.9/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/appl/python-3.9/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/appl/python-3.9/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/appl/python-3.9/lib/python3.9/site-packages/niworkflows/interfaces/cifti.py", line 104, in _run_interface
    annotation_files, label_file = _get_cifti_data(
  File "/appl/python-3.9/lib/python3.9/site-packages/niworkflows/interfaces/cifti.py", line 229, in _get_cifti_data
    for f in tf.get(
  File "/appl/python-3.9/lib/python3.9/site-packages/templateflow/api.py", line 78, in get
    _s3_get(filepath)
  File "/appl/python-3.9/lib/python3.9/site-packages/templateflow/api.py", line 220, in _s3_get
    r = requests.get(url, stream=True)
  File "/appl/python-3.9/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/appl/python-3.9/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='templateflow.s3.amazonaws.com', port=443): Max retries exceeded with url: /tpl-fsLR/tpl-fsLR_hemi-L_den-32k_desc-nomedialwall_dparc.label.gii (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7b826e71f0>: Failed to establish a new connection: [Errno 110] Connection timed out'))


```

**Comment by mgxd** [comment]
The tricky thing about this is depending on what command line options are used, different files might be required. I do think it's reasonable to ensure all the CIFTI files (at least for 91k grayordinates) are present.

However, see https://github.com/nipreps/fmriprep/issues/2521#issuecomment-907587408 for a workaround.

**Comment by BlackHoleExelion** [comment]
Thank you so much for the help!
