### ISSUE TITLE
wb_command / libQt5Core failure in Singularity

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2534]
Thanks @effigies.

following is the command I used to process the data.

singularity run --cleanenv --bind /mnt/fMRIprep /mnt/tools/fMRIprep_sing/fmriprep-21.0.0rc0.simg /mnt/fMRIprep/scR21 /mnt/fMRIprep/scR21_outputs_21_Sep_2021 -w /mnt/fMRIprep/scR21_outputs_21_Sep_2021/derivatives/scratch --fs-license-file $PWD/license.txt --write-graph --cifti-output 91k participant --participant-label sub-50015 --ignore slicetiming --output-spaces T1w MNI152NLin2009cAsym:res-2 fsaverage fsLR

But I am getting following error,
 Standard error: ( please see my previous comment for more information)
wb_command: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
Return code: 127

I am not sure how to fix it. Please let me know if I am using the correct command.

_Originally posted by @sameera2004 in https://github.com/nipreps/fmriprep/issues/2210#issuecomment-918336847_

**Comment by effigies** [comment]
Going by https://stackoverflow.com/questions/58912268/singularity-container-python-pytorch-why-does-import-torch-work-on-arch-l, it looks like we might need to modify the image.

```
strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

@sameera2004 If you're comfortable creating a singularity recipe, you could add that line to the end. Otherwise the easiest solution would probably be for us to create a patch branch that you can test. Let me know.

**Comment by sameera2004** [comment]
Thanks @effigies I haven't created a singularity recipe before. It would be great if you can create a patch branch for us.

**Comment by effigies** [comment]
@sameera2004 Try building from `nipreps/fmriprep:libqt`.

**Comment by effigies** [comment]
Hi @sameera2004, just a bump to confirm whether the proposed patch fixes things for you.

**Comment by mgxd** [comment]
I think it would look like

```
singularity build fmriprep-21.0.0-libqt.simg docker://nipreps/fmriprep:libqt
```

**Comment by sameera2004** [comment]
Thanks @mgxd I was able to build it, I will test run it now

**Comment by sameera2004** [comment]
@effigies and @mgxd Thanks. Now I was able to process one subject fMRI data without any errors and I still didn't get a time to check those results. I also processed two other subjects and got the following two different errors from them.


Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/niworkflows/interfaces/nibabel.py", line 191, in _run_interface
    img_4d = nb.concat_images(nii_list)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabel/funcs.py", line 141, in concat_images
    raise ValueError(f'Affine for image {i} does not match affine for first image')
ValueError: Affine for image 3 does not match affine for first image



Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/niworkflows/interfaces/nilearn.py", line 176, in _run_interface
    new_nii = concat_imgs(self.inputs.in_files, dtype=self.inputs.dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 471, in concat_niimgs
    niimg = check_niimg(niimg, ensure_ndim=ndim)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 283, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg.py", line 134, in load_niimg
    dtype = _get_target_dtype(_get_data(niimg).dtype, dtype)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nilearn/_utils/niimg.py", line 24, in _get_data
    data = np.asanyarray(img._dataobj)
  File "/usr/local/miniconda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 171, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 391, in __array__
    arr = self._get_scaled(dtype=dtype, slicer=())
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 358, in _get_scaled
    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabel/arrayproxy.py", line 332, in _get_unscaled
    return array_from_file(self._shape,
  File "/usr/local/miniconda/lib/python3.8/site-packages/nibabel/volumeutils.py", line 519, in array_from_file
    infile.seek(offset)
  File "indexed_gzip/indexed_gzip.pyx", line 651, in indexed_gzip.indexed_gzip._IndexedGzipFile.seek
indexed_gzip.indexed_gzip.CrcError: CRC/size validation failed - the GZIP data might be corrupt (file: /gpfs/projects/fmriprep/scR21_outputs_Sep_2021_N/derivatives/scratch/fmriprep_wf/single_subject_50144_wf/func_preproc_ses_1_task_RSFC_run_4_wf/bold_t1_trans_wf/bold_to_t1w_transform/vol0412_xform-00412.nii.gz)

**Comment by effigies** [comment]
Let's open that as a new issue.
