### ISSUE TITLE
Problem running fmriprep 20.2.3

### ISSUE THREAD

**Issue by shilpitju** [nipreps/fmriprep#2554]
Hi,

I have been using fmriprep for quite sometime now. However, with the installation of fmriprep version 20.2.3 and trying to run it on docker version 20.10.7 is giving the following errors:

WatsonBucketsNamParamName  System.Collections.IDictionarySystem.Excepti   System.ArgumentException    The path is not of a legal form.

   �   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at Docker.ApiServices.Mounting.FileSharing.IsPathIncluded(String path, String directory) in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 59
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__7.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__5.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
       �8
NewNormalizePath
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.IO.Path
System.String NewNormalizePath(System.String, Int32, Boolean)W �  mscorlib.
See 'docker run --help'.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

Kindly help to rectify the issue.

**Comment by effigies** [comment]
This appears to be a Docker issue, though it may be an issue with the Docker command. Could you share your command?

**Comment by shilpitju** [comment]
PS E:\S0807> fmriprep-docker .\Nifti .\Derivatives1 participant --participant-label sub-S0807 --fs-license-file .\license.txt --use-syn-sdc --output-spaces MNI152NLin6Asym --cifti-output  --stop-on-first-crash

**Comment by shilpitju** [comment]
My E:\ is in file sharing of docker.

**Comment by effigies** [comment]
This should have printed a line with `docker run` in it. What did that look like?

**Comment by shilpitju** [comment]
docker run --rm -e DOCKER_VERSION_8395080871=20.10.7 -it -v E:\S0807\license.txt:/opt/freesurfer/license.txt:ro -v E:\S0807\Nifti:/data:ro -v E:\S0807\Derivatives1:/out nipreps/fmriprep:20.2.3 /data /out participant --participant-label sub-S0807 --use-syn-sdc --cifti-output --stop-on-first-crash --output-spaces MNI152NLin6Asym

**Comment by effigies** [comment]
That looks reasonable, as far as I can see. I would check with Docker support.

**Comment by shilpitju** [comment]
Alright, so you suggest sharing the error with them. Will do so.

Thanks,
