### ISSUE TITLE
ValueError: Trying to re-register the builtin cmap 'bwr'.

### ISSUE THREAD

**Issue by GerardYu** [nipreps/fmriprep#2564]
hi there,
i was trying to preprocess single subject with the following command

fmriprep dataset output participant --participant-label 002 --skip-bids-validation

and i got these errors

210930-21:40:48,698 cli WARNING:
         Telemetry disabled because sentry_sdk is not installed.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/intel/oneapi/2021.3/intelpython/latest/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/intel/oneapi/2021.3/intelpython/latest/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 20, in build_workflow
    from ..workflows.base import init_fmriprep_wf
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 20, in <module>
    from ..interfaces import SubjectSummary, AboutSummary, DerivativesDataSink
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/interfaces/__init__.py", line 5, in <module>
    from niworkflows.interfaces import (
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/niworkflows/interfaces/__init__.py", line 4, in <module>
    from .masks import BETRPT as BET
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/niworkflows/interfaces/masks.py", line 23, in <module>
    from . import report_base as nrc
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/niworkflows/interfaces/report_base.py", line 10, in <module>
    from ..viz.utils import cuts_from_bbox, compose_view
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/niworkflows/viz/__init__.py", line 3, in <module>
    from .plots import plot_carpet
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/niworkflows/viz/plots.py", line 15, in <module>
    from nilearn.plotting import plot_img
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/nilearn/plotting/__init__.py", line 42, in <module>
    from . import cm
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/nilearn/plotting/cm.py", line 214, in <module>
    _cm.register_cmap(name=k, cmap=v)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/matplotlib/cm.py", line 149, in register_cmap
    raise ValueError(msg)
ValueError: Trying to re-register the builtin cmap 'bwr'.

**Comment by effigies** [comment]
This was a bug in nilearn, fixed in https://github.com/nilearn/nilearn/pull/2582. If you upgrade to nilearn >= 0.7, that should fix it.

**Comment by GerardYu** [comment]
yeap, indeed its fixed after upgrading nilearn
