### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

### ISSUE THREAD

**Issue by Sharon0615** [nipreps/fmriprep#2636]
### What happened?
```
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 640, in parse_args
    config.from_dict(vars(opts))
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 648, in from_dict
    execution.load(settings)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 218, in load
    cls.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 469, in init
    indexer=_indexer,
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/layout.py", line 156, in __init__
    indexer(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 112, in __call__
    self._index_metadata()
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 380, in _index_metadata
    file_md.update(pl())
  File "/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/index.py", line 275, in load_json
    return json.load(handle)
  File "/usr/local/miniconda/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/miniconda/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
```

### What command did you use?

```shell
The problem came up when I was running the following code:
root@msi-MS-7C86:/media/msi/ExtremeSSD/PKU6th_resting/Demo/ReorgData# fmriprep-docker /media/msi/ExtremeSSD/PKU6th_resting/Demo/ReorgData /media/msi/ExtremeSSD/PKU6th_resting/Demo/ReorgData/derivatives/ participant --participant-label 11100 --fs-license-file /media/msi/ExtremeSSD/license.txt --fs-no-reconall
```
I have no idea about where the bug is and how to fix it.

### What version of fMRIPrep are you running?

v20.2.6

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by Sharon0615** [comment]
And I have validated my .json files in this website(https://codebeautify.org/jsonvalidator?/jsonvalidate), they seemed to be fine.

**Comment by oesteban** [comment]
@effigies this weird issue seems to be related to a problem when loading PyBIDS' config file, WDYT?

**Comment by effigies** [comment]
I don't think it is, because it's during `_index_metadata()`. It looks like a bad JSON file, but unfortunately the exception doesn't list the filename... @Sharon0615 can you index your dataset with PyBIDS? You should be able to do something like `pybids layout --index-metadata /path/to/dataset /tmp/db`. That will at least verify that it's a PyBIDS/dataset issue, not an fMRIPrep issue.

We can then work on debugging further over at PyBIDS.

**Comment by Sharon0615** [comment]
The problem might result from the wrong encoding format of participants.tsv. When I changed it from ASCII to utf-8 format, it can be solved. Thanks for your kind help .

**Comment by effigies** [comment]
Glad you were able to resolve it.
