### ISSUE TITLE
fmriprep pause during anatomical recontruction step

### ISSUE THREAD

**Issue by ltetrel** [nipreps/fmriprep#2637]
### What happened?

We are running fmriprep on a SLURM compute cluster, the process is paused and does not exit.
Hence our slurm job exit when it timeout (and we don't have access to the working directory, which is saved on the compute node).

### What command did you use?

```shell
singularity run --cleanenv -B $SLURM_TMPDIR:/DATA -B /home/ltetrel/.cache/templateflow:/templateflow -B /etc/pki:/etc/pki/ -B /scratch/ltetrel/cima-q/1636990190:/OUTPUT /lustre03/project/6003287/containers/fmriprep-20.2.1lts.sif -w /DATA/fmriprep_work --participant-label 9929164   --bids-filter-file /OUTPUT/bids_filters.json   --output-spaces MNI152NLin2009cAsym MNI152NLin6Asym anat fsnative --output-layout bids --notrack --skip_bids_validation --write-graph --omp-nthreads 8 --nprocs 16 --mem_mb 65536 --resource-monitor /DATA/cima-q /DATA/cima-q/derivatives/fmriprep participant
```

### What version of fMRIPrep are you running?

20.2.1lts

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Last command (process is paused at this stage):

211123-20:40:39,959 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_9929164_wf.anat_preproc_wf.anat_norm_wf.trunc_mov".

Error log:

/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
exception calling callback for <Future at 0x2ae3ce4e3390 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 486, in run
    self._get_hashval()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 609, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 302, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_types.py", line 2336, in validate
    return TraitListObject( self, object, name, value )
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in __init__
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 2305, in <listcomp>
    value = [ validate( object, name, val ) for val in value ]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: Each element of the 't2w_list' trait of a _FSDetectInputsInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/DATA/cima-q/sub-9929164/ses-V03/anat/sub-9929164_ses-V03_T2w.nii.gz' <class 'str'> was specified.
Error setting node input:
Node: recon_config
input: t2w_list
results_file: /DATA/fmriprep_work/fmriprep_wf/single_subject_9929164_wf/bidssrc/result_bidssrc.pklz
value: /DATA/cima-q/sub-9929164/ses-V03/anat/sub-9929164_ses-V03_T2w.nii.gz
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 217, in result
    op.join(self.output_dir(), "result_%s.pklz" % self.name)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /DATA/fmriprep_work/fmriprep_wf/single_subject_9929164_wf/anat_preproc_wf/surface_recon_wf/recon_config/result_recon_config.pklz
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: /DATA/fmriprep_work/fmriprep_wf/single_subject_9929164_wf/anat_preproc_wf/surface_recon_wf/recon_config/result_recon_config.pklz
```

### Additional information / screenshots

We have a datalad dataset where we `datalad get` just the T1 and func. There are also t2w and flair but we ignore them (empty symlinks).
Since we thought this was an issue where fmriprep see the files (think it exists), we added a bids_filter to ignore these (empty) files. But that did not change the error that we see.

```
{
  "fmap": {"datatype": "fmap"},
  "bold": {"datatype": "func", "suffix": "bold"},
  "t1w": {"datatype": "anat", "suffix": "T1w"},
  "roi": {"datatype": "anat", "suffix": "roi"}
}
```

**Comment by mgxd** [comment]
It looks like the cache may have gotten messed up. Can you try clearing it and then re-running? Also, you can use `--ignore t2w flair` in place of `--bids-filter-file` in this case.

BTW- The `20.1.x` series is not LTS - that is `20.2.x`

**Comment by ltetrel** [comment]
> It looks like the cache may have gotten messed up. Can you try clearing it and then re-running? Also, you can use --ignore t2w flair in place of --bids-filter-file in this case.

Regarding the cache, we are using a compute node , so the clache should be cleared each time. I was not aware of the option `--ignore t2w flair`thanks I will try. 

> BTW- The 20.1.x series is not LTS - that is 20.2.x

uups my bad it is `20.2.1lts`, just modified it on the issue.

**Comment by mgxd** [comment]
Ah, I see the problem - these are the default queries fMRIPrep uses:

```
{
  "fmap": {"datatype": "fmap"},
  "bold": {"datatype": "func", "suffix": "bold"},
  "sbref": {"datatype": "func", "suffix": "sbref"},
  "flair": {"datatype": "anat", "suffix": "FLAIR"},
  "t2w": {"datatype": "anat", "suffix": "T2w"},
  "t1w": {"datatype": "anat", "suffix": "T1w"},
  "roi": {"datatype": "anat", "suffix": "roi"},
}
```

If adding special filtering with `--bids-filter-file`, the entries you provide will overwrite the defaults, but any scantype omitted will be set to the default listed above. The `--ignore` method should work, but if you wished to use `--bids-filter-file`, I think you would need to supplement your file with:

```
{
  "fmap": {"datatype": "fmap"},
  "bold": {"datatype": "func", "suffix": "bold"},
  "t1w": {"datatype": "anat", "suffix": "T1w"},
  "roi": {"datatype": "anat", "suffix": "roi"},
  "t2w": null,
  "flair": null
}
```

**Comment by ltetrel** [comment]
Ok! I was confused by the bids_filter definition, there is no instruction on the BIDS documentation for that file, just yours.

I will try with this new bids_filter, and let you know. It may take a while (time to have job queued and processed etc..).

**Comment by ltetrel** [comment]
So I tried with the bids_filters.json that you proposed, unfortunately I got the following error:
```
/usr/local/miniconda/lib/python3.7/site-packages/bids/layout/validation.py:46: UserWarning: The ability to pass arguments to BIDSLayout that control indexing is likely to be removed in future; possibly as early as PyBIDS 0.14. This includes the `config_filename`, `ignore`, `force_index`, and `index_metadata` arguments. The recommended usage pattern is to initialize a new BIDSLayoutIndexer with these arguments, and pass it to the BIDSLayout via the `indexer` argument.
  warnings.warn("The ability to pass arguments to BIDSLayout that control "
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 17, in main
    parse_args()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/parser.py", line 713, in parse_args
    config.execution.init()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 467, in init
    for k, v in filters.items()
AttributeError: 'Query' object has no attribute 'items'
```

Anyway we finally decided to process the dateset with also FLAIR and T2* and the preprocessing went well this time.
