### ISSUE TITLE
File name too long in slice time correction step on multi-echo rest runs

### ISSUE THREAD

**Issue by Shotgunosine** [nipreps/fmriprep#2650]
### What happened?

I tried running 9 subjects worth of data through fmriprep 21.0.0rc2 using a singluarity container built off of the docker image and all of them hung for 48 hours hitting the jobs wall time and dying. It looks like all of the jobs died in the slice timing correction step with `OSError: [Errno 36] File name too long:`. I think the processes hung because in addition to not being able to write the slice timing output, they were unable to write the error files for the same reason (File name too long).

### What command did you use?

```shell
singularity run --cleanenv /data/MBDU/singularity_images/fmriprep_v21.0.0rc2.simg /data/MBDU/mid_share/data/bids_defaced     $TMPDIR/out participant     --participant_label 20900     -w $TMPDIR/wrk     --nprocs $SLURM_CPUS_PER_TASK     --mem_mb $SLURM_MEM_PER_NODE     --fs-license-file /data/MBDU/singularity_images/license.txt     --output-spaces MNI152NLin2009cAsym:res-2 fsaverage     --dummy-scans 4 --bids-filter-file /data/MBDU/mid_share/data/derivatives/fmriprep/fmriprepv21.0.0rc2_test/bids_filter --use-aroma --error-on-aroma-warnings -vvv
```
```


### What version of fMRIPrep are you running?

fmriprep 21.0.0rc2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

shell
exception calling callback for <Future at 0x2aaab4b718b0 state=finished raised OSError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 507, in run
    os.makedirs(outdir, exist_ok=True)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/lscratch/27850734/wrk/fmriprep_wf/single_subject_20900_wf/func_preproc_ses_v1_task_rest_run_1_echo_1_wf/bold_stc_wf/_bold_file_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz_name_source_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 216, in result
    return _load_resultfile(
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 290, in load_resultfile
    if not results_file.exists():
  File "/opt/conda/lib/python3.8/pathlib.py", line 1388, in exists
    self.stat()
  File "/opt/conda/lib/python3.8/pathlib.py", line 1194, in stat
    return self._accessor.stat(self)
OSError: [Errno 36] File name too long: '/lscratch/27850734/wrk/fmriprep_wf/single_subject_20900_wf/func_preproc_ses_v1_task_rest_run_1_echo_1_wf/bold_stc_wf/_bold_file_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz_name_source_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz/slice_timing_correction/result_slice_timing_correction.pklz'
"""
```

**Comment by Shotgunosine** [comment]
Here are the logs for one participant:
[fmriprepv21.0.0rc2_test_27850720_0_error.log](https://github.com/nipreps/fmriprep/files/7661517/fmriprepv21.0.0rc2_test_27850720_0_error.log)
[fmriprepv21.0.0rc2_test_27850720_0_output.log](https://github.com/nipreps/fmriprep/files/7661518/fmriprepv21.0.0rc2_test_27850720_0_output.log)

**Comment by effigies** [comment]
Ouch:

```Python
>>> [(len(part), part) for part in Path('/lscratch/27850734/wrk/fmriprep_wf/single_subject_20900_wf/func_preproc_ses_v1_task_rest_run_1_echo_1_wf/bold_stc_wf/_bold_file_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz_name_source_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz/slice_timing_correction/result_slice_timing_correction.pklz').parts]
[(1, '/'),
 (8, 'lscratch'),
 (8, '27850734'),
 (3, 'wrk'),
 (11, 'fmriprep_wf'),
 (23, 'single_subject_20900_wf'),
 (45, 'func_preproc_ses_v1_task_rest_run_1_echo_1_wf'),
 (11, 'bold_stc_wf'),
 (266,
  '_bold_file_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz_name_source_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz'),
 (23, 'slice_timing_correction'),
 (35, 'result_slice_timing_correction.pklz')]
```

So the issue here is not in STC so much as here:

https://github.com/nipreps/fmriprep/blob/59290411635863f9c7bbd496f414ff80adb466cc/fmriprep/workflows/bold/base.py#L504-L510

And this is a consequence of how nipype expands working directory names, and isn't something we do ourselves. The good news is that I don't think the `name_source` variable is actually necessary here, as it's always identical to `bold_file`. So we should be able to cut the 266-character compoent in half.

**Comment by mgxd** [comment]
Even after the fix in #2651, if this comes up again - [nipype's config](https://miykael.github.io/nipype_tutorial/notebooks/basic_execution_configuration.html#Execution) has a `parameterize_dirs` setting that could help.

**Comment by effigies** [comment]
Should we just set that by default? Or leave it to users to pass the config?

**Comment by mgxd** [comment]
I think we should leave it up to users:
- it would only apply to a small subset of users
- it obfuscates the workdir

**Comment by effigies** [comment]
An alternative approach could be to do something like:

```Python
echos = pe.Node(niu.IdentityInterface(fields=["echoidx"]), name="echos")
echos.iterables = [("echoidx", range(len(bold_files))]

boldbuffer = pe.Node(niu.Select(inlist=bold_files))
if multiecho:
    wf.connect(echos, boldbuffer, [("echoidx", "index")])
else:
    boldbuffer.inputs.index = 0
```

Would turn

```
(266,
  '_bold_file_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz_name_source_..data..MBDU..mid_share..data..bids_defaced..sub-20900..ses-v1..func..sub-20900_ses-v1_task-rest_run-1_echo-2_bold.nii.gz'),
```

Into

```
(10, '_echoidx_0`)
```

WDYT?

**Comment by Shotgunosine** [comment]
That seems like a reasonable compromise between brevity and obfuscation to me.
