### ISSUE TITLE
OSError: Duplicate node name

### ISSUE THREAD

**Issue by djarecka** [nipreps/fmriprep#2672]
### What happened?

I get error when running fmriprep for all subjectd from this dataset

```
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 324, in init_single_subject_wf
    ('outputnode.fsnative2t1w_xfm', 'inputnode.fsnative2t1w_xfm')]),
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 161, in connect
    self._check_nodes(newnodes)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/workflows.py", line 769, in _check_nodes
    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "func_preproc_ses_1_task_rest_run_1_wf" found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 334, in init_single_subject_wf
    raise OSError(msg) from err
OSError: Could not create subworkflow for /DATA/SDSU_1/sub-28852/ses-1/func/sub-28852_ses-1_task-rest_run-1_bold.nii.gz. func_preproc_ses_1_task_rest_run_1_wf already exists. Check if uncompressed (.nii) and compressed (.nii.gz) files are both present.
```

I did check that I only have `nii.gz` file:

```
[10:15][1.93][-50%]djarecka@openmind7:djarecka$ tree data/abide2/RawData/SDSU_1/sub-28852
data/abide2/RawData/SDSU_1/sub-28852
└── ses-1
    ├── anat
    │   └── sub-28852_ses-1_run-1_T1w.nii.gz -> ../../../.git/annex/objects/jm/pG/MD5E-s7746440--e62b3828d4dbd45e547c7d48e9326a85.nii.gz/MD5E-s7746440--e62b3828d4dbd45e547c7d48e9326a85.nii.gz
    └── func
        └── sub-28852_ses-1_task-rest_run-1_bold.nii.gz -> ../../../.git/annex/objects/vK/zK/MD5E-s34339759--764700058fddf3135b62aa9b01e5ec00.nii.gz/MD5E-s34339759--764700058fddf3135b62aa9b01e5ec00.nii.gz
```

cc: @doritdorit

### What command did you use?

```shell
singularity run --cleanenv -B my_base_dir:/BASE -B my_data_dir:/DATA fmriprep-20.2.3.simg /DATA/SDSU_1 /BASE/SDSU_1_derivatives     participant --participant_label sub-28852 --nprocs 8     --output-layout bids     --output-spaces MNI152NLin6Asym:res-2 fsaverage6 T1w:res-2     --use-aroma     --skip-bids-validation --mem_mb 7500     --fs-license-file /DATA/freesurfer_license.txt     --fs-subjects-dir /BASE/SDSU_1_derivatives/freesurfer     --cifti-output -w /BASE/fmriprep-workdir-abide2/SDSU_1/sub-28852
```

### What version of fMRIPrep are you running?

20.2.3

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

### Additional information / screenshots

I know that this dataset is not valid BIDS dataset, the dataset doesn't have the correct participant-id pattern, i.e. code 212 (I also got code 55), but I think this error might be independent. Had similar dataset that were running fine. 

This is the dataset: s3://fcp-indi/data/Projects/ABIDE2/RawData/ABIDEII-SDSU_1

**Comment by effigies** [comment]
Can you try with 20.2.6 to verify the issue has not been addressed?

**Comment by djarecka** [comment]
@effigies - just checked it with 20.2.6 and it looks like the issue persists

**Comment by effigies** [comment]
Duplicate file found in a misnamed derivatives subdirectory.
