### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by dlevitas** [nipreps/fmriprep#2702]
### What happened?

I'm re-processing some data (originally processed using version 20.2.0), and am hitting this error during the `acompcor` confounds renaming procedure. This appears to be the same error as #2659.

### What command did you use?

```shell
unset PYTHONPATH; singularity run \
-B /N/project/bold_perception/LoST:/N/project/bold_perception/LoST \
-B /N/dcwan/projects/irf/templateflow:/opt/templateflow \
-B /N/scratch/dlevitas/fmriprep-21.0.1_temp:/N/scratch/dlevitas/fmriprep-21.0.1_temp \
-B /N/project/bold_perception/LoST/derivatives/fmriprep-21.0.1:/N/project/bold_perception/LoST/derivatives/fmriprep-21.0.1 \
/N/dcwan/projects/irf/containers/fmriprep-21.0.1.simg \
/N/project/bold_perception/LoST \
/N/project/bold_perception/LoST/derivatives/fmriprep-21.0.1 \
participant \
--participant-label 10 \
--skip-bids-validation \
--md-only-boilerplate \
--fs-license-file /N/soft/rhel7/freesurfer/6.0.0/freesurfer/license.txt \
--fs-subjects-dir /N/project/bold_perception/LoST/derivatives/freesurfer-6.0.0 \
--output-spaces MNI152NLin2009cAsym:res-2 MNI152NLin6Asym:res-2 \
--use-aroma \
--nthreads 8 \
--stop-on-first-crash \
--resource-monitor \
--low-mem \
--mem_mb 30000 \
--use-plugin /N/project/bold_perception/LoST/fmriprep_plugin_10.yml \
--verbose \
--output-layout bids \
-w /N/scratch/dlevitas/fmriprep-21.0.1_temp/sub-10
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_wf.single_subject_10_wf.func_preproc_task_lost_run_3_wf.bold_confounds_wf.rename_acompcor
Working directory: /N/scratch/dlevitas/fmriprep-21.0.1_temp/sub-10/fmriprep_wf/single_subject_10_wf/func_preproc_task_lost_run_3_wf/bold_confounds_wf/rename_acompcor

Node inputs:

components_file = <undefined>
metadata_file = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/legacymultiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/interfaces/confounds.py", line 139, in _run_interface
    components = pd.read_csv(self.inputs.components_file, sep='\t')
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers.py", line 1873, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 521, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

### Additional information / screenshots

This error has [currently] only occurred for a specific subject's run. The other subject's runs, and other subjects in general, are not hitting this error, though I will update if that becomes the case. I can't discern anything idiosyncratic about this run, so I'm unsure why it's failing here specifically.

**Comment by effigies** [comment]
Is this data multi-echo?

I believe it's a masking issue. If you have a subject that reliably hits this, would you be willing to share their data privately?

**Comment by dlevitas** [comment]
Not multi-echo, but it has a `MultibandAccelerationFactor` of 8.

Yes, if the issue persists I can share it privately

**Comment by dlevitas** [comment]
Downgraded fmriprep version to 20.2.3 for now, but will reopen if I encounter this error again.
