### ISSUE TITLE
ValueError: Only one phase-encoding direction <j-> found across sources.

### ISSUE THREAD

**Issue by annewilk** [nipreps/fmriprep#2704]
### What happened?

I updated from version 20.2.6 to 21.0.1 and received this error when trying to run fmriprep on the exact same data where it ran using the previous version:

ValueError: Only one phase-encoding direction <j-> found across sources.

I've tried to run various subjects (one at the time) but keep getting this error. 

Thanks!

### What command did you use?

```shell
fmriprep-docker /home/akramer/ProjectJoint/rawdata /home/akramer/ProjectJoint/derivatives --fs-license-file /home/akramer/Downloads/license.txt
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.12 -it -v /home/akramer/Downloads/license.txt:/opt/freesurfer/license.txt:ro -v /home/akramer/ProjectJoint/rawdata:/data:ro -v /home/akramer/ProjectJoint/derivatives:/out nipreps/fmriprep:21.0.1 /data /out participant
bids-validator@1.8.0
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Summary:                  Available Tasks:        Available Modalities: 
        24 Files, 707.16MB        Learning                MRI                   
        1 - Subject               SocialCraving                                 
        2 - Sessions              Resting                                       


	If you have any questions, please post on https://neurostars.org/tags/bids.

220203-15:45:02,611 nipype.workflow IMPORTANT:
	 Running fMRIPrep version 21.0.1

         License NOTICE ##################################################
         fMRIPrep 21.0.1
         Copyright 2021 The NiPreps Developers.
         
         This product includes software developed by
         the NiPreps Community (https://nipreps.org/).
         
         Portions of this software were developed at the Department of
         Psychology at Stanford University, Stanford, CA, US.
         
         This software redistributes the versioneer Python package, which is
         Public domain source code.
         
         This software is also distributed as a Docker container image.
         The bootstraping file for the image ("Dockerfile") is licensed
         under the MIT License.
         
         This software may be distributed through an add-on package called
         "Docker Wrapper" that is under the BSD 3-clause License.
         #################################################################
220203-15:45:02,646 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /data.
           * Participant list: ['101'].
           * Run identifier: 20220203-154449_1409b40e-ec47-4b7a-b900-21018bc9b4e4.
           * Output spaces: MNI152NLin2009cAsym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 324, in init_single_subject_wf
    fmap_estimators = find_estimators(
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/utils/wrangler.py", line 298, in find_estimators
    e = fm.FieldmapEstimation(
  File "<attrs generated init sdcflows.fieldmaps.FieldmapEstimation>", line 7, in __init__
    self.__attrs_post_init__()
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/fieldmaps.py", line 385, in __attrs_post_init__
    raise ValueError(
ValueError: Only one phase-encoding direction <j-> found across sources.
```

**Comment by effigies** [comment]
Thanks for the bug report. Could you share a listing of your BIDS dataset, and the metadata for your BOLD and fieldmap files?

**Comment by eniluap** [comment]
Is there any follow-up on this issue? I have error message. Thanks

**Comment by kahinimehta** [comment]
I am experiencing the same issue!

**What happened?**

I updated from fmriprep 20.2.6 to 21.0.0 in order to use the --me_output-echos flag, but a subject I was able to run through fmriprep previously now errors out. 

**What command did you use?**
fmriprep-docker -i nipreps/fmriprep:21.0.0 /Users/kahinim/Desktop/BIDS /Users/kahinim/Desktop/derivatives --fs-license-file /Users/kahinim/Desktop/derivatives/license.txt --skip-bids-validation --output-spaces MNI152NLin6Asym:res-2 --participant-label SLmobile --force-bbr --cifti-output 91k -v -v --me-output-echos --n_cpus 3

**What version of fMRIPrep are you running?**
21.0.0

**How are you running fMRIPrep?**
Docker

**Is your data BIDS valid?**
Yes

**Are you reusing any previously computed results?**
No

Please copy and paste any relevant log output.
`RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.8 -it -v /Users/kahinim/Desktop/derivatives/license.txt:/opt/freesurfer/license.txt:ro -v /Users/kahinim/Desktop/BIDS:/data:ro -v /Users/kahinim/Desktop/derivatives:/out nipreps/fmriprep:21.0.0 /data /out participant --skip-bids-validation --participant-label SLmobile --force-bbr --cifti-output 91k -v -v --me-output-echos --n_cpus 3 --output-spaces MNI152NLin6Asym:res-2
/opt/conda/lib/python3.8/site-packages/bids/config.py:39: FutureWarning: Setting 'extension_initial_dot' will be removed in pybids 0.16.
  warnings.warn("Setting 'extension_initial_dot' will be removed in pybids 0.16.",
You are using fMRIPrep-21.0.0, and a newer version of fMRIPrep is available: 21.0.2.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
220509-15:59:21,69 cli INFO:
	 Telemetry system to collect crashes and errors is enabled - thanks for your feedback!. Use option ``--notrack`` to opt out.
220509-15:59:27,162 nipype.workflow IMPORTANT:
	 Running fMRIPrep version 21.0.0

         License NOTICE ##################################################
         fMRIPrep 21.0.0
         Copyright 2021 The NiPreps Developers.
         
         This product includes software developed by
         the NiPreps Community (https://nipreps.org/).
         
         Portions of this software were developed at the Department of
         Psychology at Stanford University, Stanford, CA, US.
         
         This software redistributes the versioneer Python package, which is
         Public domain source code.
         
         This software is also distributed as a Docker container image.
         The bootstraping file for the image ("Dockerfile") is licensed
         under the MIT License.
         
         This software may be distributed through an add-on package called
         "Docker Wrapper" that is under the BSD 3-clause License.
         #################################################################
220509-15:59:27,194 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /data.
           * Participant list: ['SLmobile'].
           * Run identifier: 20220509-155919_0b228c02-50c1-4cb6-8905-5e94fd89f5ec.
           * Output spaces: MNI152NLin6Asym:res-2.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 324, in init_single_subject_wf
    fmap_estimators = find_estimators(
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/utils/wrangler.py", line 297, in find_estimators
    e = fm.FieldmapEstimation(
  File "<attrs generated init sdcflows.fieldmaps.FieldmapEstimation>", line 7, in __init__
    self.__attrs_post_init__()
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/fieldmaps.py", line 385, in __attrs_post_init__
    raise ValueError(
ValueError: Only one phase-encoding direction <j> found across sources.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues`

**Comment by kahinimehta** [comment]
**Update**
Switching to version 21.0.2  did not resolve the issue. 

We also attempted adding metadata fields as per new BIDS specifications at `https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#expressing-the-mr-protocol-intent-for-fieldmaps`
```
"B0FieldIdentifier": "pepolar0",
"B0FieldSource": "pepolar0"
```
to the fmap and bold .json sidecars but these have not been implemented yet. 

**What command did you use?**
fmriprep-docker -i nipreps/fmriprep:21.0.0 /Users/kahinim/Desktop/BIDS /Users/kahinim/Desktop/derivatives --fs-license-file /Users/kahinim/Desktop/derivatives/license.txt --skip-bids-validation --output-spaces MNI152NLin6Asym:res-2 --participant-label SLmobile --force-bbr --cifti-output 91k -v -v --me-output-echos --n_cpus 3

**What version of fMRIPrep are you running?**
21.0.2

**How are you running fMRIPrep?**
Docker

**Is your data BIDS valid?**
Yes

**Are you reusing any previously computed results?**
No

**Please copy and paste any relevant log output.**

```
File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 452, in init_single_subject_wf
    raise NotImplementedError(
NotImplementedError: Sophisticated PEPOLAR schemes are unsupported.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

```

**Comment by kahinimehta** [comment]
Update: We had two fmaps, respectively`sub_ses__acq-fMRIdistmap_dir-PA_epi.nii.gz` and `sub_ses__acq-fMRIdistmap_dir-AP_epi.nii.gz` - and deleting one of them, along with its sidecar, resolved the issue.
