### ISSUE TITLE
RuntimeError and OSError

### ISSUE THREAD

**Issue by lollopasquini** [nipreps/fmriprep#2710]
### What happened?

I run fmriprep on a subject with three sessions and get a RuntimeError and then a OSError.

### What command did you use?

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.12 -it -v /Users/lorenzopasquini/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/lorenzopasquini/Desktop/Insight2/bids_coverted:/data:ro -v /Users/lorenzopasquini/Desktop/Insight2/derivatives:/out nipreps/fmriprep:21.0.1 /data /out participant --participant-label 30 --cifti-output --use-aroma --nthreads 4 --mem_mb 20000 --output-spaces MNI152NLin2009cAsym:res-2
```

### What version of fMRIPrep are you running?

fMRIPrep version 21.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: /tmp/work/fmriprep_wf/single_subject_30_wf/func_preproc_ses_2_task_rest_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.res2/threshold/mapflow/_threshold43/result__threshold43.pklz
220208-00:57:34,462 nipype.interface INFO:
	 stderr 2022-02-08T00:57:34.458857:++ 3dvolreg: AFNI version=AFNI_21.3.17 (Dec 30 2021) [64-bit]
220208-00:57:34,468 nipype.interface INFO:
	 stderr 2022-02-08T00:57:34.458857:++ Authored by: RW Cox
220208-00:57:34,474 nipype.interface INFO:
	 stderr 2022-02-08T00:57:34.473110:** AFNI converts NIFTI_datatype=4 (INT16) in file /tmp/work/fmriprep_wf/single_subject_30_wf/func_preproc_ses_2_task_rest_wf/bold_std_trans_wf/bold_reference_wf/_std_target_MNI152NLin2009cAsym.res2/gen_avg/vol0000_xform-00000_clipped_merged_sliced.nii.gz to FLOAT32
220208-00:57:34,475 nipype.interface INFO:
	 stderr 2022-02-08T00:57:34.473110:     Warnings of this type will be muted for this session.
220208-00:57:34,476 nipype.interface INFO:
	 stderr 2022-02-08T00:57:34.473110:     Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
220208-00:58:04,744 nipype.workflow WARNING:
	 Storing result file without outputs
220208-00:58:04,749 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_30_wf.func_preproc_ses_3_task_face_wf.ica_aroma_wf.smooth" (/tmp/work/fmriprep_wf/single_subject_30_wf/func_preproc_ses_3_task_face_wf/ica_aroma_wf/smooth)
exception calling callback for <Future at 0x7f14f0f449d0 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
susan /tmp/work/fmriprep_wf/single_subject_30_wf/func_preproc_ses_3_task_face_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.res2/merge/vol0000_xform-00000_clipped_merged.nii.gz 289.4050597500 2.5479654009 3 1 1 /tmp/work/fmriprep_wf/single_subject_30_wf/func_preproc_ses_3_task_face_wf/ica_aroma_wf/calc_bold_mean/vol0000_xform-00000_clipped_merged_mean.nii.gz 385.8734130000 /tmp/work/fmriprep_wf/single_subject_30_wf/func_preproc_ses_3_task_face_wf/ica_aroma_wf/smooth/vol0000_xform-00000_clipped_merged_smooth.nii.gz
Standard output:

Standard error:
terminate called after throwing an instance of 'NiftiIO::NiftiException'
  what():  Error: short write, output file will be truncated
Aborted
Return code: 134

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 746, in _run_command
    _save_resultfile(
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 235, in save_resultfile
    savepkl(resultsfile, result)
  File "/opt/conda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 720, in savepkl
    pkl_file.write(content)
  File "/opt/conda/lib/python3.8/gzip.py", line 335, in close
    myfileobj.close()
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred
```

**Comment by effigies** [comment]
You need to map a working directory into your container. Try using the `-w` flag with `fmriprep-docker`.

**Comment by lollopasquini** [comment]
this is the running code I get if I add -w just after fmriprep-docker:
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.12 -it -v /Users/lorenzopasquini/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /Users/lorenzopasquini/Desktop/Insight2/derivatives:/data:ro -v /Users/lorenzopasquini/Desktop/Insight2/participant:/out -v /Users/lorenzopasquini/Desktop/Insight2/bids_coverted:/scratch nipreps/fmriprep:21.0.1 /data /out participant --participant-label 30 --cifti-output --use-aroma --nthreads 4 --mem_mb 20000 -w /scratch --output-spaces MNI152NLin2009cAsym:res-2

**Comment by lollopasquini** [comment]
and this is the error I get:
File "/opt/conda/lib/python3.8/site-packages/bids/layout/validation.py", line 73, in validate_root
    raise BIDSValidationError(
bids.exceptions.BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS dataset must have this file.
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}

**Comment by lollopasquini** [comment]
adding -w resulted in a folder been created in Users/lorenzopasquini/Desktop/Insight2, where also the original dataset_description.json file is located

**Comment by effigies** [comment]
Sorry, you need to use `-w /path/to/working/directory`, not just `-w`. It's a scratch directory where intermediate files will be stored. It can be safely deleted once done, and will allow you to reuse partially computed results, if your job is interrupted. See https://fmriprep.org/en/stable/faq.html?highlight=--work-dir#can-fmriprep-continue-to-run-after-encountering-an-error.

**Comment by lollopasquini** [comment]
Thanks again, it worked!
