### ISSUE TITLE
 Errors occurred while processing data from participants

### ISSUE THREAD

**Issue by ilaria-b** [nipreps/fmriprep#2742]
### What happened?

At what seems to be the end of the processing, the terminal returned both a successful and not successful completion. I am reporting because the terminal asks for it but it seems as the processing occurred accurately. 

### What command did you use?

```shell
[XXXXXX:/Volumes/XXXXX/BIDS] XXXXX.lab% fmriprep-docker /Volumes/XXXXXX/BIDS/raw /Volumes/XXXXXX/BIDS/derivatives participant --participant-label sub-021 --fs-license-file /Volumes/XXXXXX/fsl_license/license.txt --skip-bids-validation --fs-no-reconall --dummy-scans 6 --low-mem --output-spaces MNI152NLin2009cAsym:res-2 -w /Volumes/XXXXXXX/Testfolder
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
From terminal: 

Preprocessing did not finish successfully. Errors occurred while processing data from participants: 021 (1). Check the HTML reports for details.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

From error section in the html file:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/interfaces/reports.py", line 125, in _run_interface
    return super(SubjectSummary, self)._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/interfaces/reports.py", line 89, in _run_interface
    segment = self._generate_segment()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/interfaces/reports.py", line 157, in _generate_segment
    counts = Counter(BIDS_NAME.search(series).groupdict()['task_id'][5:]
  File "/opt/conda/lib/python3.8/collections/__init__.py", line 552, in __init__
    self.update(iterable, **kwds)
  File "/opt/conda/lib/python3.8/collections/__init__.py", line 637, in update
    _count_elements(self, iterable)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/interfaces/reports.py", line 157, in 
    counts = Counter(BIDS_NAME.search(series).groupdict()['task_id'][5:]
TypeError: 'NoneType' object is not subscriptable
```

### Additional information / screenshots

The only difference with this participant is that there are 2 T1w and some func scans have the makeup label.

**Comment by mgxd** [comment]
can you share the filenames of the `func/` files for this problematic subject?
