### ISSUE TITLE
nu_correct: crashed while running nu_estimate_np_and_em (termination status=256)

### ISSUE THREAD

**Issue by igorvazz** [nipreps/fmriprep#2743]
### What happened?

Hello, I'm trying to run fmriprep on a singularity container running on a cluster and I'm getting the following error on the html log generated:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
recon-all -autorecon1 -noskullstrip -openmp 8 -subjid sub-0002 -sd /data/derivatives/fmriprep/sourcedata/freesurfer -nomotioncor
Standard output:
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /data/derivatives/fmriprep/sourcedata/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
-rw-rw-r-- 1 ivaz navigator 21860 Mar 23 15:54 /data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/scripts/recon-all.log
Linux barinel057 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/scripts/recon-all.local-copy'
#--------------------------------------------
#@# Talairach Wed Mar 23 16:04:02 WET 2022
/data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/mri

 mri_nu_correct.mni --no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50 

/data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/mri
/opt/freesurfer/bin/mri_nu_correct.mni
--no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50
nIters 1
$Id: mri_nu_correct.mni,v 1.27 2016/02/26 16:19:49 mreuter Exp $
Linux barinel057 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Wed Mar 23 16:04:03 WET 2022
Program nu_correct, built from:
Package MNI N3, version 1.12.0, compiled by nicks@terrier (x86_64-unknown-linux-gnu) on 2015-06-19 at 01:25:34
/bin/bc
tmpdir is ./tmp.mri_nu_correct.mni.22790
/data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/mri
mri_convert orig.mgz ./tmp.mri_nu_correct.mni.22790/nu0.mnc -odt float
mri_convert.bin orig.mgz ./tmp.mri_nu_correct.mni.22790/nu0.mnc -odt float 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from orig.mgz...
TR=2300.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (-1, 0, 0)
j_ras = (0, 0, -1)
k_ras = (0, 1, 0)
changing data type from uchar to float (noscale = 0)...
writing to ./tmp.mri_nu_correct.mni.22790/nu0.mnc...
 
--------------------------------------------------------
Iteration 1 Wed Mar 23 16:04:04 WET 2022
nu_correct -clobber ./tmp.mri_nu_correct.mni.22790/nu0.mnc ./tmp.mri_nu_correct.mni.22790/nu1.mnc -tmpdir ./tmp.mri_nu_correct.mni.22790/0/ -iterations 1000 -distance 50
[ivaz@barinel057:/data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/mri/] [2022-03-23 16:04:04] running:
  /opt/freesurfer/mni/bin/nu_estimate_np_and_em -parzen -log -sharpen 0.15 0.01 -iterations 1000 -stop 0.001 -shrink 4 -auto_mask -nonotify -b_spline 1.0e-7 -distance 50 -quiet -execute -clobber -nokeeptmp -tmpdir ./tmp.mri_nu_correct.mni.22790/0/ ./tmp.mri_nu_correct.mni.22790/nu0.mnc ./tmp.mri_nu_correct.mni.22790/nu1.imp

Assertion failed at line 742 in file templates/CachedArray.cc
nu_estimate_np_and_em: crashed while running volume_stats (termination status=256)
nu_correct: crashed while running nu_estimate_np_and_em (termination status=256)
ERROR: nu_correct
Linux barinel057 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-0002 exited with ERRORS at Wed Mar 23 16:04:04 WET 2022

For more details, see the log file /data/derivatives/fmriprep/sourcedata/freesurfer/sub-0002/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1

```

### What command did you use?

```shell
#!/bin/bash
#
#SBATCH -A myproject
#SBATCH -J fmriprep
#SBATCH --time=48:00:00
#SBATCH -n 1
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=4G
#SBATCH -p cpu1  # Queue names you can submit to
# Outputs ----------------------------------
#SBATCH -o /veracruz/projects/c/myproject/igor/myproject/log/%x-%A-%a.out
#SBATCH -e /veracruz/projects/c/myproject/igor/myproject/log/%x-%A-%a.err
#SBATCH --mail-user=myemail@gmail.com
#SBATCH --mail-type=ALL
# ------------------------------------------


# Import the Singularity module
module load Singularity

temp=`mktemp -d -p /veracruz/projects/c/myproject/fmriprep/tmp`

export TMPDIR=$temp
export SINGULARITY_TMPDIR=$temp
export SINGULARITYENV_TMPDIR=$temp
export SINGULARITY_CACHEDIR=$temp
export SINGULARITYENV_CACHEDIR=$temp

export SINGULARITYENV_MPLCONFIGDIR=$TMPDIR/matplotlib
mkdir -p ${SINGULARITYENV_MPLCONFIGDIR}

HOST_WORK=/veracruz/projects/c/myproject/fmriprep/tmp/work
mkdir -p ${HOST_WORK}

# Set the study folders ADNI
export STUDY=/veracruz/projects/c/myproject/study

BIDS_DIR="$STUDY/bids_subset"
DERIVS_DIR="$BIDS_DIR/derivatives"
LOCAL_FREESURFER_DIR="$DERIVS_DIR/freesurfer" 

# Prepare some writeable bind-mount points.
TEMPLATEFLOW_HOST_HOME=/veracruz/projects/c/myproject/igor/.cache/templateflow

FMRIPREP_HOST_CACHE=/veracruz/projects/c/myproject/igor/.cache/fmriprep
mkdir -p ${TEMPLATEFLOW_HOST_HOME}
mkdir -p ${FMRIPREP_HOST_CACHE}

# Prepare derivatives folder
mkdir -p ${DERIVS_DIR}

mkdir -p ${BIDS_DIR}/derivatives/freesurfer
mkdir -p ${BIDS_DIR}/derivatives/fmriprep

# Make sure FS_LICENSE is defined in the container.
export SINGULARITYENV_FS_LICENSE=/veracruz/projects/c/myproject/fmriprep/license.txt
FS_LICENSE=/veracruz/projects/c/myproject/fmriprep/license.txt

# Designate a templateflow bind-mount point
export SINGULARITYENV_TEMPLATEFLOW_HOME="/templateflow"
SINGULARITY_CMD="singularity run --cleanenv \
-B $FS_LICENSE:/license \
-B $BIDS_DIR:/data \
-B ${TEMPLATEFLOW_HOST_HOME}:${SINGULARITYENV_TEMPLATEFLOW_HOME} \
-B ${SINGULARITY_TMPDIR}:/tmp \
-B ${LOCAL_FREESURFER_DIR}:/fsdir \
-B $HOST_WORK:/work /veracruz/projects/c/myproject/fmriprep/fmriprep21.0.1.simg"

# Parse the participants.tsv file and extract one subject ID from the line corresponding to this SLURM task.
subject=$( sed -n -E "$((${SLURM_ARRAY_TASK_ID} + 1))s/sub-(\S*)\>.*/\1/gp" ${BIDS_DIR}/participants.tsv )

# Compose the command line
cmd="${SINGULARITY_CMD} /data /data/derivatives/fmriprep participant \
 --fs-license-file /license \
 --participant-label $subject \
 -w /work/ \
 -vv \
 --omp-nthreads 8 \
 --nthreads 12 \
 --mem_mb 30000 \
 --fs-subjects-dir /fsdir \
 --output-spaces MNI152NLin2009cAsym:res-2 anat fsnative fsaverage5 --use-aroma"

# Setup done, run the command
echo Running task ${SLURM_ARRAY_TASK_ID}
echo Commandline: $cmd
eval $cmd
exitcode=$?

# Output results to a table
echo "sub-$subject   ${SLURM_ARRAY_TASK_ID}    $exitcode" \
      >> ${SLURM_JOB_NAME}.${SLURM_ARRAY_JOB_ID}.tsv
echo Finished tasks ${SLURM_ARRAY_TASK_ID} with exit code $exitcode
exit $exitcode
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

I'm also running the .slurm script from a bash script with the following code:

```
#! /bin/bash


sbatch --array=1-$(( $( wc -l /veracruz/projects/c/myproject/study/bids_subset/participants.tsv | cut -f1 -d' ' ) - 1 )) /veracruz/projects/c/myproject/fmriprep/sbatch_igor.slurm

```

**Comment by mgxd** [comment]
This looks related to https://github.com/nipreps/fmriprep/issues/1975 - when using the `--cleanenv` flag, environmental variables on the host will not be passed in, except if they start with `SINGULARITYENV_*`. My guess is there are some variables pointing to paths that don't exist within the container, such as:
```
export SINGULARITYENV_FS_LICENSE=/veracruz/projects/c/myproject/fmriprep/license.txt
export SINGULARITYENV_TMPDIR=$temp
```

I'd also double check the expanded `$cmd` and make sure everything looks good.

**Comment by igorvazz** [comment]
thanks for reaching back @mgxd. I've ended up solving this issue by not setting the SINGULARITYENV's at all, and the nu_currect issue was gone
