### ISSUE TITLE
nibabel.filebasedimages.ImageFileError

### ISSUE THREAD

**Issue by xionghuiYu** [nipreps/fmriprep#2747]
### What happened?

nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/data/sub-08/ses-1/func/sub-08_ses-1_task-motor_run-01_bold.nii.gz"

### What command did you use?

```shell
fmriprep-docker

Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 167, in init_func_preproc_wf
    if nb.load(
  File "/opt/conda/lib/python3.8/site-packages/nibabel/loadsave.py", line 55, in load
    raise ImageFileError(f'Cannot work out file type of "{filename}"')
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/data/sub-08/ses-1/func/sub-08_ses-1_task-motor_run-01_bold.nii.gz"


I can not run it!!
Can your help me!
```

### What version of fMRIPrep are you running?

 DOCKER_VERSION_8395080871=20.10.13

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Please provide the full command. And since you have a specific file that is failing, can you confirm it can be opened in another tool, such as fslhd?
