### ISSUE TITLE
traits.trait_errors.TraitError: slice encoding direction related

### ISSUE THREAD

**Issue by GerardYu** [nipreps/fmriprep#2750]
### What happened?

hi, i'm preprocessing multi-echo images from https://openneuro.org/datasets/ds003592/versions/1.0.8 , i'm able to preprocess sub-001 to sub-126 without any issue. However, i've encountered error shown in the pasted log below when i started on sub-264 onwards

the error seems to point to the .json file,  it can't seem to take the value of j- for the slice encoding direction?

```
{
	"EchoTime": 0.014,
	"RepetitionTime": 3,
	"SliceEncodingDirection": "j-",
	"SliceTiming": [
		0,
		1.5425,
		0.07,
		1.6125,
		0.14,
		1.6825,
		0.21,
		1.7525,
		0.28,
		1.8225,
		0.35,
		1.8925,
		0.42,
		1.9625,
		0.49,
		2.0325,
		0.56,
		2.1025,
		0.63,
		2.1725,
		0.7,
		2.2425,
		0.77,
		2.3125,
		0.84,
		2.3825,
		0.91,
		2.4525,
		0.98,
		2.5225,
		1.05,
		2.5925,
		1.12,
		2.6625,
		1.19,
		2.7325,
		1.26,
		2.8025,
		1.33,
		2.8725,
		1.4,
		2.9425,
		1.47	],
	"TaskName": "rest"
}

```

### What command did you use?

```shell
fmriprep BIDS_dir output participant --skip_bids_validation --output-spaces MNI152NLin6Asym --participant-label $d --nthreads 4
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
220329-18:27:40,448 nipype.workflow WARNING:
	 Previous output generated by version 0+unknown found.
220329-18:27:40,564 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /scratch/junhong.yu/SPRENG/BIDS_dir.
           * Participant list: ['264'].
           * Run identifier: 20220329-182727_5241100a-dab1-4045-97f3-796e246ff60a.
           * Output spaces: MNI152NLin6Asym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /scratch/junhong.yu/SPRENG/output/sourcedata/freesurfer.
220329-18:27:44,387 nipype.workflow INFO:
	 No single-band-reference found for sub-264_task-rest_echo-1_bold.nii.gz.
220329-18:27:44,860 nipype.workflow IMPORTANT:
	 BOLD series will be slice-timing corrected to an offset of 1.47s.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/intel/oneapi/2021.3/intelpython/latest/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/intel/oneapi/2021.3/intelpython/latest/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 370, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 497, in init_func_preproc_wf
    bold_stc_wf = init_bold_stc_wf(name="bold_stc_wf", metadata=metadata)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/fmriprep/workflows/bold/stc.py", line 119, in init_bold_stc_wf
    tzero=tzero),
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/nipype/interfaces/afni/base.py", line 214, in __init__
    super(AFNICommand, self).__init__(**inputs)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 627, in __init__
    super(CommandLine, self).__init__(**inputs)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 202, in __init__
    self.inputs.trait_set(**inputs)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/traits/has_traits.py", line 1520, in trait_set
    setattr(self, name, value)
  File "/home/junhong.yu/fmriprepenv/lib/python3.7/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'slice_encoding_direction' trait of a TShiftInputSpec instance must be 'k' or 'k-', but a value of 'j-' <class 'str'> was specified.
```

**Comment by effigies** [comment]
I guess it's time to handle this case. We didn't implement it before, since it will be tricky to be completely sure of and we'd never actually seen data come off the scanner where the slice wasn't the third axis.

**Comment by GerardYu** [comment]
actually i was informed by one of the authors of the dataset that the slice encoding direction should be k. They will be correcting the json files soon

**Comment by effigies** [comment]
Okay. I'm inclined to close this issue then, as the error seems to have caught the bug in the data. The underlying tool 3dTshift does not support STC with a different slice-encoding dimension (and uses k vs k- to indicate whether to reverse the times), probably on the basis that the slice-encoding dimension is always the third. Adding support for other dimensions is more likely to result in silently doing the wrong thing based on bad metadata than handling rare data correctly.
