### ISSUE TITLE
nipype.workflow CRITICAL bug: Can't get attribute 'ValidateImage' 

### ISSUE THREAD

**Issue by andreifoldes** [nipreps/fmriprep#2752]
### What happened?

Tried to run fmriprep 21.0.1 using singularity and got: FileNotFoundError: /home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/select_bold/result_select_bold.pklz

### What command did you use?

```shell
singularity run --cleanenv -B /home/saptaf1/Documents/bids /home/saptaf1/singularity_imgs/niprep_fmriprep.simg /home/saptaf1/Documents/bids /home/saptaf1/Documents/bids/derivatives participant --participant-label "CHOUSM"  --md-only-boilerplate --output-spaces MNI152NLin2009cAsym:res-2 --stop-on-first-crash --mem-mb 16000 --fs-license-file $HOME/freesurfer_license.txt
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
220330-18:39:24,347 nipype.workflow WARNING:
	 Some nodes demand for more threads than available (4).
220330-18:39:54,655 nipype.utils WARNING:
	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
220330-18:39:54,656 nipype.workflow CRITICAL:
	 Can't get attribute 'ValidateImage' on <module 'niworkflows.interfaces.images' from '/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/images.py'>
220330-18:39:54,661 nipype.workflow WARNING:
	 Error while checking node hash, forcing re-run. Although this error may not prevent the workflow from running, it could indicate a major problem. Please report a new issue at https://github.com/nipy/nipype/issues adding the following information:

	Node: fmriprep_wf.single_subject_CHOUSM_wf.func_preproc_task_fLocalizer_run_1_wf.ds_report_validation
	Interface: fmriprep.interfaces.DerivativesDataSink
	Traceback:
Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 347, in _local_hash_check
    cached, updated = self.procs[jobid].is_cached()

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 332, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()

  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _get_inputs
    raise RuntimeError(

RuntimeError: Error populating the inputs of node "ds_report_validation": the results file of the source node (/home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/initial_boldref_wf/val_bold/result_val_bold.pklz) does not contain any outputs.

220330-18:39:54,663 nipype.utils WARNING:
	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
220330-18:39:54,663 nipype.workflow CRITICAL:
	 Can't get attribute 'ValidateImage' on <module 'niworkflows.interfaces.images' from '/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/images.py'>
220330-18:39:54,680 nipype.workflow ERROR:
	 Node ds_report_validation failed to run on host el022.cubric.cf.ac.uk.
220330-18:39:54,684 nipype.workflow ERROR:
	 Saving crash info to /home/saptaf1/Documents/bids/derivatives/sub-CHOUSM/log/20220330-183856_33171a13-4d69-4434-8e2e-b1b37832436f/crash-20220330-183954-saptaf1-ds_report_validation-fe2f5577-aef7-461b-8722-22eb475c7273.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 443, in run
    cached, updated = self.is_cached()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 332, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _get_inputs
    raise RuntimeError(
RuntimeError: Error populating the inputs of node "ds_report_validation": the results file of the source node (/home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/initial_boldref_wf/val_bold/result_val_bold.pklz) does not contain any outputs.

220330-18:39:54,711 nipype.workflow CRITICAL:
	 fMRIPrep failed: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 443, in run
    cached, updated = self.is_cached()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 332, in is_cached
    hashed_inputs, hashvalue = self._get_hashval()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _get_inputs
    raise RuntimeError(
RuntimeError: Error populating the inputs of node "ds_report_validation": the results file of the source node (/home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/initial_boldref_wf/val_bold/result_val_bold.pklz) does not contain any outputs.

220330-18:39:55,449 cli ERROR:
	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: CHOUSM (1). Check the HTML reports for details.
220330-18:39:56,344 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_CHOUSM_wf.func_preproc_task_fLocalizer_run_1_wf.select_bold" in "/home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/select_bold".
220330-18:39:56,566 nipype.utils WARNING:
	 No metadata was found in the pkl file. Make sure you are currently using the same Nipype version from the generated pkl.
220330-18:39:56,567 nipype.workflow CRITICAL:
	 Can't get attribute 'ValidateImage' on <module 'niworkflows.interfaces.images' from '/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/images.py'>
exception calling callback for <Future at 0x7f5c7bcaf9a0 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 486, in run
    self._get_hashval()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 538, in _get_hashval
    self._get_inputs()
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 585, in _get_inputs
    raise RuntimeError(
RuntimeError: Error populating the inputs of node "select_bold": the results file of the source node (/home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/initial_boldref_wf/val_bold/result_val_bold.pklz) does not contain any outputs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 216, in result
    return _load_resultfile(
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/select_bold/result_select_bold.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: /home/saptaf1/work/fmriprep_wf/single_subject_CHOUSM_wf/func_preproc_task_fLocalizer_run_1_wf/select_bold/result_select_bold.pklz
```

**Comment by andreifoldes** [comment]
The error was caused by disk space issues. Please ignore.

**Comment by effigies** [comment]
Thanks for following up!

**Comment by dhyangcheng** [comment]
Hi， I just have the exact same problem.  How do you solve this  problem ?  I am sure there are about 200G free sapce  in my HPC accout.  Thanks in advance！

**Comment by dhyangcheng** [comment]
> The error was caused by disk space issues. Please ignore.

Hi， I just have the exact same problem. How do you solve this problem ? I am sure there are about 200G free sapce in my HPC accout. Thanks in advance！

**Comment by effigies** [comment]
Please open a new issue and provide the error information requested.
