### ISSUE TITLE
fmriprep 21.0.1 FileNotFoundErrors on a HPC cluster

### ISSUE THREAD

**Issue by mikojeske** [nipreps/fmriprep#2755]
### What happened?

Hello everybody,

I am running fmriprep (21.0.1) on a HPC cluster with a singularity image. I had no problems with previous versions of fmriprep (e.g. 20.0.1). But with the newest version, I am running into FileNotFoundErrors and I can't seem to find a good solution. You can find an example of the command I used and the errors I got below.

Based on previous bug reports of other users, it seems to be a filesystem synchronization issue. 

I tried the following things, but had no succes:
- Running the singularity from different directories
- Using different work directories
- Creating different singularity images
- Creating a singularity image locally and then using it on the HPC cluster
- unset PYTHONPATH
- nthreads 1 
- using only one cpu (the cluster says you always needs 2)

I did manage to not get the error by using a workaround from a previous bug report. The workaround uses the following plugin:

plugin: LegacyMultiProc
plugin_args: {maxtasksperchild: 1, memory_gb: 250, n_procs: 16, raise_insufficient: false}

However, this severely slows down fmriprep and causes it to pause on certain analysis steps.

Are there any other things I could do to solve the issue?

### What command did you use?

```shell
singularity run --cleanenv -B /vsc-hard-mounts/leuven-user/333/vsc33337/ -B /vsc-hard-mounts/leuven-data/333/vsc33337/ -B /scratch/leuven/333/vsc33337/ -B /scratch/leuven/333/vsc33337/fmriprep_work/ /vsc-hard-mounts/leuven-data/333/vsc33337/fmriprep_latest.simg /vsc-hard-mounts/leuven-data/333/vsc33337/BIDS /scratch/leuven/333/vsc33337/fmriprep_OUTPUT_sub_$subject participant --output-spaces anat MNI152NLin6Asym:res-2 MNI152NLin2009cAsym --use-aroma --work-dir /scratch/leuven/333/vsc33337/fmriprep_work --resource-monitor --fs-no-reconall --participant-label $subject --fs-license-file /vsc-hard-mounts/leuven-data/333/vsc33337/license.txt
```

### What version of fMRIPrep are you running?

21.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
exception calling callback for <Future at 0x2b01b287b1c0 state=finished raised FileNotFoundError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 512, in run
    savepkl(op.join(outdir, "_node.pklz"), self)
  File "/opt/conda/lib/python3.8/site-packages/nipype/utils/filemanip.py", line 721, in savepkl
    os.rename(tmpfile, filename)
OSError: [Errno 61] No data available: '/scratch/leuven/333/vsc33337/fmriprep_work/fmriprep_wf/single_subject_125_wf/func_preproc_task_ddt2_wf/initial_boldref_wf/gen_avg/_node.pklz.tmp' -> '/scratch/leuven/333/vsc33337/fmriprep_work/fmriprep_wf/single_subject_125_wf/func_preproc_task_ddt2_wf/initial_boldref_wf/gen_avg/_node.pklz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 70, in run_node
    result["result"] = node.result
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 216, in result
    return _load_resultfile(
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 291, in load_resultfile
    raise FileNotFoundError(results_file)
FileNotFoundError: /scratch/leuven/333/vsc33337/fmriprep_work/fmriprep_wf/single_subject_125_wf/func_preproc_task_ddt2_wf/initial_boldref_wf/gen_avg/result_gen_avg.pklz
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 159, in _async_callback
    result = args.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
FileNotFoundError: /scratch/leuven/333/vsc33337/fmriprep_work/fmriprep_wf/single_subject_125_wf/func_preproc_task_ddt2_wf/initial_boldref_wf/gen_avg/result_gen_avg.pklz
```

**Comment by mikojeske** [comment]
The problem was solved by --work-dir $VSC_SCRATCH_NODE as the $VSC_SCRATCH_NODE can be accessed more quickly.
