### ISSUE TITLE
N4BiasFieldCorrection error (137)

### ISSUE THREAD

**Issue by CarlosLeandro09** [nipreps/fmriprep#2825]
### What happened?

Hello everyone,
I've tried to run fMRIPrep to process only one subject, but the procedure always fails. I don't know how to fix it.

### What command did you use?

```shell
python -m fmriprep_docker "/Users/Carlos Leandro/Desktop/Pessoal/Pesquisa/Pesquisas_pessoais/Estudos_em_IRM/Data_bases_fmri/DATA/bids" "/Users/Carlos Leandro/Desktop/Pessoal/Pesquisa/Pesquisas_pessoais/Estudos_em_IRM/Data_bases_fmri/DATA/derivatives" participant --participant-label 01 --skip-bids-validation --md-only-boilerplate --fs-license-file "/Users/Carlos Leandro/Desktop/Pessoal/Pesquisa/Pesquisas_pessoais/Estudos_em_IRM/Data_bases_fmri/DATA/license.txt" --fs-no-reconall --output-spaces MNI152NLin2009cAsym:res-2 --stop-on-first-crash -w "/Users/Carlos Leandro/Desktop/Pessoal/Pesquisa/Pesquisas_pessoais/Estudos_em_IRM/Data_bases_fmri/DATA/workdir"
```

### What version of fMRIPrep are you running?

21.0.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_wf.single_subject_01_wf.anat_preproc_wf.brain_extraction_wf.inu_n4_final
Working directory: /scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/inu_n4_final

Node inputs:

args = <undefined>
bias_image = <undefined>
bspline_fitting_distance = 200.0
bspline_order = <undefined>
convergence_threshold = 1e-07
copy_header = True
dimension = 3
environ = {'NSLOTS': '8'}
histogram_sharpening = <undefined>
input_image = ['/scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_validate/sub-01_run-1_T1w_valid.nii.gz']
mask_image = <undefined>
n_iterations = [50, 50, 50, 50, 50]
num_threads = 8
output_image = <undefined>
rescale_intensities = True
save_bias = True
shrink_factor = 4
weight_image = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1380, in _run_interface
    result = self._collate_results(
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1249, in _collate_results
    for i, nresult, err in nodes:
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
    self.raise_exception(runtime)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
    raise RuntimeError(
RuntimeError: Command:
N4BiasFieldCorrection --bspline-fitting [ 200 ] -d 3 --input-image /scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/anat_validate/sub-01_run-1_T1w_valid.nii.gz --convergence [ 50x50x50x50x50, 1e-07 ] --output [ sub-01_run-1_T1w_valid_corrected.nii.gz, sub-01_run-1_T1w_valid_bias.nii.gz ] -r --shrink-factor 4 --weight-image /scratch/fmriprep_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/map_wmmask/summap_trans.nii.gz
Standard output:

Standard error:
Killed
Return code: 137
```

**Comment by effigies** [comment]
Error code 137 is a memory issue. You may need to adjust Docker settings to ensure there is enough memory available to tools in the container. Or you can also try setting `--mem-mb` lower.

**Comment by CarlosLeandro09** [comment]
Thank you! But `--mem-mb` didn't work. I will try reserve more memory for this task.
