### ISSUE TITLE
T2SMap error

### ISSUE THREAD

**Issue by quach-al** [nipreps/fmriprep#2827]
### What happened?

I am trying to run fmriprep on a multi-echo dataset and run into this error for each of my multi-echo scans. This happened when I tried to re-run it a second time as well.

### What command did you use?

```shell
fmriprep-docker BIDS_DIR \
                derivatives \
                participant \
                --notrack \
                --me-output-echos \
                --work-dir WORK_DIR \
                --fs-license-file /Applications/freesurfer/license.txt \
```

### What version of fMRIPrep are you running?

22.0.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_22_0_wf.single_subject_retrotest001_wf.func_preproc_ses_01_task_arrows_acq_3x2me3_dir_PA_run_01_echo_1_wf.bold_t2smap_wf.t2smap_node
Working directory: /scratch/fmriprep_22_0_wf/single_subject_retrotest001_wf/func_preproc_ses_01_task_arrows_acq_3x2me3_dir_PA_run_01_echo_1_wf/bold_t2smap_wf/t2smap_node

Node inputs:

args = <undefined>
echo_times = [0.0142, 0.03539, 0.05658]
environ = {}
fittype = curvefit
in_files = <undefined>
mask_file = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node t2smap_node.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
    setattr(outputs, key, val)
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'optimal_comb' trait of a T2SMapOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch/fmriprep_22_0_wf/single_subject_retrotest001_wf/func_preproc_ses_01_task_arrows_acq_3x2me3_dir_PA_run_01_echo_1_wf/bold_t2smap_wf/t2smap_node/desc-optcom_bold.nii.gz' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 401, in run
    outputs = self.aggregate_outputs(runtime)
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/scratch/fmriprep_22_0_wf/single_subject_retrotest001_wf/func_preproc_ses_01_task_arrows_acq_3x2me3_dir_PA_run_01_echo_1_wf/bold_t2smap_wf/t2smap_node/desc-optcom_bold.nii.gz' for output 'optimal_comb' of a T2SMap interface
```

**Comment by mgxd** [comment]
This may be hitting https://github.com/nipy/nipype/issues/3493

Can you try clearing the `WORK_DIR/fmriprep_22_0_wf/single_subject_retrotest001_wf/func_preproc_ses_01_task_arrows_acq_3x2me3_dir_PA_run_01_echo_1_wf/bold_t2smap_wf/t2smap_node` directory and rerunning?

**Comment by quach-al** [comment]
Hi, thanks for the reply! I tried your suggestion and received the same error.

**Comment by AndreaZHU111** [comment]
> Hi, thanks for the reply! I tried your suggestion and received the same error.

Hi, I wonder if you have solved this problem? I have the same error and I have no idea what to do.

**Comment by tsalo** [comment]
Can you check the working directory to see what exists within the t2smap node's folder?

**Comment by effigies** [comment]
I think we should probably close this. It's old and there's not enough to say what went wrong. In more recent versions we should at least get stderr and stdout, so we might get any error reporting that tedana provides.
