### ISSUE TITLE
RuntimeError: No BOLD images found for participant sub01 and task <all>. All workflows require BOLD images.

### ISSUE THREAD

**Issue by WeiShaoD** [nipreps/fmriprep#2833]
### What happened?

Hello, Dear Fmriprep community

I was running fmriprep to preprocess data on my local machine MacOS within docker, But there is a problem 

RuntimeError: No BOLD images found for participant sub01 and task <all>. All workflows require BOLD images

I think I put the bold files within the subdirectory from the input directory

(base) weishao@wei sub-sub01 % ls anat 
501_Sub01_sT1W_3D_TFE_32chSHC_20180802141246.json       501_Sub01_sT1W_3D_TFE_32chSHC_20180802141246.nii.gz
(base) weishao@wei sub-sub01 % ls func 
201_Sub01_bold_R1.json          201_Sub01_bold_R1.nii.gz        301_Sub01_bold_R2.json          301_Sub01_bold_R2.nii.gz        401_Sub01_bold_R3.json          401_Sub01_bold_R3.nii.gz
(base) weishao@wei sub-sub01 % 

### What command did you use?

```shell
Here is my script 

#!/bin/bash

export PATH="/Users/weishao/.local/bin:$PATH"
export DOCKER_DEFAULT_PLATFORM=linux/amd64

#User inputs:
bids_root_dir=/Users/weishao/Documents/2020_confidence/Sub01
subj=sub01
nthreads=4
mem=20 #gb
container=docker #docker or singularity

#Begin:

#Convert virtual memory from gb to mb
mem=`echo "${mem//[!0-9]/}"` #remove gb at end
mem_mb=`echo $(((mem*1000)-5000))` #reduce some memory for buffer space during pre-processing

#export TEMPLATEFLOW_HOME=$HOME/.cache/templateflow
export FS_LICENSE=$HOME/Desktop/Flanker/derivatives/license.txt

#Run fmriprep
fmriprep-docker $bids_root_dir $bids_root_dir/derivatives \
    participant \
    --participant-label sub-sub01 \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-license-file /Users/weishao/Documents/2020_confidence/Sub01/license.txt \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb
```

### What version of fMRIPrep are you running?

fMRIPrep 22.0.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.17 -it -v /Users/weishao/Documents/2020_confidence/Sub01/license.txt:/opt/freesurfer/license.txt:ro -v /Users/weishao/Documents/2020_confidence/Sub01:/data:ro -v /Users/weishao/Documents/2020_confidence/Sub01/derivatives:/out nipreps/fmriprep:22.0.0 /data /out participant --participant-label sub-sub01 --skip-bids-validation --md-only-boilerplate --fs-no-reconall --nthreads 4 --stop-on-first-crash --mem_mb 15000 --output-spaces MNI152NLin2009cAsym:res-2
x220808-15:36:47,781 nipype.workflow IMPORTANT:
         Running fMRIPrep version 22.0.0

         License NOTICE ##################################################
         fMRIPrep 22.0.0
         Copyright 2022 The NiPreps Developers.
         
         This product includes software developed by
         the NiPreps Community (https://nipreps.org/).
         
         Portions of this software were developed at the Department of
         Psychology at Stanford University, Stanford, CA, US.
         
         This software redistributes the versioneer Python package, which is
         Public domain source code.
         
         This software is also distributed as a Docker container image.
         The bootstraping file for the image ("Dockerfile") is licensed
         under the MIT License.
         
         This software may be distributed through an add-on package called
         "Docker Wrapper" that is under the BSD 3-clause License.
         #################################################################
220808-15:37:49,278 nipype.workflow IMPORTANT:
         Building fMRIPrep's workflow:
           * BIDS dataset path: /data.
           * Participant list: ['sub01'].
           * Run identifier: 20220808-153358_f27b51f2-6b45-46a8-9e66-50ee6a0f2e9b.
           * Output spaces: MNI152NLin2009cAsym:res-2.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 89, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 171, in init_single_subject_wf
    raise RuntimeError(
RuntimeError: No BOLD images found for participant sub01 and task <all>. All workflows require BOLD images.
```

### Additional information / screenshots

please

**Comment by mgxd** [comment]
@WeiShaoD your data is not in BIDS format - please see https://www.nipreps.org/apps/framework/#what-is-bids for more details
