### ISSUE TITLE
LTS : Importing the numpy C-extensions failed. 

### ISSUE THREAD

**Issue by emdupre** [nipreps/fmriprep#2845]
### What happened?

I'm seeing a new error when running the fMRIPrep LTS -- specifically, it fails on the initial `from fmriprep.cli.run import main` call. The full traceback is below, but the error message points to a numpy installation issue :

```
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/local/miniconda/bin/python"
  * The NumPy version is: "1.20.3"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

Is this something others have also noted ? cc @bpinsard for insight !

### What command did you use?

```shell
singularity run -B ${DATADIR}:/data:ro \
	-B ${SCRATCH}:/out \
	-B ${LICENSE}/license.txt:/license/license.txt:ro \
	${SIMGDIR}/fmriprep-20.2.3.simg \
	/data /out participant \
        --participant-label sub-${sub} \
        -t Raiders \
	--output-space fsaverage5 MNI152NLin2009cAsym:res-2 \
	-w /out/workdir \
	--notrack \
    --fs-license-file /license/license.txt 
```
```


### What version of fMRIPrep are you running?

20.2.3

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 6, in <module>
    from fmriprep.cli.run import main
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 4, in <module>
    from .. import config
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/config.py", line 95, in <module>
    from nipype import __version__ as _nipype_ver
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/__init__.py", line 18, in <module>
    from .utils.config import NipypeConfig
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/utils/config.py", line 19, in <module>
    import numpy as np
  File "/share/software/user/open/py-numpy/1.20.3_py39/lib/python3.9/site-packages/numpy/__init__.py", line 145, in 
<module>
    from . import core
  File "/share/software/user/open/py-numpy/1.20.3_py39/lib/python3.9/site-packages/numpy/core/__init__.py", line 48,
 in <module>
    raise ImportError(msg)
```
```


### Additional information / screenshots

_No response_

**Comment by effigies** [comment]
It looks like there's numpy being imported from outside the container. Can you use --cleanenv?

**Comment by emdupre** [comment]
Argh, yes, you're right ! Re-ran again and it's fine. I'm re-using a few pre-built images, and I should have checked this beforehand 🙇  Sorry for the noise !
