### ISSUE TITLE
NodeExecutionError & FileNotFoundError while performing fmriPrep steps using docker

### ISSUE THREAD

**Issue by kartikeysaran** [nipreps/fmriprep#2856]
### What happened?

While using fmriPrep on my [open neuro fmri dataset](https://openneuro.org/datasets/ds000052/versions/00001) i got NodeExecutionError and FileNotFoundError

I am Pasting the complete error below

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node norm.

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 90, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/work/fmriprep_22_0_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/fixes.py", line 110, in _run_interface
    _copyxform(
  File "/opt/conda/lib/python3.9/site-packages/niworkflows/utils/images.py", line 79, in _copyxform
    resampled = nb.load(out_image, mmap=False)
  File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 92, in load
    raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/tmp/work/fmriprep_22_0_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'

I am also attaching the html file generated by fmriPrep
Link to [HTML file generated](https://drive.google.com/file/d/1CL88bP_sIBtDWLOttxpIxfd-QxCQpg0v/view?usp=sharing)

### What command did you use?

```shell
`fmriprep-docker /Users/lenovo/Desktop/drdo /Users/lenovo/Desktop/drdo/output participant --participant-label 01 --fs-license-file /Users/lenovo/Desktop/drdo/output/license.txt`
```

### What version of fMRIPrep are you running?

0.4.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
result["result"] = node.run(updatehash=updatehash)
File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
result = self._run_interface(execute=True)
File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
return self._run_command(execute)
File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node norm.

Traceback (most recent call last):
File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 90, in load
stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/work/fmriprep_22_0_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
runtime = self._run_interface(runtime)
File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/fixes.py", line 110, in _run_interface
_copyxform(
File "/opt/conda/lib/python3.9/site-packages/niworkflows/utils/images.py", line 79, in _copyxform
resampled = nb.load(out_image, mmap=False)
File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 92, in load
raise FileNotFoundError(f"No such file or no access: '{filename}'")
FileNotFoundError: No such file or no access: '/tmp/work/fmriprep_22_0_wf/single_subject_01_wf/anat_preproc_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'
```

### Additional information / screenshots

i followed [this tutorial](https://medium.com/@gelana/using-fmriprep-for-fmri-data-preprocessing-90ce4a9b85bd) and used the same data as used in this tutorial , i got error regarding the license.txt file that i got from freesurfer as NameException so i added it into the `.bidsignore` file and the code seemed to work but after this i also got another warning that 3.80GB is available on the location you have provided and that might be not enough for the fmriPrep execution and it proceeded and finally it showed the above error 

I would really be thankful if someone solves my problem as i am stuck in this from the past few days 
Thankyou in advance :)

**Comment by kartikeysaran** [comment]
@effigies Can you please have a look

**Comment by juansanchezpena** [comment]
I got this:
[juan@doctor 20220926-165232_81ad38b9-f534-4d34-a5c4-dc2190e64255]$ cat crash-20220926-211200-root-_autorecon_surfs0-71f68aac-5301-492b-9457-85844088396e.txt
Node: _autorecon_surfs0
Working directory: /tmp/work/fmriprep_22_0_wf/single_subject_patensasc0085_wf/anat_preproc_wf/surface_recon_wf/autorecon_resume_wf/autorecon_surfs/mapflow/_autorecon_surfs0

Node inputs:

FLAIR_file = <undefined>
T1_files = <undefined>
T2_file = <undefined>
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = autorecon-hemi
environ = {}
expert = <undefined>
flags = ['-noparcstats', '-noparcstats2', '-noparcstats3', '-nohyporelabel', '-nobalabels']
hemi = lh
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = <undefined>
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
steps = <undefined>
subject_id = sub-patensasc0085
subjects_dir = /output/freesurfer
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _autorecon_surfs0.

RuntimeError: subprocess exited with code 1.

**Comment by effigies** [comment]
@juansanchezpena Please post to a new issue or find one that has the same issue.

**Comment by effigies** [comment]
@kartikeysaran Apologies for the delay. I'll note that you said you're using fMRIPrep 0.4.2, but your workflow directory is `/tmp/work/fmriprep_22_0_wf`, so it seems likely you're using 22.0.x.

Based on `3.80GB space is available on the provided path which might not be enough for the fmriPrep execution`, it would make sense that a file was unable to be written, and then an attempt to modify it would fail. Also, you are writing into your container `/tmp` instead of mounting a working directory with `-w`. I would try something like:

```
fmriprep-docker /Users/lenovo/Desktop/drdo /Users/lenovo/Desktop/drdo/output participant \
    --participant-label 01 --fs-license-file /Users/lenovo/Desktop/drdo/output/license.txt \
    -w /Users/lenovo/Desktop/drdo/scratch
```
