### ISSUE TITLE
Defined but empty SliceTiming should be skipped

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep#2867]
### What happened?

fMRIprep on [ds001242](https://openneuro.org/datasets/ds001242) leads to https://github.com/poldracklab/tacc-openneuro/issues/30:

```
Process Process-2:
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
retval["workflow"] = init_fmriprep_wf()
File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 89, in init_fmriprep_wf
single_subject_wf = init_single_subject_wf(subject_id)
File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 374, in init_single_subject_wf
func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/base.py", line 440, in init_func_preproc_wf
func_derivatives_wf = init_func_derivatives_wf(
File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/outputs.py", line 164, in init_func_derivatives_wf
timing_parameters = prepare_timing_parameters(metadata)
File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/outputs.py", line 96, in prepare_timing_parameters
TA = st[-1] + (st[1] - st[0]) # Final slice onset - slice duration
IndexError: list index out of range
```

### What command did you use?

```shell
TACC openneuro script
```

### What version of fMRIPrep are you running?

22

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
It seems like this should already be the case? I guess this will take active debugging.

https://github.com/nipreps/fmriprep/blob/7124ef2c50cd4d58b94689b10eb9666c55afd711/fmriprep/workflows/bold/base.py#L322
