### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

### ISSUE THREAD

**Issue by megq** [nipreps/fmriprep#2873]
Hello, I've run this same script to convert DICOMS to bids format a bunch of times for participants within this study, but this one appears to be erroring and I'm not sure why. They have all the correct files and I can't seem to find the issue. 

I looked back at previous issues with similar errors and that fix didn't work for me unfortunately. 

Thank you!

INFO: Running heudiconv version 0.5.4
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 's4111', 'outdir': '/out/bids/', 'session': None}
INFO: Processing 1304 dicoms
INFO: Reloading existing filegroup.json because /out/bids/.heudiconv/s4111/info/s4111.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Populating template files under /out/bids/
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 323, in process_args
    dcmconfig=args.dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 212, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/src/heudiconv/heudiconv/bids.py", line 77, in populate_bids_templates
    populate_aggregated_jsons(path)
  File "/src/heudiconv/heudiconv/bids.py", line 109, in populate_aggregated_jsons
    json_ = load_json(fpath)
  File "/src/heudiconv/heudiconv/utils.py", line 176, in load_json
    data = json.load(fp)
  File "/opt/miniconda-latest/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/opt/miniconda-latest/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
chmod: cannot access '/data/projects/STUDIES/SEAT/fMRI/bids/sub-s4111': No such file or directory

**Comment by mgxd** [comment]
This looks like it was meant for the [nipy/heudiconv](https://github.com/nipy/heudiconv) repo, please open an issue there
