### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by ErikJahner** [nipreps/fmriprep#2883]
### What happened?

I am trying to run frmri prep and i get this error. Fmriprep worked previously

### What command did you use?

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.8 -it -v //Users/mhiylab/IVA_project.v2/derivatives/license.txt:/opt/freesurfer/license.txt:ro -v //Users/mhiylab/IVA_project.v2/bids:/data:ro -v //Users/mhiylab/IVA_project.v2/derivatives:/out -v /Users/mhiylab/Desktop/tmp/402:/scratch nipreps/fmriprep:21.0.2 /data /out participant --participant-label sub-402 --use-aroma --low-mem --nthreads 13 --mem_mb 24000 --md-only-boilerplate --stop-on-first-crash --clean-workdir --resource-monitor -w /scratch --output-spaces MNI152NLin2009cAsym MNI152NLin6Asym
```

### What version of fMRIPrep are you running?

fMRIPrep-21.0.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 66, in build_workflow
    msg = check_pipeline_version(version, fmriprep_dir / "dataset_description.json")
  File "/opt/conda/lib/python3.8/site-packages/niworkflows/utils/bids.py", line 447, in check_pipeline_version
    desc = json.loads(data_desc.read_text())
  File "/opt/conda/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
402
```

**Comment by effigies** [comment]
Can you share the contents of the `dataset_desription.json` that's in your output directory?

**Comment by effigies** [comment]
Please reopen if you have more information.
