### ISSUE TITLE
[fmriprep-docker][Command bids-validator not found]

### ISSUE THREAD

**Issue by silk1100** [nipreps/fmriprep#2911]
### What happened?

I installed fmriprep and fmriprep-docker. docker is up and running on my linux machine. After I ran fmriprep-docker command as follow:
`fmriprep-docker GU_1/ ./output/ participant -w ./work/ --participant-label 28824 --omp-nthreads 9 --mem 8000`
docker started pulling the required images and then I received the following error

```
Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 39, in main
    parse_args()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/parser.py", line 790, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/utils/bids.py", line 186, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmp4tpo_wz_.json']' returned non-zero exit status 1.
```

### What command did you use?

```shell
fmriprep-docker GU_1/ ./output/ participant -w ./work/ --participant-label 28824 --omp-nthreads 9 --mem 8000
```

### What version of fMRIPrep are you running?

fMRIPrep v22.0.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Additional information / screenshots

```
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.21 -it -v /home/mohamedta/ABIDEII/GU_1:/data:ro -v /home/mohamedta/ABIDEII/output:/out -v /home/mohamedta/ABIDEII/work:/scratch nipreps/fmriprep:22.0.2 /data /out participant --participant-label 28824 --omp-nthreads 9 --mem 8000 -w /scratch
bids-validator@1.8.0

        1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)                                   
                ./task-rest_bold.json
                        Evidence: .AcquisitionDuration should be number

        Please visit https://neurostars.org/search?q=JSON_SCHEMA_VALIDATION_ERROR for existing conversations about this issue.                                  

        1: [WARN] The recommended file /README is missing. See Section 03 (Modality agnostic files) of the BIDS specification. (code: 101 - README_FILE_MISSING)

        Please visit https://neurostars.org/search?q=README_FILE_MISSING for existing conversations about this issue.                                           

        2: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered because there are no authors, which will make DOI registration from dataset metadata impossible. (code: 113 - NO_AUTHORS)                                                     

        Please visit https://neurostars.org/search?q=NO_AUTHORS for existing conversations about this issue.                                                    


        Summary:                 Available Tasks:        Available Modalities: 
        185 Files, 3.37GB        rest                    MRI                   
        106 - Subjects                                                         
        1 - Session                                                            


        If you have any questions, please post on https://neurostars.org/tags/bids.                                                                             

Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 39, in main
    parse_args()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/parser.py", line 790, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/utils/bids.py", line 186, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmp4tpo_wz_.json']' returned non-zero exit status 1.
```

**Comment by effigies** [comment]
The validator did run, and it raised an error because you have an invalid field:

```
        1: [ERR] Invalid JSON file. The file is not formatted according the schema. (code: 55 - JSON_SCHEMA_VALIDATION_ERROR)                                   
                ./task-rest_bold.json
                        Evidence: .AcquisitionDuration should be number
```

What are the contents of `task-rest_bold.json`? I'm a bit surprised that `AcquisitionDuration` is defined, since resting state runs rarely use sparse acquisition.

**Comment by effigies** [comment]
Looks like bad metadata that doesn't conform to the BIDS specification. I would just remove that field and report to the dataset maintainers that they need to fix it.

**Comment by Dakshithas** [comment]
I'm also facing the same issue.

**Comment by effigies** [comment]
@Dakshithas As far as I can tell this issue is resolved. Please open a new bug report with what you're seeing.
