### ISSUE TITLE
SDC b-spline matrix issue

### ISSUE THREAD

**Issue by aiims-himanshu** [nipreps/fmriprep#2919]
### What happened?

i recently updated to new version to test for shift for processing of dataset. however the new version is having b spline transform matrix error for one of the session run. 

i previously used 21.0.1 version and there was no such issue in that. also i am currently testing the 22.0.2 versionb for any such issue. 

[crash-20221220-055756-root-resample-7a3a983f-6222-49ed-908c-7107caea8ec3.txt](https://github.com/nipreps/fmriprep/files/10267303/crash-20221220-055756-root-resample-7a3a983f-6222-49ed-908c-7107caea8ec3.txt)

following issue is not persistent in same subject other two dataset which were acquired in same session.

### What command did you use?

```shell
time sudo docker run -ti --rm \
-v //media/himanshu/m2/trial/input:/data:ro \
-v /media/himanshu/m2/trial/output5:/out \
-v /media/himanshu/m2/trial/tmp4:/w \
-v /home/himanshu/freesurfer/:/freesurfer \
-v /media/himanshu/m2/trial/freesurfer/:/fsdir \
nipreps/fmriprep:22.0.2 \
/data /out \
participant \
--fs-license-file /freesurfer/license.txt \
-w /w \
--fs-subjects-dir /fsdir \
--use-aroma \
--bold2t1w-init register \
--skull-strip-t1w force \
--output-spaces MNI152NLin6Asym fsnative T1w \
--me-output-echos \
--bold2t1w-dof 12 \
--notrack \
--cifti-output 91k \
--notrack
```

### What version of fMRIPrep are you running?

22.1.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
File: /out/sub-01/log/20221220-053329_dde2bd67-e31c-4d00-acec-cc752f227077/crash-20221220-055756-root-resample-7a3a983f-6222-49ed-908c-7107caea8ec3.txt
Working Directory: /w/fmriprep_22_1_wf/single_subject_01_wf/func_preproc_task_motor_run_01_wf/unwarp_wf/resample
Inputs:
in_coeff:
in_data:
in_xfms:
num_threads: 8
pe_dir:
ro_time:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node resample.

Traceback:
	concurrent.futures.process._RemoteTraceback: 
	"""
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
	    r = call_item.fn(*call_item.args, **call_item.kwargs)
	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
	    return [fn(*args) for args in chunk]
	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 202, in 
	    return [fn(*args) for args in chunk]
	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/interfaces/bspline.py", line 624, in _b0_resampler
	    if unwarp.fit(distorted_img):
	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/transform.py", line 99, in fit
	    wmat = grid_bspline_weights(spatialimage, moved_cs)
	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/transform.py", line 417, in grid_bspline_weights
	    colloc_ax = BSpline.design_matrix(x, t, 3)[:, (2 + pad_left):-(2 + pad_right)]
	  File "/opt/conda/lib/python3.9/site-packages/scipy/interpolate/_bsplines.py", line 416, in design_matrix
	    raise ValueError(f'Out of bounds w/ x = {x}.')
	ValueError: Out of bounds w/ x = [ 4.37191168  4.86487637  5.35784106  5.85080575  6.34377045  6.83673514
	  7.32969983  7.82266452  8.31562921  8.8085939   9.30155859  9.79452329
	 10.28748798 10.78045267 11.27341736 11.76638205 12.25934674 12.75231144
	 13.24527613 13.73824082 14.23120551 14.7241702  15.21713489 15.71009959
	 16.20306428 16.69602897 17.18899366 17.68195835 18.17492304 18.66788773
	 19.16085243 19.65381712 20.14678181 20.6397465  21.13271119 21.62567588
	 22.11864058 22.61160527 23.10456996 23.59753465 24.09049934 24.58346403
	 25.07642873 25.56939342 26.06235811 26.5553228  27.04828749 27.54125218
	 28.03421687 28.52718157 29.02014626 29.51311095 30.00607564 30.49904033
	 30.99200502 31.48496972 31.97793441 32.4708991  32.96386379 33.45682848].
```

**Comment by effigies** [comment]
If you look in your working directory, you should find something like `fmriprep_22_1_wf/single_subject_*_wf/func_preproc_ses_1_task_*_wf/unwarp_wf/resample/_report/report.rst`. There should be a section `Original Inputs`. If you could share the file(s) in `in_coeff`, `in_xfms` and the first file in `in_data`, that would help us to debug this issue.
