### ISSUE TITLE
 Command '['bids-validator' Error

### ISSUE THREAD

**Issue by Dakshithas** [nipreps/fmriprep#2924]
### What happened?

try to preprocess the FMRI dataset and fail. Then try a dataset that I already preprocessed using fmriprep two months ago. the same error prompt there too.

### What command did you use?

```shell
sudo fmriprep-docker data/ds004241-download data/ds004241-download/derivatives participant --fs-license-file data/license.txt
```

### What version of fMRIPrep are you running?

22.1.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.17 -it -v /home/rnd/data/license.txt:/opt/freesurfer/license.txt:ro -v /home/rnd/data/ds004241-download:/data:ro -v /home/rnd/data/ds004241-download/derivatives:/out nipreps/fmriprep:22.1.0 /data /out participant
--topup-max-vols input is no longer used and the flag will be removed in a future release.
bids-validator@1.8.0

        1: [ERR] Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./annex-uuid
                        Evidence: annex-uuid

        Please visit https://neurostars.org/search?q=NOT_INCLUDED for existing conversations about this issue.


        Summary:             Available Tasks:        Available Modalities:
        38 Files, 1GB                                MRI
        32 - Subjects
        1 - Session


        If you have any questions, please post on https://neurostars.org/tags/bids.

Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 42, in main
    parse_args()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/parser.py", line 810, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/utils/bids.py", line 186, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmpnohkdyyi.json']' returned non-zero exit status 1.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

**Comment by effigies** [comment]
It looks like you have an `annex-uuid` file in your dataset that is causing the validator to error out.
