### ISSUE TITLE
NodeExecutionError:  

### ISSUE THREAD

**Issue by juansanchezpena** [nipreps/fmriprep#2933]
### What happened?

I saw **fmriprep / nipype NodeExecutionError #3415** but did not see any comments. 

Node: fmriprep_22_1_wf.single_subject_patensasc0089_wf.func_preproc_ses_1385_task_rest_run_05_wf.unwarp_wf.resample
Working directory: /tmp/work/fmriprep_22_1_wf/single_subject_patensasc0089_wf/func_preproc_ses_1385_task_rest_run_05_wf/unwarp_wf/resample

Node inputs:

in_coeff = <undefined>
in_data = <undefined>
in_xfms = <undefined>
num_threads = 8
pe_dir = <undefined>
ro_time = <undefined>

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node resample.

### What command did you use?

```shell
Running fMRIPrep version 22.1.0+0.gce344b39.dirty

docker service create --replicas 1 --reserve-cpu 8 --reserve-memory 16g --mode replicated --restart-condition none  --mount type=bind,source=$indir,destination=/input,readonly=true --mount type=bind,source=$outdir,destination=/output  --mount type=bind,source=/MRI_DATA/bin/freesurferlicense.txt,destination=/opt/freesurfer/license.txt,readonly=true  nipreps/fmriprep:22.1.0  /input /output participant $addarg
```

### What version of fMRIPrep are you running?

22.1.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
230111-08:36:34,445 nipype.workflow ERROR:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 could not run node: fmriprep_22_1_wf.single_subject_patensasc0085_wf.func_preproc_ses_1173_task_rest_run_04_wf.unwarp_wf.resample
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 230111-08:36:35,519 nipype.workflow CRITICAL:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 fMRIPrep failed: Traceback (most recent call last):
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |     result["result"] = node.run(updatehash=updatehash)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |     result = self._run_interface(execute=True)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |     return self._run_command(execute)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    |     raise NodeExecutionError(msg)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node resample.
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | Traceback:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	concurrent.futures.process._RemoteTraceback: 
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	"""
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	Traceback (most recent call last):
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    r = call_item.fn(*call_item.args, **call_item.kwargs)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    return [fn(*args) for args in chunk]
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    return [fn(*args) for args in chunk]
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/interfaces/bspline.py", line 624, in _b0_resampler
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    if unwarp.fit(distorted_img):
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/transform.py", line 99, in fit
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    wmat = grid_bspline_weights(spatialimage, moved_cs)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/transform.py", line 417, in grid_bspline_weights
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    colloc_ax = BSpline.design_matrix(x, t, 3)[:, (2 + pad_left):-(2 + pad_right)]
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/site-packages/scipy/interpolate/_bsplines.py", line 416, in design_matrix
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    raise ValueError(f'Out of bounds w/ x = {x}.')
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	ValueError: Out of bounds w/ x = [ 3.62616494  4.12461877  4.6230726   5.12152642  5.61998025  6.11843408
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  6.61688791  7.11534173  7.61379556  8.11224939  8.61070322  9.10915704
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  9.60761087 10.1060647  10.60451853 11.10297235 11.60142618 12.09988001
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 12.59833384 13.09678766 13.59524149 14.09369532 14.59214915 15.09060297
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 15.5890568  16.08751063 16.58596446 17.08441828 17.58287211 18.08132594
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 18.57977977 19.07823359 19.57668742 20.07514125 20.57359508 21.0720489
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 21.57050273 22.06895656 22.56741039 23.06586421 23.56431804 24.06277187
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 24.5612257  25.05967952 25.55813335 26.05658718 26.55504101 27.05349483
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 27.55194866 28.05040249 28.54885632 29.04731014 29.54576397 30.0442178
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 30.54267163 31.04112545 31.53957928 32.03803311 32.53648694 33.03494076
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 33.53339459 34.03184842 34.53030225 35.02875607 35.5272099  36.02566373].
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	"""
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	The above exception was the direct cause of the following exception:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	Traceback (most recent call last):
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    runtime = self._run_interface(runtime)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/site-packages/sdcflows/interfaces/bspline.py", line 373, in _run_interface
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    ) = zip(*outputs)
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    for element in iterable:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    yield fs.pop().result()
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    return self.__get_result()
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	    raise self._exception
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	ValueError: Out of bounds w/ x = [ 3.62616494  4.12461877  4.6230726   5.12152642  5.61998025  6.11843408
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  6.61688791  7.11534173  7.61379556  8.11224939  8.61070322  9.10915704
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	  9.60761087 10.1060647  10.60451853 11.10297235 11.60142618 12.09988001
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 12.59833384 13.09678766 13.59524149 14.09369532 14.59214915 15.09060297
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 15.5890568  16.08751063 16.58596446 17.08441828 17.58287211 18.08132594
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 18.57977977 19.07823359 19.57668742 20.07514125 20.57359508 21.0720489
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 21.57050273 22.06895656 22.56741039 23.06586421 23.56431804 24.06277187
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 24.5612257  25.05967952 25.55813335 26.05658718 26.55504101 27.05349483
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 27.55194866 28.05040249 28.54885632 29.04731014 29.54576397 30.0442178
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 30.54267163 31.04112545 31.53957928 32.03803311 32.53648694 33.03494076
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 33.53339459 34.03184842 34.53030225 35.02875607 35.5272099  36.02566373].
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 230111-08:37:07,839 cli ERROR:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: patensasc0085 (1). Check the HTML reports for details.
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 230111-08:37:07,839 cli ERROR:
peaceful_wozniak.1.1f50cdq7sjk0@plisskenmri.nyspi.local    | 	 Preprocessing did not finish successfully. Errors occurred while processing data from participants: patensasc0085 (1). Check the HTML reports for details.
```

### Additional information / screenshots

This also happened with a subsequent subject in the last resting state run as well.

**Comment by effigies** [comment]
This should be fixed in 22.1.1.

**Comment by effigies** [comment]
See https://github.com/nipreps/sdcflows/issues/323

**Comment by juansanchezpena** [comment]
Thanks Chris, I will use the 22.1.1 on same data and report back
________________________________
