### ISSUE TITLE
TraitError: The 's0_map' trait of a T2SMapOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_t2smap_wf/t2smap_node/S0map.nii.gz'  was specified

### ISSUE THREAD

**Issue by AndreaZHU111** [nipreps/fmriprep#2935]
### What happened?

I'm trying to run multi-echo data on fmriprep-docker (on Windows) but the propress always doesn't finish successfully. I have searched lots of solutions but it still doesn't work. How can this problems be solved?
What's more, when the fmriprep starts to run, there's a warning like:
Some nodes exceed the total amount of memory available(5.47GB)
I don't know if this has something to do with the error?

### What command did you use?

```shell
fmriprep-docker D:\bids4 D:\bids4\derivatives participant --participant-label 001 --fs-license-file D:\FClearning\license.txt -w D:\scratch
```

### What version of fMRIPrep are you running?

22.1.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node Name: fmriprep_22_1_wf.single_subject_001_wf.func_preproc_task_rest_echo_01_wf.bold_t2smap_wf.t2smap_node
File: /out/sub-001/log/20230116-123138_46c92a52-3ff3-4362-8fb5-fbe196e91682/crash-20230116-180742-root-t2smap_node-6f905bbd-a96f-4198-91c3-afd82f5f8568.txt
Working Directory: /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_t2smap_wf/t2smap_node
Inputs:
args:
echo_times: [0.0132, 0.03245, 0.0517]
environ: {}
fittype: curvefit
in_files:
mask_file:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node t2smap_node.

Cmdline:
	t2smap -d /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_0/merge/vol0000_xform-00000_clipped_merged.nii.gz /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_1/merge/vol0000_xform-00000_clipped_merged.nii.gz /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_2/merge/vol0000_xform-00000_merged.nii.gz -e 13.2 32.45 51.7 --mask /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/initial_boldref_wf/enhance_and_skullstrip_bold_wf/combine_masks/sub-001_task-rest_echo-01_bold_average_corrected_brain_mask_maths.nii.gz --fittype curvefit
Stdout:

Stderr:
	INFO     t2smap:t2smap_workflow:241 Using output directory: /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_t2smap_wf/t2smap_node
	INFO     t2smap:t2smap_workflow:251 Loading input data: ['/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_0/merge/vol0000_xform-00000_clipped_merged.nii.gz', '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_1/merge/vol0000_xform-00000_clipped_merged.nii.gz', '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_2/merge/vol0000_xform-00000_merged.nii.gz']
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 's0_map' trait of a T2SMapOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_t2smap_wf/t2smap_node/S0map.nii.gz'  was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 401, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_t2smap_wf/t2smap_node/S0map.nii.gz' for output 's0_map' of a T2SMap interface
```

**Comment by effigies** [comment]
Yes, this is definitely an out-of-memory error.

```
Stderr:
	INFO     t2smap:t2smap_workflow:241 Using output directory: /scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_t2smap_wf/t2smap_node
	INFO     t2smap:t2smap_workflow:251 Loading input data: ['/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_0/merge/vol0000_xform-00000_clipped_merged.nii.gz', '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_1/merge/vol0000_xform-00000_clipped_merged.nii.gz', '/scratch/fmriprep_22_1_wf/single_subject_001_wf/func_preproc_task_rest_echo_01_wf/bold_bold_trans_wf/_echoidx_2/merge/vol0000_xform-00000_merged.nii.gz']
	Killed
```

> Some nodes exceed the total amount of memory available(5.47GB)
> I don't know if this has something to do with the error?

You cannot run fMRIPrep on 5.5GB of RAM. You will need to use another computer with more RAM.

**Comment by AndreaZHU111** [comment]
> Yes, this is definitely an out-of-memory error.

> You cannot run fMRIPrep on 5.5GB of RAM. You will need to use another computer with more RAM.

Thanks for your reply! 
So the only solution is changing the computer? I wander if there is any chance to modify the settings and expand the memory used by fmriprep?

**Comment by effigies** [comment]
If you have more memory on your machine, then you should be able to increase the memory availability in Docker.

**Comment by AndreaZHU111** [comment]
> If you have more memory on your machine, then you should be able to increase the memory availability in Docker.

Thanks a lot for your reply! I will try it.

**Comment by tsalo** [comment]
@AndreaZHU111 if you pull the latest version of fMRIPrep, you can now control how tedana estimates T2* and S0. There's an option called `loglin` that should work better for low-memory situations.
