### ISSUE TITLE
Singularity image & FREESURFER_HOME path

### ISSUE THREAD

**Issue by muet0005** [nipreps/fmriprep#2961]
### What happened?

Hello, 

I've been using a singularity image from fmriprep 20.1.1 for a while not (I realize it's out of date and am in the process of upgrading now).  It's worked without issue. Our HPC system was recently upgraded, and now I'm running into issues. Basically, it seems the PATH variable does not have FREESURFER_HOME/bin in it (I get a FileNotFoundError for mri_convert.  If I run interactive I can confirm there is not mri_convert in the path variable.  From some posts here, I've tried mounting my home folder and mounting a few other folders, but this didn't help.  I can't tell for sure, but got a sense from other posts freesurfer should be installed in /opt, but I also do not see it there when running interactively...

The system runs a new version of red hat, but the main difference I can see is we use apptainer now instead of singularity (apptainer version 1.1.5-2.el8).

Any ideas on what I might try to troubleshoot this a bit further? 

Thanks for your time and help! 

### What command did you use?

```shell
singularity run --cleanenv ${container} --participant_label sub-123456  --fs-license-file ${license} --fs-no-reconall --anat-only --output-space T1w MNI152NLin2009cAsym:res-1 --work-dir ${workDir}--nthreads 1 --omp-nthreads 1 --notrack --verbose ${bidsDir} ${derivatives} participant

#note: singularity is a sym link to apptainer on our system...apptainer version 1.1.5-2.el8
```

### What version of fMRIPrep are you running?

20.1.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
singularity run --cleanenv ${container} --participant_label sub-123456  --fs-license-file ${license} --fs-no-reconall --anat-only --output-space T1w MNI152NLin2009cAsym:res-1 --work-dir ${workDir}--nthreads 1 --omp-nthreads 1 --notrack --verbose ${bidsDir} ${derivatives} participant
You are using fMRIPrep-20.1.1, and a newer version of fMRIPrep is available: 22.1.1.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
WARNING: Version 20.1.1 of fMRIPrep (current) has been FLAGGED
(reason: Functional outputs in standard space can be wrong depending on the original data's orientation headers - see https://github.com/nipreps/fmriprep/issues/2307).
That means some severe flaw was found in it and we strongly
discourage its usage.
230308-14:37:12,451 cli INFO:
	 Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
bids-validator@1.4.0

This dataset appears to be BIDS compatible.

        Summary:                Available Tasks:        Available Modalities: 
        3 Files, 33.51MB                                T1w                   
        1 - Subject                                                           
        1 - Session                                                           


	If you have any questions, please post on https://neurostars.org/tags/bids.

230308-14:37:19,59 nipype.workflow IMPORTANT:
	 
    Running fMRIPREP version 20.1.1:
      * BIDS dataset path: /scratch/bids
      * Participant list: ['123456'].
      * Run identifier: 20230308-143711_97a006fc-a792-4e29-9ced-a8179f6f13b5.
      * Output spaces: T1w MNI152NLin2009cAsym:res-1.
      * Pre-run FreeSurfer's SUBJECTS_DIR: /scratch/bids/derivatives/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 87, in build_workflow
    if not check_valid_fs_license():
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/utils/misc.py", line 314, in check_valid_fs_license
    proc = sp.run(_cmd, stdout=sp.PIPE, stderr=sp.STDOUT)
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 466, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 1516, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mri_convert': 'mri_convert'
```

**Comment by effigies** [comment]
Hi, thanks for following up. I confess I was a little hesitant to start digging, as it looks like you did everything right. Singularity is nice in many ways, but the variability of site configurations is a challenge to support from our side.

**Comment by muet0005** [comment]
In case it's helpful for others who come across this, 

"--no-mount hostfs" 

Solved the problem!

**Comment by effigies** [comment]
Thanks! I'm sure this will be very helpful. I'll mark it as a potential FAQ in case it comes up again.
