### ISSUE TITLE
error with --use-aroma

### ISSUE THREAD

**Issue by BRAICLab** [nipreps/fmriprep#2971]
### What happened?

Hi, 
I am pretty new with fmriprep so I apologize if it is a silly error. 
I am able to run correctly fmriprep-docker with the standard pipeline from start to end for subjects. But as soon as I add the option to conduct ica-aroma (using --use-aroma), it crashes and I am really not sure why. I list the error message below

 #################################################################
230322-22:32:34,729 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /data.
           * Participant list: ['0008117'].
           * Run identifier: 20230322-223218_f74cff2f-05ba-4383-a365-0010e7534b92.
           * Output spaces: MNI152NLin2009cAsym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 115, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 91, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 413, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/base.py", line 277, in init_func_preproc_wf
    sbref_files = layout.get(return_type="file", **sb_ents)
  File "/opt/conda/lib/python3.9/site-packages/bids/layout/layout.py", line 626, in get
    raise ValueError(msg + "If you're sure you want to impose "
ValueError: 'desc' is not a recognized entity. If you're sure you want to impose this constraint, set invalid_filters='allow'.

Again, it runs perfectly well when I don't have the --use-aroma option in my command.
Thank you very much for any suggestions.

### What command did you use?

```shell
fmriprep-docker /home/nebmeg/Desktop/BRAIC_Lab/BIDS/ /home/nebmeg/Desktop/BRAIC_Lab/BIDS/output_new --participant-label 0008117 --skip-bids-validation --ignore slicetiming --fs-license-file /usr/local/freesurfer/fs_v7_1_1/freesurfer/license.txt --use-aroma

RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=23.0.1 -it -v /usr/local/freesurfer/fs_v7_1_1/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/nebmeg/Desktop/BRAIC_Lab/BIDS:/data:ro -v /home/nebmeg/Desktop/BRAIC_Lab/BIDS/output_new:/out nipreps/fmriprep:22.1.1 /data /out participant --participant-label 0008117 --skip-bids-validation --ignore slicetiming --use-aroma
You are using fMRIPrep-22.1.1, and a newer version of fMRIPrep is available: 23.0.0.
Please check out our documentation about how and when to upgrade:
https://fmriprep.readthedocs.io/en/latest/faq.html#upgrading
--topup-max-vols input is no longer used and the flag will be removed in a future release.
230322-22:32:33,808 nipype.workflow IMPORTANT:
	 Running fMRIPrep version 22.1.1
```

### What version of fMRIPrep are you running?

22.1.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
#################################################################
230322-22:32:34,729 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /data.
           * Participant list: ['0008117'].
           * Run identifier: 20230322-223218_f74cff2f-05ba-4383-a365-0010e7534b92.
           * Output spaces: MNI152NLin2009cAsym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /out/sourcedata/freesurfer.
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 115, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 91, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 413, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/base.py", line 277, in init_func_preproc_wf
    sbref_files = layout.get(return_type="file", **sb_ents)
  File "/opt/conda/lib/python3.9/site-packages/bids/layout/layout.py", line 626, in get
    raise ValueError(msg + "If you're sure you want to impose "
ValueError: 'desc' is not a recognized entity. If you're sure you want to impose this constraint, set invalid_filters='allow'.
```

**Comment by BRAICLab** [comment]
I am confused - I don't think it is the case. My subject's data is in /home/nebmeg/Desktop/BRAIC_Lab/BIDS/sub-000xxx while I call the output directory in /home/nebmeg/Desktop/BRAIC_Lab/BIDS/output 
(I also just tried to call it derivatives as suggested, and I get the same error). 
And if it is the case, would the regular command line (without use-aroma) also not work?

**Comment by effigies** [comment]
`/home/nebmeg/Desktop/BRAIC_Lab/BIDS` is the dataset. You are placing outputs in `/home/nebmeg/Desktop/BRAIC_Lab/BIDS/output_new`. This means that after the first subject is run, there will be new files in `/home/nebmeg/Desktop/BRAIC_Lab/BIDS` that fMRIPrep will attempt to look at to understand the dataset.

> (I also just tried to call it derivatives as suggested, and I get the same error).

The problem is that there already are things in that directory. They need to be removed.

> And if it is the case, would the regular command line (without use-aroma) also not work?

Yes, that will not work, either.
