### ISSUE TITLE
Error EISDIR : no authorization to read, even though rights were set

### ISSUE THREAD

**Issue by laurec00** [nipreps/fmriprep#2972]
### What happened?

I tried running fmriprep-docker on a bids folder that has passed the bids validator online.

### What command did you use?

```shell
fmriprep-docker /mnt/d/laure/vs12/bids /mnt/d/laure/vs12/fmri-prep_test participant -w /mnt/d/laure/vs12/fmri-prep_test/work
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=23.0.1 -it -v /mnt/d/laure/vs12/bids:/data:ro -v /mnt/d/laure/vs12/fmri-prep_test:/out -v /mnt/d/laure/vs12/fmri-prep_test/work:/scratch nipreps/fmriprep:23.0.0 /data /out participant -w /scratch
bids-validator@1.8.0
```

### What version of fMRIPrep are you running?

23.0.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Unhandled rejection (
  reason: Error: EISDIR: illegal operation on a directory, read
).

Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 43, in main
    parse_args()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/parser.py", line 801, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/utils/bids.py", line 186, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmp05lzxfkq.json']' returned non-zero exit status 3.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

### Additional information / screenshots

I created a group docker with rwx rights on the bids folder and recursively to everything inside. I am running fmriprep-docker in a conda environment created for it.

**Comment by effigies** [comment]
Try adding `--shell` to your command. That will put you in a bash shell inside the environment. From there you should be able to do a little bit more digging around to understand the permissions of your system. The user should not be docker but instead `root` unless you pass the `-u` flag.

I'm guessing `/mnt/d` indicates that you're running on Windows, and I don't have much experience there to go on.

**Comment by laurec00** [comment]
Hey ! Thank you for your answer. I am still quite new to linux and docker. My computer is windows but I am using a linux VM to run the command (ubuntu) and I am using bash language directly. I tried running from root and I got the same error. Permissions are as follow:
root@CD-BW0Z1L3:/home/laure# ls -l /mnt/d/laure/vs12/bids
-rwxrwxrwx for each file for user laure and group laure
drwxrwxrwx for each directory for user laure and group laure

Should root be the user indicated ?

**Comment by laurec00** [comment]
The problem was from bids validator in the end, when i used the option to pass it then it started to work. Weird since I had check the folder on the website and everything was good, but at least it's settled ! Thank you again for your help
