### ISSUE TITLE
installation error on macOS 13 with homebrew python 3.11

### ISSUE THREAD

**Issue by raamana** [nipreps/fmriprep#2976]
### What happened?

FYI: Installation error on macOS 13 (intel processor) with Homebrew python 3.11

### What command did you use?

```shell
$ 11:59:22 Quark-2 tests >>  pip install fmriprep
Collecting fmriprep
  Downloading fmriprep-23.0.1-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 kB 3.3 MB/s eta 0:00:00
Collecting apscheduler
  Downloading APScheduler-3.10.1-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 1.7 MB/s eta 0:00:00
Collecting codecarbon
  Downloading codecarbon-2.1.4-py3-none-any.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.9/174.9 kB 5.6 MB/s eta 0:00:00
Collecting looseversion
  Downloading looseversion-1.1.2-py3-none-any.whl (8.1 kB)
Requirement already satisfied: nibabel>=4.0.1 in /usr/local/lib/python3.11/site-packages (from fmriprep) (5.0.1)
Collecting nipype>=1.8.5
  Downloading nipype-1.8.5-py3-none-any.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 24.3 MB/s eta 0:00:00
Collecting nitime
  Downloading nitime-0.9.tar.gz (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 33.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting nitransforms>=21.0.0
  Downloading nitransforms-22.0.0-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.7/54.7 kB 1.8 MB/s eta 0:00:00
Collecting niworkflows~=1.7.8
  Downloading niworkflows-1.7.8.tar.gz (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.3/177.3 kB 6.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running dist_info
      creating /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info
      writing /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/entry_points.txt
      writing requirements to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/requires.txt
      writing top-level names to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/top_level.txt
      writing manifest file '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/SOURCES.txt'
      listing git files failed - pretending there aren't any
      reading manifest file '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching 'conftest.py' found under directory 'niworkflows/'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/SOURCES.txt'
      creating '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows-1.7.8.dist-info'
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 105, in run
          bdist_wheel.egg2dist(egg_info_dir, self.dist_info_dir)
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 414, in egg2dist
          shutil.copy(license, os.path.join(self.distinfo_dir, license_filename))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen posixpath>", line 76, in join
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```
```


### What version of fMRIPrep are you running?

Not yet

### How are you running fMRIPrep?

Other

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
$ 11:59:22 Quark-2 tests >>  pip install fmriprep
Collecting fmriprep
  Downloading fmriprep-23.0.1-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.0/216.0 kB 3.3 MB/s eta 0:00:00
Collecting apscheduler
  Downloading APScheduler-3.10.1-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 1.7 MB/s eta 0:00:00
Collecting codecarbon
  Downloading codecarbon-2.1.4-py3-none-any.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.9/174.9 kB 5.6 MB/s eta 0:00:00
Collecting looseversion
  Downloading looseversion-1.1.2-py3-none-any.whl (8.1 kB)
Requirement already satisfied: nibabel>=4.0.1 in /usr/local/lib/python3.11/site-packages (from fmriprep) (5.0.1)
Collecting nipype>=1.8.5
  Downloading nipype-1.8.5-py3-none-any.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 24.3 MB/s eta 0:00:00
Collecting nitime
  Downloading nitime-0.9.tar.gz (6.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 33.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting nitransforms>=21.0.0
  Downloading nitransforms-22.0.0-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.7/54.7 kB 1.8 MB/s eta 0:00:00
Collecting niworkflows~=1.7.8
  Downloading niworkflows-1.7.8.tar.gz (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.3/177.3 kB 6.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running dist_info
      creating /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info
      writing /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/dependency_links.txt
      writing entry points to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/entry_points.txt
      writing requirements to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/requires.txt
      writing top-level names to /private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/top_level.txt
      writing manifest file '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/SOURCES.txt'
      listing git files failed - pretending there aren't any
      reading manifest file '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching 'conftest.py' found under directory 'niworkflows/'
      adding license file 'LICENSE'
      writing manifest file '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows.egg-info/SOURCES.txt'
      creating '/private/var/folders/f3/vw4cz6js4zn8fgktmxrfmjsc0000gn/T/pip-modern-metadata-xl_jv8d4/niworkflows-1.7.8.dist-info'
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/dist_info.py", line 105, in run
          bdist_wheel.egg2dist(egg_info_dir, self.dist_info_dir)
        File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 414, in egg2dist
          shutil.copy(license, os.path.join(self.distinfo_dir, license_filename))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen posixpath>", line 76, in join
      TypeError: expected str, bytes or os.PathLike object, not NoneType
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```
```


### Additional information / screenshots

_No response_

**Comment by raamana** [comment]
I was trying to check if I can get `fmriprep.__version__` after importing - see [here](https://neurostars.org/t/python-package-managers-pros-and-cons/25235/16?u=raamana)

**Comment by effigies** [comment]
Huh. Looks like we don't publish wheels of niworkflows. And we haven't updated the build system in a while.
