### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory (mri_robust_register command)

### ISSUE THREAD

**Issue by junxiatree** [nipreps/fmriprep#2977]
### What happened?

When I ran 'mri_robust_register', there is an error:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/work/fmriprep_23_0_wf/single_subject_994509xxx_wf/anat_preproc_wf/surface_recon_wf/fsnative2t1w_xfm/T1_robustreg.lta'
Do you have any suggestions?

![Screenshot 2023-03-30 at 11 19 28](https://user-images.githubusercontent.com/75524484/228711211-cf062168-9f64-4fed-9cf4-9fb440585a33.png)

### What command did you use?

```shell
fmriprep-docker
RUNNING: run --rm -e DOCKER_VERSION_8395080871=20.10.23 -it -v /media/xxxx-data/Localizer_BIDS/code/license.txt:/opt/freesurfer/license.txt:ro -v /media/xxxx-data/BIDS/data_rs/rs:/data:ro -v /media/xxx-data/BIDS/data_rs/derivatives:/out nipreps/fmriprep:23.0.0 /data /out participant --participant-label 994509xxx --skip-bids-validation --md-only-boilerplate
```

### What version of fMRIPrep are you running?

23.0.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fsnative2t1w_xfm.

Cmdline:
        mri_robust_register --satit --iscale --lta /tmp/work/fmriprep_23_0_wf/single_subject_994509xxx_wf/anat_preproc_wf/surface_recon_wf/fsnative2t1w_xfm/T1_robustreg.lta --mov /out/sourcedata/freesurfer/sub-994509xxx/mri/T1.mgz --dst /data/sub-994509xxx/ses-01/anat/sub-994509xxx_ses-01_T1w.nii
Stdout:
        7.3.2

        --satit: Will iterate with different SAT to ensure outliers below wlimit!
        --iscale: Enabling intensity scaling!
        --lta: Output transform as /tmp/work/fmriprep_23_0_wf/single_subject_994509xxx_wf/anat_preproc_wf/surface_recon_wf/fsnative2t1w_xfm/T1_robustreg.lta .
        --mov: Using /out/sourcedata/freesurfer/sub-994509xxx/mri/T1.mgz as movable/source volume.
        --dst: Using /data/sub-994509862/ses-01/anat/sub-994509xxx_ses-01_T1w.nii as target volume.

        reading source '/out/sourcedata/freesurfer/sub-994509xxx/mri/T1.mgz'...
        reading target '/data/sub-994509862/ses-01/anat/sub-994509xxx_ses-01_T1w.nii'...
        INFO: This is an unsigined short.

        Registration::setSourceAndTarget(MRI s, MRI t, keeptype = TRUE )
           Type Source : 0  Type Target : 10  ensure both FLOAT (3)
           Reordering axes in mov to better fit dst... ( -1 -3 2 )
         Determinant after swap : 1
           Mov: (0.7, 0.7, 0.7)mm  and dim (320, 320, 320)
           Dst: (0.7, 0.7, 0.7)mm  and dim (290, 320, 256)
           Asserting both images: 0.7mm isotropic
            - reslicing Mov ...
               -- changing data type from 0 to 3 (noscale = 0)...
            - reslicing Dst ...
               -- changing data type from 10 to 3 (noscale = 0)...
        MRIchangeType: Building histogram 0 24198 1000, flo=0, fhi=0.999, dest_type=3
               -- Original : (0.7, 0.7, 0.7)mm and (290, 320, 256) voxels.
               -- Resampled: (0.7, 0.7, 0.7)mm and (320, 320, 320) voxels.
               -- Reslicing using cubic bspline
        MRItoBSpline degree 3


         Registration::findSaturation
           - computing centroids
Stderr:
        makeIsotropic WARNING: not different enough, won't reslice!
        CostFunctions::centroid is NAN (empty image? n = 0 )
Traceback:
        Traceback (most recent call last):
          File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 399, in run
            runtime = self._post_run_hook(runtime)
          File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/freesurfer.py", line 248, in _post_run_hook
            fix_lta_length(lta_file)
          File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/freesurfer.py", line 399, in fix_lta_length
            lines = Path(lta_file).read_text().splitlines(keepends=True)
          File "/opt/conda/lib/python3.9/pathlib.py", line 1266, in read_text
            with self.open(mode='r', encoding=encoding, errors=errors) as f:
          File "/opt/conda/lib/python3.9/pathlib.py", line 1252, in open
            return io.open(self, mode, buffering, encoding, errors, newline,
          File "/opt/conda/lib/python3.9/pathlib.py", line 1120, in _opener
            return self._accessor.open(self, flags, mode)
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/work/fmriprep_23_0_wf/single_subject_994509862_wf/anat_preproc_wf/surface_recon_wf/fsnative2t1w_xfm/T1_robustreg.lta'
```

**Comment by effigies** [comment]
I'm sorry, I missed this.

`        CostFunctions::centroid is NAN (empty image? n = 0 )` would indicate that there's some issue with the input images.

Looking at `mri_robust_register --satit --iscale --lta /tmp/work/fmriprep_23_0_wf/single_subject_994509xxx_wf/anat_preproc_wf/surface_recon_wf/fsnative2t1w_xfm/T1_robustreg.lta --mov /out/sourcedata/freesurfer/sub-994509xxx/mri/T1.mgz --dst /data/sub-994509xxx/ses-01/anat/sub-994509xxx_ses-01_T1w.nii`. I would check what `/out/sourcedata/freesurfer/sub-994509xxx/mri/T1.mgz` and `/data/sub-994509xxx/ses-01/anat/sub-994509xxx_ses-01_T1w.nii` look like, and see if you can run `mri_robust_register` outside of fMRIPrep.

Please retry with 23.2.0a1, and if this is still an issue, reopen.
