### ISSUE TITLE
ConnectionResetError, no additional info with verbose

### ISSUE THREAD

**Issue by hugofluhr** [nipreps/fmriprep#2983]
### What happened?

I am trying to run fmriprep:23.0.1 on my Linux Ubuntu 16.04 machine using Docker and am getting what seems to be a multiprocessing error at the very beginning of fmriprep. When trying to get more info by using `-v`, `-vv`, `-vvvv`, no additional info is printed.

### What command did you use?

```shell
$ fmriprep-docker /media/localadmin/DATA/hugo/70subjects /media/localadmin/DATA/hugo/70subjects_outputs participant --participant-label sub-CHUVL048 --skip_bids_validation --bids-database-dir /media/localadmin/DATA/hugo/70subjects_outputs/.bids-db --fs-license-file /home/localadmin/Installs/freesurfer/license.txt --nprocs 1 --omp-nthreads 1 -vvvv
```

### What version of fMRIPrep are you running?

23.0.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.7 -it -v /home/localadmin/Installs/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /media/localadmin/DATA/hugo/70subjects:/data:ro -v /media/localadmin/DATA/hugo/70subjects_outputs:/out -v /media/localadmin/DATA/hugo/70subjects_outputs/.bids-db:/tmp/bids_db nipreps/fmriprep:23.0.1 /data /out participant --participant-label sub-CHUVL048 --skip_bids_validation --nprocs 1 --omp-nthreads 1 -vvvv --bids-database-dir /tmp/bids_db
230406-15:09:06,318 cli INFO:
	 Telemetry system to collect crashes and errors is enabled - thanks for your feedback!. Use option ``--notrack`` to opt out.
Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 93, in main
    retval = mgr.dict()
  File "/opt/conda/lib/python3.9/multiprocessing/managers.py", line 715, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/opt/conda/lib/python3.9/multiprocessing/managers.py", line 598, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 513, in Client
    answer_challenge(c, authkey)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 757, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

**Comment by mgxd** [comment]
Is this happening consistently? Perhaps you try running with `--debug pdb` and see if you still run into the problem.

**Comment by HEO-K** [comment]
I'm having the exactly same issue and it happen consistently.
``` bash
docker run -ti --rm -v /usr/local/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v ${bids_path}:/data:ro -v ${bids_path}/derivatives:/out nipreps/fmriprep:23.0.1 /data /out participant --participant-label ${sub} --skip_bids_validation --output-spaces anat:res-native
 Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 93, in main
    retval = mgr.dict()
  File "/opt/conda/lib/python3.9/multiprocessing/managers.py", line 715, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/opt/conda/lib/python3.9/multiprocessing/managers.py", line 598, in _create
    conn = self._Client(self._address, authkey=self._authkey)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 513, in Client
    answer_challenge(c, authkey)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 757, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

However, the previous version(21.0.2) works fine without any problems.

My system info (from `docker info`):
``` bash
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 376.9GiB
```

**Comment by mgxd** [comment]
@HEO-K thanks for the report - could you try running with `--debug pdb`?

**Comment by HEO-K** [comment]
@mgxd

**Comment by mgxd** [comment]
Interesting - this shows that you are hitting your thread threshold. Are you using an older version of Docker? It looks like you may be hitting this: https://stackoverflow.com/questions/70087344/python-in-docker-runtimeerror-cant-start-new-thread

**Comment by HEO-K** [comment]
@mgxd 
Version is 19.03.03 of server, where I got error. On the other hands, on my local computer, Docker 20.10.23, fmriprep is working very well. I can't update the program on the server at will, so I can't check this is because of version, but I think you're probably right. If the problem still persists after update of Docker on the server, I will comment or reopen new issue. Thanks!
