### ISSUE TITLE
Error in get_img_orientation during workflow setup in 20.2.7 but not in 20.2.0

### ISSUE THREAD

**Issue by ins0mniac2** [nipreps/fmriprep#2993]
### What happened?

Got an error during workflow setup in get_img_orientation function on a dataset in 20.2.7. The same dataset processed without this error in 20.2.0. Can't see any obvious problem with the image header.

### What command did you use?

```shell
singularity run --cleanenv $SINGULARITY_IMAGE \
    $BIDS $OUTFOLDER \
    participant \
    --participant-label $SUBJECTID \
    --nthreads $NTHREADS \
    --omp-nthreads $OMPTHREADS \
    --fs-license-file $FS_LICENSE \
    --work-dir $WORKDIR \
    --longitudinal \
    --cifti-output \
    --notrack \
    --no-submm-recon \
    --use-aroma \
    --skip_bids_validation \
    --write-graph \
    --force-syn \
    --low-mem \
    -vvv \
    --output-spaces \
      MNI152NLin2009cAsym:res-02 \
      HDTRACK60v1:res-02 \
      OASIS30ANTs:res-02 \
      fsaverage \
      fsaverage5 \
      T1w \
      func
```

### What version of fMRIPrep are you running?

20.2.7

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
====
230418-21:48:02,681 nipype.workflow INFO:
         No single-band-reference found for sub-XX_ses-06_task-taskmotor_run-01_bold.nii.gz.
230418-21:48:03,245 nipype.workflow IMPORTANT:
         BOLD series will be slice-timing corrected to an offset of 1.48s.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 172, in init_func_preproc_wf
    ref_orientation = get_img_orientation(ref_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 982, in get_img_orientation
    return ''.join(nb.aff2axcodes(img.affine))
TypeError: sequence item 2: expected str instance, NoneType found
=====
```

**Comment by ins0mniac2** [comment]
b"\\\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00r9\x04\x"

**Comment by effigies** [comment]
That seems to have gotten truncated...

**Comment by ins0mniac2** [comment]
I was going to say -- this doesn't make sense. Let me redirect the output.

**Comment by effigies** [comment]
Okay. I had to escape the first character, but then I got:

```
In [31]: hdr.get_sform(coded=True)
Out[31]: 
(array([[ -3.3125    ,  -0.        ,   0.        , 106.43405151],
        [  0.        ,   3.29311061,   0.        , -85.32108307],
        [  0.        ,   0.3578808 ,   0.        , -67.8843689 ],
        [  0.        ,   0.        ,   0.        ,   1.        ]]),
 1)

In [32]: hdr.get_qform(coded=True)
Out[32]: 
(array([[ -3.3125    ,   0.        ,   0.        , 106.43405151],
        [  0.        ,   3.3076491 ,  -0.1785266 , -85.32108307],
        [  0.        ,   0.17920284,   3.29516736, -67.8843689 ],
        [  0.        ,   0.        ,   0.        ,   1.        ]]),
 1)
```

You have a corrupted sform that's coded non-zero. The simplest thing would be to zero-out the `sform_code` and let fMRIPrep copy the qform to the sform for you.

**Comment by ins0mniac2** [comment]
Thanks @effigies ! That looks like a 0 z-resolution! Do you suggest something like

`img.header.set_sform(affine, 0)` 

no matter what affine is, fmriprep will use the qform ? Related question: the header hasn't been altered by anything after being extracted by dcm2niix. What could cause this ?

**Comment by effigies** [comment]
You can also use `fsledithd` to edit the header.

**Comment by ins0mniac2** [comment]
Looks like further header repair may be needed:
`Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 82, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 304, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 148, in init_func_preproc_wf
    bold_file[0] if isinstance(bold_file, (list, tuple)) else bold_file
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/loadsave.py", line 52, in load
    img = image_klass.from_filename(filename, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/dataobj_images.py", line 489, in from_filename
    keep_file_open=keep_file_open)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/analyze.py", line 980, in from_file_map
    img._affine = header.get_best_affine()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/nifti1.py", line 732, in get_best_affine
    return self.get_qform()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/nifti1.py", line 915, in get_qform
    quat = self.get_qform_quaternion()
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/nifti1.py", line 890, in get_qform_quaternion
    return fillpositive(bcd, self.quaternion_threshold)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nibabel/quaternions.py", line 99, in fillpositive
    raise ValueError(f'w2 should be positive, but is {w2:e}')
ValueError: w2 should be positive, but is -4.000510e-07
`

**Comment by effigies** [comment]
That's surprising. We were able to get the qform before. Does it work if you use fsledithd to set the code instead of nibabel?

**Comment by ins0mniac2** [comment]
I did use fslhd to just change sform_code

**Comment by ins0mniac2** [comment]
So it turns out when I use nibabel to set `sform_code` , it does work, and the fmriprep run successfully finished. Thanks a lot @effigies for your guidance.
