### ISSUE TITLE
Nibabel deprecation rasing when importing from nipype.interfaces.nipy.base

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#3003]
### What happened?

```
Process Process-2:
Traceback (most recent call last):
  File "/home/oesteban/.miniconda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/oesteban/.miniconda/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/oesteban/workspace/fmriprep/fmriprep/cli/workflow.py", line 115, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/data/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 92, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/data/home/oesteban/workspace/fmriprep/fmriprep/workflows/base.py", line 306, in init_single_subject_wf
    anat_preproc_wf = init_anat_preproc_wf(
  File "/data/home/oesteban/workspace/smriprep/smriprep/workflows/anatomical.py", line 386, in init_anat_preproc_wf
    brain_extraction_wf = init_brain_extraction_wf(
  File "/data/home/oesteban/workspace/niworkflows/niworkflows/anat/ants.py", line 463, in init_brain_extraction_wf
    atropos_wf = init_atropos_wf(
  File "/data/home/oesteban/workspace/niworkflows/niworkflows/anat/ants.py", line 846, in init_atropos_wf
    from nipype.algorithms.metrics import FuzzyOverlap
  File "/data/home/oesteban/workspace/nipype/nipype/algorithms/metrics.py", line 26, in <module>
    from ..interfaces.nipy.base import NipyBaseInterface
  File "/data/home/oesteban/workspace/nipype/nipype/interfaces/nipy/__init__.py", line 3, in <module>
    from .model import FitGLM, EstimateContrast
  File "/data/home/oesteban/workspace/nipype/nipype/interfaces/nipy/model.py", line 4, in <module>
    from .base import NipyBaseInterface
  File "/data/home/oesteban/workspace/nipype/nipype/interfaces/nipy/base.py", line 14, in <module>
    package_check("nipy")
  File "/data/home/oesteban/workspace/nipype/nipype/utils/misc.py", line 168, in package_check
    mod = __import__(pkg_name)
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nipy/__init__.py", line 32, in <module>
    from nipy.io.api import load_image, save_image, as_image
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nipy/io/api.py", line 3, in <module>
    from .files import load as load_image, save as save_image, as_image
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nipy/io/files.py", line 22, in <module>
    from ..core.image.image import is_image
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nipy/core/image/__init__.py", line 13, in <module>
    from . import image
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nipy/core/image/image.py", line 34, in <module>
    class Image(object):
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nipy/core/image/image.py", line 84, in Image
    def shape(self):
  File "/home/oesteban/.miniconda/lib/python3.9/site-packages/nibabel/deprecator.py", line 185, in deprecated_func
    raise error_class(message)
nibabel.deprecator.ExpiredDeprecationError: setattr_on_read has been renamed to auto_attr. Please use nibabel.onetime.auto_attr

* deprecated from version: 3.2
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 5.0
```

### What command did you use?

```shell
bare metal.
```

### What version of fMRIPrep are you running?

master

### How are you running fMRIPrep?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
Yeah, we can't install nipy in the same environment as nipype anymore. Nothing to do here.
