### ISSUE TITLE
autorecon1 "ERROR: OS is missing bc (binary calculator) utility"

### ISSUE THREAD

**Issue by madisoth** [nipreps/fmriprep#3015]
### What happened?

autorecon1 failed with the log output below; looks like `bc` is no longer in the Docker image as of #2982. 

### What command did you use?

```shell
fmriprep_goodvox-patch_05192023a.sif \
  --fs-license-file /license.txt \
  --resource-monitor \
  --project-goodvoxels \
  --omp-nthreads 3 \
  --cifti-output 91k \
  -vv \
  -w /wd \
  /bids_dir /output_dir participant
```

### What version of fMRIPrep are you running?

PR #3011 (goodvox-patch); also tried unstable (commit 5d36a6f7273b898aa21a6698ae7e0155377fc8f4 from Apr 26)

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node Name: fmriprep_23_1_wf.single_subject_MSC02_wf.anat_preproc_wf.surface_recon_wf.autorecon1
File: /output_dir/sub-MSC02/log/20230519-195321_67bf68d2-7fd1-4248-9e2c-ec593e33429f/crash-20230519-195833-tmadison-autorecon1-05fe5340-9c6a-4b19-9242-a6c269900ae5.txt
Working Directory: /wd/fmriprep_23_1_wf/single_subject_MSC02_wf/anat_preproc_wf/surface_recon_wf/autorecon1
Inputs:
FLAIR_file:
T1_files:
T2_file:
args:
big_ventricles:
brainstem:
directive: autorecon1
environ: {}
expert:
flags:
hemi:
hippocampal_subfields_T1:
hippocampal_subfields_T2:
hires:
mprage:
mri_aparc2aseg:
mri_ca_label:
mri_ca_normalize:
mri_ca_register:
mri_edit_wm_with_aseg:
mri_em_register:
mri_fill:
mri_mask:
mri_normalize:
mri_pretess:
mri_remove_neck:
mri_segment:
mri_segstats:
mri_tessellate:
mri_watershed:
mris_anatomical_stats:
mris_ca_label:
mris_fix_topology:
mris_inflate:
mris_make_surfaces:
mris_register:
mris_smooth:
mris_sphere:
mris_surf2vol:
mrisp_paint:
openmp: 3
parallel:
steps:
subject_id: recon_all
subjects_dir:
talairach:
use_FLAIR:
use_T2:
xopts:
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node autorecon1.

Cmdline:
	recon-all -autorecon1 -i /wd/fmriprep_23_1_wf/single_subject_MSC02_wf/anat_preproc_wf/anat_validate/sub-MSC02_ses-res03to06_T1w_noise_corrected_valid.nii.gz -T2 /bids_dir/sub-MSC02/ses-res03to06/anat/sub-MSC02_ses-res03to06_T2w.nii.gz -noskullstrip -noT2pial -noFLAIRpial -hires -openmp 3 -subjid sub-MSC02 -sd /output_dir/sourcedata/freesurfer -expert /wd/fmriprep_23_1_wf/single_subject_MSC02_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts
Stdout:
	INFO: hi-res volumes are conformed to the min voxel size
	fs-check-version --s sub-MSC02 --o /tmp/tmp.eXDdCX
	Fri May 19 19:58:31 CDT 2023

	setenv SUBJECTS_DIR /output_dir/sourcedata/freesurfer
	cd /wd/fmriprep_23_1_wf/single_subject_MSC02_wf/anat_preproc_wf/surface_recon_wf/autorecon1
	/opt/freesurfer/bin/fs-check-version --s sub-MSC02 --o /tmp/tmp.eXDdCX
	-rwxrwxr-x. 1 root root 18565 Aug  4  2022 /opt/freesurfer/bin/fs-check-version

	freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
	$Id$
	Linux acl52 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
	pid 4150941
	Current FS Version freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
	Subject does not have a bstampfile, copying /opt/freesurfer/build-stamp.txt
	Subject FS Version: freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
	No constraints on version because REQ=UnSet and FsVerFile=NotThere
	#@#% fs-check-version match = 1
	fs-check-version Done
	INFO: SUBJECTS_DIR is /output_dir/sourcedata/freesurfer
	Actual FREESURFER_HOME /opt/freesurfer
	Linux acl52 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
	ERROR: OS is missing bc (binary calculator) utility
Stderr:

Traceback:
	RuntimeError: subprocess exited with code 1.
```

**Comment by effigies** [comment]
Good timing. I was just upgrading ANTs, so we'll get this fixed up in #3016.
