### ISSUE TITLE
 reason: TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by YasmineMH1997** [nipreps/fmriprep#3024]
### What happened?

The Bids version of my dataset is 1.0.1. I am not sure if that is creating conflicts. This the error I am getting. 
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.2 -it -v C:\Users\yasmi\desktop\Oasis\license.txt:/opt/freesurfer/license.txt:ro -v C:\Users\yasmi\desktop\Oasis\Bids:/data:ro -v C:\Users\yasmi\desktop\Oasis\Bids\derivatives:/out nipreps/fmriprep:23.0.2 /data /out participant
bids-validator@1.8.0

Unhandled rejection (
  reason: TypeError: Cannot read properties of undefined (reading 'split')
    at Minimatch.match (/opt/conda/lib/node_modules/bids-validator/node_modules/minimatch/minimatch.js:717:9)
    at minimatch (/opt/conda/lib/node_modules/bids-validator/node_modules/minimatch/minimatch.js:107:42)
    at Object.ignoredFile (/opt/conda/lib/node_modules/bids-validator/utils/config.js:11:13)
    at Function.format (/opt/conda/lib/node_modules/bids-validator/utils/issues/index.js:65:16)
    at Function.exceptionHandler (/opt/conda/lib/node_modules/bids-validator/utils/issues/index.js:191:25)
    at /opt/conda/lib/node_modules/bids-validator/validators/bids/fullTest.js:225:35
).

Traceback (most recent call last):
  File "/opt/conda/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/run.py", line 43, in main
    parse_args()
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/parser.py", line 801, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/lib/python3.9/site-packages/fmriprep/utils/bids.py", line 186, in validate_input_dir 
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmp7dtryovt.json']' returned non-zero exit status 3.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues

### What command did you use?

```shell
fmriprep-docker <your bids-folder> <your output-folder>
```

### What version of fMRIPrep are you running?

should be 20.1.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
fmriprep --version
Traceback (most recent call last):
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code     
    exec(code, run_globals)
  File "C:\Users\yasmi\AppData\Roaming\Python\Python310\Scripts\fmriprep.exe\__main__.py", line 4, in <module>
  File "C:\Users\yasmi\AppData\Roaming\Python\Python310\site-packages\fmriprep\cli\run.py", line 4, in <module>
    from .. import config
  File "C:\Users\yasmi\AppData\Roaming\Python\Python310\site-packages\fmriprep\config.py", line 74, in <module>
    set_start_method('forkserver')
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 251, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'forkserver'
```

### Additional information / screenshots

 fmriprep --version
Traceback (most recent call last):
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code     
    exec(code, run_globals)
  File "C:\Users\yasmi\AppData\Roaming\Python\Python310\Scripts\fmriprep.exe\__main__.py", line 4, in <module>
  File "C:\Users\yasmi\AppData\Roaming\Python\Python310\site-packages\fmriprep\cli\run.py", line 4, in <module>
    from .. import config
  File "C:\Users\yasmi\AppData\Roaming\Python\Python310\site-packages\fmriprep\config.py", line 74, in <module>
    set_start_method('forkserver')
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 251, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
  File "C:\Users\yasmi\AppData\Local\Programs\Python\Python310\lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'forkserver'

**Comment by effigies** [comment]
This seems like a validator issue. Are you able to reproduce the issue at https://bids-standard.github.io/bids-validator/?

**Comment by YasmineMH1997** [comment]
Yes it gives the same errors

**Comment by effigies** [comment]
Apologies for not following up. We can't support validator issues here. Please open an issue on https://github.com/bids-standard/bids-validator.
