### ISSUE TITLE
FileNotFoundError: 'aparc_a2009s_stats' of a ReconAll interface

### ISSUE THREAD

**Issue by celprov** [nipreps/fmriprep#3083]
### What happened?

Hi,
I'm trying to run fMRIPrep on our deep sampling dataset, which contains 15 sessions on a single subject.
However, fMRIPrep fails with the following error (see the full error log below):

> Traceback (most recent call last):
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
>             outputs = self.aggregate_outputs(runtime)
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
>             raise FileNotFoundError(msg)
>         FileNotFoundError: No such file or directory '['/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/lh.aparc.a2009s.stats', '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/rh.aparc.a2009s.stats']' for output 'aparc_a2009s_stats' of a ReconAll interface

Seems to be the same error as #1685

Something strange I noticed is that I run `sub-pilot/ses-13`, but the files that triggered the failure is the T2w image of `sub-pilot/ses-6`; why does it run session 6 when I use `--bids-filter-file` to run only one session?

Btw the same command 

> `recon-all -autorecon1 -T2 /data/sub-pilot/ses-06/anat/sub-pilot_ses-06_T2w.nii.gz -noskullstrip -noT2pial -noFLAIRpial -cw256 -hires -openmp 2 -subjid sub-pilot -sd /out/fmriprep-23.1.4/sourcedata/freesurfer -expert /work/fmriprep_23_1_wf/single_subject_pilot_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts`

was launched while trying to run `sub-pilot/ses-12` and also resulted in a similar issue

> The 'rawavg' trait of a ReconAllOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/mri/rawavg.mgz' <class 'str'> was specified

Not sure where it comes from, but here are some particularities about how I call fMRIPrep:
- I use `--bids-filter-file` to run only one session from our single subject.
- I downloaded the required template from templateflow in advance and mount it. Because I launched several sessions of the same subject in parallel using SLURM arrays, I had to do that to avoid file corruption errors because several processes were working on the same file at the same time.

cc/ @oesteban @acionca

### What command did you use?

```shell
#!/bin/bash

#SBATCH --partition=russpold
#SBATCH --mem=50GB
#SBATCH --cpus-per-task=4
#SBATCH --time=20:00:00
#SBATCH --job-name=fmriprep
#SBATCH --error="slurm-%A_%a.err"

# Submit a Single Subject through fMRIPrep

DATADIR="/oak/stanford/groups/russpold/inprocess/cprovins/hcph-pilot"
SUBJ="sub-pilot"
SES="ses-13"
STUDY=`basename $DATADIR`

echo "Processing: $SUBJ"

IMG="/oak/stanford/groups/russpold/users/cprovins/singularity_images/fmriprep-23.1.4.simg"

WORKDIR="${L_SCRATCH}/fmriprep/${STUDY}/${SES}"
mkdir -p ${WORKDIR}
OUTDIR="${DATADIR}/derivatives"
mkdir -p $OUTDIR

PATCHES=""

BINDINGS="-B $DATADIR/inputs:/data:ro \
-B ${WORKDIR}:/work \
-B ${OUTDIR}:/out \
-B `pwd`/license.txt:/opt/freesurfer/license.txt \
-B `pwd`/filter_file_$SES.json:/filter_file_$SES.json \
-B ${HOME}/.cache/templateflow/tpl-MNI152NLin6Asym/:${HOME}/.cache/templateflow/tpl-MNI152NLin6Asym/
$PATCHES"

FMRIPREP_CMD="/data /out/fmriprep-23.1.4 participant \
-w /work --bids-filter-file /filter_file_${SES}.json --skip_bids_validation \
--nprocs 4 --mem 50G --omp-nthreads 2 \
-vv"

#Create json file to filter one session only
echo '{"bold": {"datatype": "func", "session": "'${SES: -2}'", "suffix": "bold"}}' > filter_file_${SES}.json

SING_CMD="singularity run -e $BINDINGS $IMG $FMRIPREP_CMD"
echo $SING_CMD
$SING_CMD
echo "Completed with return code: $?"
```

### What version of fMRIPrep are you running?

23.1.4

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
230831-21:27:06,604 nipype.workflow ERROR:
         could not run node: fmriprep_23_1_wf.single_subject_pilot_wf.anat_preproc_wf.surface_recon_wf.autorecon1
230831-21:27:06,608 nipype.workflow INFO:
         crashfile: /out/fmriprep-23.1.4/sub-pilot/log/20230831-162210_8dfe087d-2c69-440e-91ed-1ed8d30e300a/crash-20230831-210116-cprovins-autorecon1-fee3754a-01c9-400b-87f6-d2c1531e8787.txt
230831-21:27:06,609 nipype.workflow INFO:
         ***********************************
230831-21:27:06,706 nipype.workflow CRITICAL:
         fMRIPrep failed: Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node autorecon1.

Cmdline:
        recon-all -autorecon1 -T2 /data/sub-pilot/ses-06/anat/sub-pilot_ses-06_T2w.nii.gz -noskullstrip -noT2pial -noFLAIRpial -cw256 -hires -openmp 2 -subjid sub-pilot -sd /out/fmriprep-23.1.4/sourcedata/freesurfer -expert /work/fmriprep_23_1_wf/single_subject_pilot_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts 
Stdout:
        INFO: hi-res volumes are conformed to the min voxel size
        fs-check-version --s sub-pilot --o /tmp/tmp.DIL0Yt
        Thu Aug 31 21:01:14 PDT 2023

        setenv SUBJECTS_DIR /out/fmriprep-23.1.4/sourcedata/freesurfer
        cd /work/fmriprep_23_1_wf/single_subject_pilot_wf/anat_preproc_wf/surface_recon_wf/autorecon1
        /opt/freesurfer/bin/fs-check-version --s sub-pilot --o /tmp/tmp.DIL0Yt
        -rwxrwxr-x 1 cprovins russpold 18565 Aug  3  2022 /opt/freesurfer/bin/fs-check-version

        freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
        $Id$
        Linux sh03-06n05.int 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
        pid 31112
        Current FS Version freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
        Subject does not have a bstampfile, copying /opt/freesurfer/build-stamp.txt
        Subject FS Version: 
        No constraints on version because REQ=UnSet and FsVerFile=NotThere
        #@#% fs-check-version match = 1
        fs-check-version Done
        Linux sh03-06n05.int 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

        recon-all -s sub-pilot exited with ERRORS at Thu Aug 31 21:01:14 PDT 2023

        For more details, see the log file 
        To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Stderr:
        cp: not writing through dangling symlink '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/scripts/build-stamp.txt'
        cat: /out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/scripts/build-stamp.txt: No such file or directory
        cp: not writing through dangling symlink '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/scripts/expert-options'
Traceback:
        Traceback (most recent call last):
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
            setattr(outputs, key, val)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 424, in validate
            value = super(MultiObject, self).validate(objekt, name, newvalue)
File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_types.py", line 2699, in validate
            return TraitListObject(self, object, name, value)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 582, in __init__
            super().__init__(
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 213, in __init__
            super().__init__(self.item_validator(item) for item in iterable)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
            super().__init__(self.item_validator(item) for item in iterable)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 865, in _item_validator
            return trait_validator(object, self.name, value)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
            value = super(File, self).validate(objekt, name, value, return_pathlike=True)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
            self.error(objekt, name, str(value))
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
            raise TraitError(
        traits.trait_errors.TraitError: Each element of the 'aparc_a2009s_stats' trait of a ReconAllOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/lh.aparc.a2009s.stats' <class 'str'> was specified.

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
            outputs = self.aggregate_outputs(runtime)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
            raise FileNotFoundError(msg)
        FileNotFoundError: No such file or directory '['/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/lh.aparc.a2009s.stats', '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/rh.aparc.a2009s.stats']' for output 'aparc_a2009s_stats' of a ReconAll interface


Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/run.py", line 162, in main
    fmriprep_wf.run(**config.nipype.get_plugin())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/base.py", line 224, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node autorecon1.

Cmdline:
        recon-all -autorecon1 -T2 /data/sub-pilot/ses-06/anat/sub-pilot_ses-06_T2w.nii.gz -noskullstrip -noT2pial -noFLAIRpial -cw256 -hires -openmp 2 -subjid sub-pilot -sd /out/fmriprep-23.1.4/sourcedata/freesurfer -expert /work/fmriprep_23_1_wf/single_subject_pilot_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts 
Stdout:
        INFO: hi-res volumes are conformed to the min voxel size
        fs-check-version --s sub-pilot --o /tmp/tmp.DIL0Yt
        Thu Aug 31 21:01:14 PDT 2023

        setenv SUBJECTS_DIR /out/fmriprep-23.1.4/sourcedata/freesurfer
        cd /work/fmriprep_23_1_wf/single_subject_pilot_wf/anat_preproc_wf/surface_recon_wf/autorecon1
        /opt/freesurfer/bin/fs-check-version --s sub-pilot --o /tmp/tmp.DIL0Yt
        -rwxrwxr-x 1 cprovins russpold 18565 Aug  3  2022 /opt/freesurfer/bin/fs-check-version

        freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
        $Id$
        Linux sh03-06n05.int 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
        pid 31112
        Current FS Version freesurfer-linux-ubuntu22_x86_64-7.3.2-20220804-6354275
        Subject does not have a bstampfile, copying /opt/freesurfer/build-stamp.txt
        Subject FS Version: 
        No constraints on version because REQ=UnSet and FsVerFile=NotThere
        #@#% fs-check-version match = 1
        fs-check-version Done
        Linux sh03-06n05.int 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

        recon-all -s sub-pilot exited with ERRORS at Thu Aug 31 21:01:14 PDT 2023

        For more details, see the log file 
        To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Stderr:
        cp: not writing through dangling symlink '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/scripts/build-stamp.txt'
        cat: /out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/scripts/build-stamp.txt: No such file or directory
        cp: not writing through dangling symlink '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/scripts/expert-options'
Traceback:
        Traceback (most recent call last):
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
            setattr(outputs, key, val)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 424, in validate
            value = super(MultiObject, self).validate(objekt, name, newvalue)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_types.py", line 2699, in validate
            return TraitListObject(self, object, name, value)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 582, in __init__
            super().__init__(
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 213, in __init__
            super().__init__(self.item_validator(item) for item in iterable)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
            super().__init__(self.item_validator(item) for item in iterable)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/trait_list_object.py", line 865, in _item_validator
            return trait_validator(object, self.name, value)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
            value = super(File, self).validate(objekt, name, value, return_pathlike=True)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
            self.error(objekt, name, str(value))
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
            raise TraitError(
        traits.trait_errors.TraitError: Each element of the 'aparc_a2009s_stats' trait of a ReconAllOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/lh.aparc.a2009s.stats' <class 'str'> was specified.

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
            outputs = self.aggregate_outputs(runtime)
          File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
            raise FileNotFoundError(msg)
        FileNotFoundError: No such file or directory '['/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/lh.aparc.a2009s.stats', '/out/fmriprep-23.1.4/sourcedata/freesurfer/sub-pilot/stats/rh.aparc.a2009s.stats']' for output 'aparc_a2009s_stats' of a ReconAll interface



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/run.py", line 227, in main
    failed_reports = generate_reports(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/reports/core.py", line 96, in generate_reports
    report_errors = [
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/reports/core.py", line 97, in <listcomp>
    run_reports(
      File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/reports/core.py", line 79, in run_reports
    return Report(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/reports/core.py", line 307, in __init__
    self._load_config(Path(config or pkgrf("niworkflows", "reports/default.yml")))
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/reports/core.py", line 48, in _load_config
    self.index(settings["sections"])
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/reports/core.py", line 348, in index
    reportlets = [
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/reports/core.py", line 349, in <listcomp>
    Reportlet(self.layout, self.out_dir, config=cfg)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/reports/core.py", line 196, in __init__
    contents = src.read_text().strip()
  File "/opt/conda/envs/fmriprep/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/opt/conda/envs/fmriprep/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/out/fmriprep-23.1.4/sub-pilot/figures/sub-pilot_ses-01_desc-summary_T1w.html'
Completed with return code: 1
```

**Comment by celprov** [comment]
The problem comes from the parallel processes working on the same file at the same time thus compromising it.
