### ISSUE TITLE
Node Name Error : ValueError: Could not build path with entities {'subject': 'Subject1', 'run': 01, 'suffix': 'bold', 'datatype': 'figures', 'extension': 'html', 'desc': 'validation'}.

### ISSUE THREAD

**Issue by belfinrv** [nipreps/fmriprep#3086]
### What happened?

We tried preprocess a rs-fMRI subject using fMRIprep. The pipeline completed the process and showed successful anatomical processing and error in BOLD process.  The summary .html file displayed series of Node Name errors. 

### What command did you use?

```shell
fMRIprep preprocess command with --skip_bids_validation option.
```

### What version of fMRIPrep are you running?

22.1.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
File:  /home/user/Project_test/data_fmriprep/sub-subject1/log/20230906-115138_3a685fd9-6c13-4b97-b8fd-716f3ad86cd5/crash-20230906-115231-user-ds_report_validation-7d2428e5-b37f-4971-96de-6a03021dad72.txt
Working Directory:  /home/user/Project_test/logs/fmriprep_22_1_wf/single_subject_subject1_wf/func_preproc_run_02_wf/ds_report_validation
Inputs:
acquisition:
atlas:
base_directory:  /home/user/Project_test/data_fmriprep
ceagent:
check_hdr: True
cohort:
compress:
data_dtype:
datatype: figures
density:
desc: validation
direction:
dismiss_entities: ['echo']
echo:
extension:
flip:
fmap:
fmapid:
from:
hemi:
in_file: [' /home/user/Project_test/logs/fmriprep_22_1_wf/single_subject_subject1_wf/func_preproc_run_02_wf/initial_boldref_wf/val_bold/mapflow/_val_bold0/report.html']
inv:
label:
meta_dict:
modality:
mode:
model:
mt:
part:
proc:
reconstruction:
recording:
resolution:
roi:
run:
scans:
session:
source_file: [' /home/user/Project_test/data_BIDS/sub-subject1/func/sub-subject1_run-02_bold.nii.gz']
space:
subject:
subset:
suffix:
task:
to:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ds_report_validation.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/bids.py", line 615, in _run_interface
	    raise ValueError(f"Could not build path with entities {out_entities}.")
	ValueError: Could not build path with entities {'subject': 'subject1', 'run': 02, 'suffix': 'bold', 'datatype': 'figures', 'extension': 'html', 'desc': 'validation'}.
```

**Comment by effigies** [comment]
You don't have a task. Please do not `--skip-bids-validation` unless you have separately validated the dataset. We include it because it helps catch problems like this.
