### ISSUE TITLE
msmsulc error

### ISSUE THREAD

**Issue by zugmana** [nipreps/fmriprep#3092]
### What happened?

Hi all,

We've successfully used version "23.2.0.dev36+g603ce440" for preprocessing few subjects with multi-echo data.
One of the subjects however presented the error below. I'm trying to rerun this subject, but maybe someone might have a better insight on what might have caused this error.

Thanks!

### What command did you use?

```shell
singularity run fmriprep_msmsulc.simg BIDS 24740.out participant --participant_label 24740 -w ${TMPDIR}/24704.wrk --notrack --output-space MNI152NLin6Asym:res-2 T1w fsaverage fsLR fsnative --nthreads ${SLURM_CPUS_PER_TASK} --omp-nthreads ${SLURM_CPUS_PER_TASK} --me-output-echos --cifti-output 91k --mem 36 --project-goodvoxels
```

### What version of fMRIPrep are you running?

23.2.0.dev36+g603ce440

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: _msmsulc1
Working directory: /lscratch/8536410/24740.wrk/fmriprep_23_2_wf/single_subject_24740_wf/anat_preproc_wf/sphere_reg_wf/msm_sulc_wf/msmsulc/mapflow/_msmsulc1

Node inputs:

args = <undefined>
config_file = /opt/conda/envs/fmriprep/lib/python3.10/site-packages/smriprep/data/msm/MSMSulcStrainFinalconf
environ = {}
in_data = /lscratch/8536410/24740.wrk/fmriprep_23_2_wf/single_subject_24740_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/morphs2gii/mapflow/_morphs2gii3/rh.sulc_converted.gii
in_mesh = /lscratch/8536410/24740.wrk/fmriprep_23_2_wf/single_subject_24740_wf/anat_preproc_wf/sphere_reg_wf/msm_sulc_wf/apply_surface_affine/mapflow/_apply_surface_affine1/rh.sphere_converted_xformed.surf.gii
in_register = <undefined>
in_weight = <undefined>
levels = <undefined>
out_base = rh.
output_format = <undefined>
reference_data = /home/zugmana2/.cache/templateflow/tpl-fsaverage/tpl-fsaverage_hemi-R_den-164k_sulc.shape.gii
reference_mesh = /home/zugmana2/.cache/templateflow/tpl-fsaverage/tpl-fsaverage_hemi-R_den-164k_desc-std_sphere.surf.gii
reference_weight = <undefined>
smooth_output_sigma = <undefined>
transformed_mesh = <undefined>
verbose = True

Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _msmsulc1.

Cmdline:
	msm --conf=/opt/conda/envs/fmriprep/lib/python3.10/site-packages/smriprep/data/msm/MSMSulcStrainFinalconf --indata=/lscratch/8536410/24740.wrk/fmriprep_23_2_wf/single_subject_24740_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/morphs2gii/mapflow/_morphs2gii3/rh.sulc_converted.gii --inmesh=/lscratch/8536410/24740.wrk/fmriprep_23_2_wf/single_subject_24740_wf/anat_preproc_wf/sphere_reg_wf/msm_sulc_wf/apply_surface_affine/mapflow/_apply_surface_affine1/rh.sphere_converted_xformed.surf.gii --out=rh. --refdata=/home/zugmana2/.cache/templateflow/tpl-fsaverage/tpl-fsaverage_hemi-R_den-164k_sulc.shape.gii --refmesh=/home/zugmana2/.cache/templateflow/tpl-fsaverage/tpl-fsaverage_hemi-R_den-164k_desc-std_sphere.surf.gii --verbose
Stdout:
	cost.size() 4 AFFINE,DISCRETE,DISCRETE,DISCRETE
	 iters 50,10,15,15
	lambda 0,10,7.5,7.5
	 sigmain 0,0,0,0
	 sigmaref 0,0,0,0
	 datagrid 6,4,5,6
	 cp gridres 6,2,3,4
	 sp grid 6,4,5,6
	 alpha_knn 5,5,5,5
	 in parse options  _simval 3,2,2,2 interations 50,10,15,15 input sigma 0,0,0,0 ref sigma 0,0,0,0 lambda 0,10,7.5,7.5  _genesis 6,4,5,6 _gridres 6,2,3,4 _sampres 6,4,5,6 opt AFFINE,DISCRETE,DISCRETE,DISCRETE _scale 0 mesh interpolator BARY discrete implementation HOCR regoption 3 potts 0
	 Initialising level 1
	-2 ia -1  30 30 ib 28 rth 9.5493 i 15 nth2 47 rph 4.77465 nph2 15 PI 3.14159 debug 0
Stderr:

Traceback:
	RuntimeError: subprocess exited with code 1.
```

**Comment by effigies** [comment]
I'm encountering this where the RH surface fails. Loading the two surfaces in freeview (`freeview -f <surf>`) the LH surface is spherical while the RH surface is visibly oblong.

![image](https://github.com/nipreps/fmriprep/assets/83442/155667e4-a0d1-4f9d-924b-8f9ea880ae48)

Seems to be related to the affine regression.

**Comment by effigies** [comment]
@edickie Have you encountered this situation? I've tried re-running the affine regression from scratch, but it seems pretty deterministic.
