### ISSUE TITLE
Conflict with sbref specifications in BIDS filter file

### ISSUE THREAD

**Issue by DVSneuro** [nipreps/fmriprep#3154]
### What happened?

Hi, we're testing the recent pre-releases for 23.2.0, and fmriprep is crashing with the error below. The same code was working fine on the previous version of fmriprep, so maybe something changed with how sbref images are handled?

### What command did you use?

```shell
-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \
-B ${MPLCONFIGDIR_DIR}:/opt/mplconfigdir \
-B $maindir:/base \
-B ~/work/tools/licenses:/opts \
-B $scratchdir:/scratch \
~/work/tools/fmriprep-23.2.0a2.simg \
/base/bids /base/derivatives/fmriprep-syn-new \
participant --participant_label $sub \
--stop-on-first-crash \
--me-output-echos \
--ignore fieldmaps \
--use-syn-sdc \
--cifti-output 91k \
--output-spaces fsLR fsaverage MNI152NLin6Asym \
--bids-filter-file /base/code/fmriprep_config.json \
--fs-license-file /opts/fs_license.txt -w /scratch
```

### What version of fMRIPrep are you running?

23.2.0a2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/envs/fmriprep/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/workflow.py", line 115, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/base.py", line 93, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/base.py", line 644, in init_single_subject_wf
    bold_wf = init_bold_wf(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/bold/base.py", line 252, in init_bold_wf
    bold_fit_wf = init_bold_fit_wf(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/bold/fit.py", line 208, in init_bold_fit_wf
    sbref_files = get_sbrefs(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/workflows/bold/fit.py", line 86, in get_sbrefs
    entities.update(suffix="sbref", extension=[".nii", ".nii.gz"], **entity_overrides)
TypeError: dict.update() got multiple values for keyword argument 'suffix'
```

**Comment by effigies** [comment]
Yup, thanks for the report! A little surprised since I've been testing on a dataset with sbrefs, but we'll figure it out.

**Comment by effigies** [comment]
Ah, got it. It's the filter file. Could you share its contents? And the full file listing of one of your datasets?

**Comment by effigies** [comment]
The next release will include a fix.

I don't think this is a critical bug that requires an immediate release. In the meantime, you can just remove the `"suffix": "sbref"` bit from your BIDS filter file.

**Comment by DVSneuro** [comment]
Thanks! Much appreciated. We updated our config file based on your suggestions, and it's working now. Still running some tests, but looking forward to seeing if this new release resolves some issues we were seeing with distortion correction.
