### ISSUE TITLE
Wrong atlas density for --cifti-output 170k

### ISSUE THREAD

**Issue by xingyu-liu** [nipreps/fmriprep#3178]
### What happened?

Hi fMRIPrep Team,

I recently attempted to preprocess a dataset using the --cifti-output 170k option, but encountered an error that caused the script to terminate (details in the attached log). It appears the issue may be related to using a 32k template for generating 59k cortex data in the 170k grayordinate space.

Any guidance or assistance you could provide on this matter would be greatly appreciated.

Best,
Xingyu

### What command did you use?

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.6 -it -v /Users/xingyuliu/postdoc_upenn/ref_materials/others/freesurfer_license.txt:/opt/freesurfer/license.txt:ro -v /Users/xingyuliu/dataset/neuro/MPG/ds001168_custom:/data:ro -v /Users/xingyuliu/dataset/neuro/MPG/ds001168_custom/derivatives:/out nipreps/fmriprep:23.1.4 /data /out participant --cifti-output 170k --skull-strip-t1w skip --participant-label 01
```

### What version of fMRIPrep are you running?

23.1.4

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

Anatomical derivatives

### Please copy and paste any relevant log output.

```shell
Node Name: fmriprep_23_1_wf.single_subject_01_wf.func_preproc_ses_1_task_rest_acq_fullbrain_run_1_wf.bold_fsLR_resampling_wf.mask_fsLR

File: /out/sub-01/log/20231208-143718_d0f6a0af-6b8f-452d-8759-e52cec7b7d3b/crash-20231208-174016-root-mask_fsLR.a1-11bb9206-bbd7-4a07-ab52-3c1632f5c958.txt
Working Directory: /tmp/work/fmriprep_23_1_wf/single_subject_01_wf/func_preproc_ses_1_task_rest_acq_fullbrain_run_1_wf/bold_fsLR_resampling_wf/_hemi_R/mask_fsLR
Inputs:
args:
column:
environ: {}
in_file:
mask:
out_file:
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node mask_fsLR.

Cmdline:
	wb_command -metric-mask /tmp/work/fmriprep_23_1_wf/single_subject_01_wf/func_preproc_ses_1_task_rest_acq_fullbrain_run_1_wf/bold_fsLR_resampling_wf/_hemi_R/resample_to_fsLR/tpl-fsLR_hemi-R_den-59k_sphere.surf.out /opt/conda/envs/fmriprep/lib/python3.10/site-packages/smriprep/data/atlases/R.atlasroi.32k_fs_LR.shape.gii tpl-fsLR_hemi-R_den-59k_sphere.surf_masked.func.gii
Stdout:

Stderr:

	While running:
	/opt/workbench/bin_linux64/../exe_linux64/wb_command -metric-mask /tmp/work/fmriprep_23_1_wf/single_subject_01_wf/func_preproc_ses_1_task_rest_acq_fullbrain_run_1_wf/bold_fsLR_resampling_wf/_hemi_R/resample_to_fsLR/tpl-fsLR_hemi-R_den-59k_sphere.surf.out /opt/conda/envs/fmriprep/lib/python3.10/site-packages/smriprep/data/atlases/R.atlasroi.32k_fs_LR.shape.gii tpl-fsLR_hemi-R_den-59k_sphere.surf_masked.func.gii

	ERROR: mask metric must have the same number of vertices

Traceback:
	RuntimeError: subprocess exited with code 255.
```

**Comment by effigies** [comment]
Thanks for this. Good to know somebody actually uses that option.

```
smriprep/data/atlases/R.atlasroi.32k_fs_LR.shape.gii
```

Looks like we need to add the 59k files to smriprep and then make sure we use them here.
