### ISSUE TITLE
fmriprep23.2 '--level minimal' fails with 'anat_to_template_Warped.nii.gz' not available

### ISSUE THREAD

**Issue by FeHoff** [nipreps/fmriprep#3224]
### What happened?

For fmriprep23.2 the  '--level minimal' setting leads to a crash while '--level resampling' and '--level full' works keeping everything else constant. Only multi-threading and RAM is higher for the later as everything is done in RAM and also Datalad containers-run is used but stripped here as it works for all.

### What command did you use?

```shell
singularity exec -B {{pwd}} --cleanenv bids-fmriprep--23.2.0.sing inputs/big fmriprep participant \
    --participant-label $subid \
    --work-dir . \
    --skip_bids_validation \
    --fs-subjects-dir inputs/big_freesurfer/$subid \
    --fs-license-file code/license.txt \
    --nthreads 3 \
    --omp-nthreads 3 \
    --mem-mb 7000 \
    --random-seed 12345 \
    --skull-strip-fixed-seed \
    --stop-on-first-crash \
    --ignore slicetiming \
    --use-aroma \
    --level minimal \
    --output-spaces func         MNI152NLin2009cAsym:res-native \
    --cifti-output 91k \
    --notrack \
    --verbose
```

### What version of fMRIPrep are you running?

23.2.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
240202-20:22:51,357 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 1 jobs ready. Free memory (GB): 4.00/7.00, Free processors: 0/3.
                     Currently running:
                       * fmriprep_23_2_wf.sub_1234567_wf.anat_fit_wf.brain_extraction_wf.norm
240202-21:02:33,773 nipype.workflow INFO:
	 [Node] Finished "norm", elapsed time 2383.951202s.
240202-21:02:33,776 nipype.workflow WARNING:
	 Storing result file without outputs
240202-21:02:33,816 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_23_2_wf.sub_1234567_wf.anat_fit_wf.brain_extraction_wf.norm" (/dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/norm)
240202-21:02:35,27 nipype.workflow ERROR:
	 Node norm failed to run on host jrc0795.
240202-21:02:35,36 nipype.workflow ERROR:
	 Saving crash info to /dev/shm/1234567.12603952/ds/fmriprep/sub-1234567/log/20240202-195201_73429cc5-9e12-48f1-8a1f-d6561049794c/crash-20240202-210235-hoffstaedter1-norm-f8aeffb5-7722-469f-8191-101ce8c45d1d.txt
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node norm.

Cmdline:
	antsRegistration --collapse-output-transforms 1 --dimensionality 3 --float 1 --initial-moving-transform [ /dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/init_aff/initialization.mat, 0 ] --initialize-transforms-per-stage 0 --interpolation LanczosWindowedSinc --output [ anat_to_template, anat_to_template_Warped.nii.gz ] --transform Rigid[ 0.1 ] --metric MI[ /p/project/coman/prep_fMRIprep/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz, /dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/inu_n4/mapflow/_inu_n40/sub-1234567_ses-2_T1w_noise_corrected_maths_corrected.nii.gz, 1, 32, Regular, 0.25 ] --convergence [ 1000x500x250x100, 1e-08, 10 ] --smoothing-sigmas 4.0x2.0x1.0x0.0vox --shrink-factors 8x4x2x1 --use-histogram-matching 1 --masks [ /p/project/coman/prep_fMRIprep/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_desc-BrainCerebellumExtraction_mask.nii.gz, NULL ] --transform Affine[ 0.1 ] --metric MI[ /p/project/coman/prep_fMRIprep/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz, /dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/inu_n4/mapflow/_inu_n40/sub-1234567_ses-2_T1w_noise_corrected_maths_corrected.nii.gz, 1, 32, Regular, 0.25 ] --convergence [ 1000x500x250x100, 1e-08, 10 ] --smoothing-sigmas 4.0x2.0x1.0x0.0vox --shrink-factors 8x4x2x1 --use-histogram-matching 1 --masks [ /p/project/coman/prep_fMRIprep/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_desc-BrainCerebellumExtraction_mask.nii.gz, NULL ] --transform SyN[ 0.1, 3.0, 0.0 ] --metric CC[ /p/project/coman/prep_fMRIprep/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_T1w.nii.gz, /dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/inu_n4/mapflow/_inu_n40/sub-1234567_ses-2_T1w_noise_corrected_maths_corrected.nii.gz, 0.5, 4, None, 1 ] --metric CC[ /dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/lap_tmpl/tpl-OASIS30ANTs_res-01_T1w_maths.nii.gz, /dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/lap_target/sub-1234567_ses-2_T1w_noise_corrected_maths_corrected_maths.nii.gz, 0.5, 4, None, 1 ] --convergence [ 50x10x0, 1e-09, 15 ] --smoothing-sigmas 2.0x1.0x0.0vox --shrink-factors 4x2x1 --use-histogram-matching 1 --masks [ /p/project/coman/prep_fMRIprep/templateflow/tpl-OASIS30ANTs/tpl-OASIS30ANTs_res-01_desc-BrainCerebellumExtraction_mask.nii.gz, NULL ] -v --winsorize-image-intensities [ 0.025, 0.975 ]  --write-composite-transform 0
Stdout:
	All_Command_lines_OK
	Using single precision for computations.
	=============================================================================
	The composite transform comprises the following transforms (in order):

... (cut thousands of lines) ...

Stderr:
	 file NULL does not exist . 
	 file NULL does not exist . 
	 file NULL does not exist . 
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nibabel/loadsave.py", line 100, in load
	    stat_result = os.stat(filename)
	FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/interfaces/fixes.py", line 110, in _run_interface
	    _copyxform(
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/utils/images.py", line 79, in _copyxform
	    resampled = nb.load(out_image, mmap=False)
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nibabel/loadsave.py", line 102, in load
	    raise FileNotFoundError(f"No such file or no access: '{filename}'")
	FileNotFoundError: No such file or no access: '/dev/shm/1234567.12603952/ds/fmriprep_23_2_wf/sub_1234567_wf/anat_fit_wf/brain_extraction_wf/norm/anat_to_template_Warped.nii.gz'


240202-21:02:35,40 nipype.workflow CRITICAL:
	 fMRIPrep failed: Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node norm.
```

**Comment by effigies** [comment]
ANTs is complaining:

```
	 file NULL does not exist . 
	 file NULL does not exist . 
	 file NULL does not exist . 
	Killed
```

Which is likely to be a memory error. What is the disk usage of `/dev/shm`? It seems like you're running everything on a ramdisk, so your processes will be competing for space for program memory and I/O.

Is this a consistent failure? If it happens every time, is it always the same node? I am surprised that `--level full` works, since this workflow is a strict subgraph of that one.

**Comment by FeHoff** [comment]
Yes, everything is running in /dev/shm = ramdisk on Linux, bc the HPC system has no local storage and inodes are severely limited. I did a rough estimate and as the nodes did not fail, I assumed there was enough RAM with 1TB for 128 subjects with 2 bold runs. Will rerun with less subjects in parallel = more RAM.
Thanks!!

**Comment by FeHoff** [comment]
I now ran 100 subjects (instead of 128) on a compute node with 128 cores and 1TB RAM and it worked nicely!

FTR: I deliberately overbook the cpu with multi-threading to have 100% of load most of the time but RAM is more problematic obviously. The dynamic RAM allocation of Nypipe saves jobs of the time but not for to many jobs in parallel, also as I call each subject in a separate fmriprep container for reproducibility. Thanks again for the immediate answer @effigies !!
