### ISSUE TITLE
Run Multiple Subjects in a Loop and fmriprep Picked the Wrong Subject's Jason File

### ISSUE THREAD

**Issue by xxnagit** [nipreps/fmriprep#3227]
### What happened?

Dear Developer,
I've tested one subject in our HPC and very worked out. But while I have nearly 100 subjects to run, I used a bash script to loop over the subjects, so that each time it's running just 1 subject. However, while running subject 103, it picked up json file for 106, and all the other subjects picked up 106 as well. I removed the loop and ran 103 as tested before, it still picked up json file for 106. Untill I removed all raw data of 106, 103 started to run correctly. It seems that my singularity --cleanenv is not working as it repeated where it left. Is there any other way to solve this? Thank you so much!

### What command did you use?

```shell
My command line running for 1 subject is:
singularity run --cleanenv \
-B /home/fmri/data_BF/fmriprep/.cache/fmriprep:/home/fmriprep/.cache/fmriprep \
/home/fmri/hpcScripts/nipreps_fmriprep_23.2.0_20240102.simg \
/home/fmri/data_BF/BIDS /home/fmri/data_BF/fmriprep_out \
participant --participant_label 103 \
--bids-filter-file /home/fmri/hpcScripts/BF_func/s1_fmriprep/tasksToRun.txt  \
--output-spaces MNI152NLin6Asym:res-2 MNI152NLin2009cAsym:res-2 T1w:res-2 \
--skip_bids_validation \
--notrack \
--stop-on-first-crash
```

### What version of fMRIPrep are you running?

23.2.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
start
running sub:103
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/index.py", line 303, in load_json
    return json.load(handle)
  File "/opt/conda/envs/fmriprep/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/conda/envs/fmriprep/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/fmriprep/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 15 (char 14)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/run.py", line 40, in main
    parse_args()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/parser.py", line 802, in parse_args
    config.from_dict({})
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/config.py", line 691, in from_dict
    execution.load(settings, init=initialize('execution'), ignore=ignore)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/config.py", line 235, in load
    cls.init()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/config.py", line 485, in init
    cls._layout = BIDSLayout(
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/layout.py", line 177, in __init__
    _indexer(self)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/index.py", line 154, in __call__
    self._index_metadata()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/index.py", line 415, in _index_metadata
    file_md.update(pl())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/bids/layout/index.py", line 305, in load_json
    raise OSError(
OSError: Error occurred while trying to decode JSON from file /home/fmri/data_BF/BIDS/sub-106/fmap/sub-106_task-rest_dir-AP_epi.json
```

**Comment by xxnagit** [comment]
woo...my bad, it is correct that this file was missing things, thank you so much for your prompt reply!
