### ISSUE TITLE
Problem during Node gen_avg - The xxx trait of a VolregOutputSpec instance must be a pathlike object or string 

### ISSUE THREAD

**Issue by LucieLenglart** [nipreps/fmriprep#3230]
### What happened?

While running fmriprep, I get an error during the run of node gen_avg

### What command did you use?

```shell
C:\Windows\System32>fmriprep-docker /Users/lucie/Documents/fMRIAnalysis/Files/BIDS  /Users/lucie/Documents/fMRIAnalysis/Files/fmriprep participant --participant-label F041111 --fs-license-file /Users/lucie/Documents/fMRIAnalysis/Files/fmriprep/license.txt --stop-on-first-crash -w /Users/lucie/Documents/fMRIAnalysis/Files/fmriprep/temp --debug all
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=24.0.7 -it -v C:\Users\lucie\Documents\fMRIAnalysis\Files\fmriprep\license.txt:/opt/freesurfer/license.txt:ro -v C:\Users\lucie\Documents\fMRIAnalysis\Files\BIDS:/data:ro -v C:\Users\lucie\Documents\fMRIAnalysis\Files\fmriprep:/out -v C:\Users\lucie\Documents\fMRIAnalysis\Files\fmriprep\temp:/scratch nipreps/fmriprep:23.2.0 /data /out participant --participant-label F041111 --stop-on-first-crash --debug all -w /scratch
```

### What version of fMRIPrep are you running?

fMRIPrep 23.2.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_23_2_wf.sub_F041111_wf.bold_task_rest_acq_Raw_wf.bold_fit_wf.hmc_boldref_wf.gen_avg
Working directory: /scratch/fmriprep_23_2_wf/sub_F041111_wf/bold_task_rest_acq_Raw_wf/bold_fit_wf/hmc_boldref_wf/gen_avg

Node inputs:

in_file = /data/sub-F041111/func/sub-F041111_task-rest_acq-Raw_bold.nii
mc_method = AFNI
nonnegative = True
num_threads = <undefined>
t_mask = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
two_pass = True

Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/linear.py", line 47, in run
    node.run(updatehash=updatehash)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node gen_avg.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'md1d_file' trait of a VolregOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch/fmriprep_23_2_wf/sub_F041111_wf/bold_task_rest_acq_Raw_wf/bold_fit_wf/hmc_boldref_wf/gen_avg/sub-F041111_task-rest_acq-Raw_bold_sliced_md.1D' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/niworkflows/interfaces/images.py", line 337, in _run_interface
	    res = volreg.run()
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/scratch/fmriprep_23_2_wf/sub_F041111_wf/bold_task_rest_acq_Raw_wf/bold_fit_wf/hmc_boldref_wf/gen_avg/sub-F041111_task-rest_acq-Raw_bold_sliced_md.1D' for output 'md1d_file' of a Volreg interface
```

### Additional information / screenshots

It seems to be a problem similar to [this one](https://neurostars.org/t/fmriprep-error-3dvolreg-fails-filenotfound-error/27163). Mango1 told me that in their case it wase due to troubles with the qform and sform matrices, but mine are present and seem  correct (obtained with dcm2niix). 
Similar problem encountered [here](https://neurostars.org/t/fmriprep-traits-trait-errors-traiterror-the-md1d-file-trait/25983) due to the use of --fs-no-reconall, but I do not use it here. 

It is worth noting that the file mentionned in the error regularly change - here it is md1d_file, but I also had oned_file and out_file.

I tried to change / empty the working directory, to update freesurfer license, to skip bids validation or slice timing, it does not change. 
When running without --stop-on-first-crash, I obtain correct images of anatomical QA.

**Comment by effigies** [comment]
Thanks for this. Is there any chance that you could share the `.nii` file that's failing here?

**Comment by effigies** [comment]
Thanks for following up!
