### ISSUE TITLE
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmp3_xycsud.json']' died with <Signals.SIGABRT: 6>.

### ISSUE THREAD

**Issue by m9080212** [nipreps/fmriprep#3289]
### What happened?

I tried to preprocess the FMRI dataset and got the following error. 

### What command did you use?

```shell
fmriprep-docker '/media/menglab/Work2/hy/face_imagery/block_design/BIDS' '/media/menglab/Work2/hy/face_imagery/block_design/BIDS/derivatives/fMRIprep' -w '/media/menglab/Work2/hy/face_imagery/block_design/fMRIprep_working_directory' --fs-license-file '/home/menglab/freesurfer/license.txt' --participant-label 1 2 --ignore slicetiming --output-spaces anat MNI152NLin2009cAsym --skull-strip-t1w force
```

### What version of fMRIPrep are you running?

23.2.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.7 -it -v /home/menglab/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /media/menglab/Work2/hy/face_imagery/block_design/BIDS:/data:ro -v /media/menglab/Work2/hy/face_imagery/block_design/BIDS/derivatives/fMRIprep:/out -v /media/menglab/Work2/hy/face_imagery/block_design/fMRIprep_working_directory:/scratch nipreps/fmriprep:23.2.2 /data /out participant --participant-label 1 2 --ignore slicetiming --skull-strip-t1w force -w /scratch --output-spaces anat MNI152NLin2009cAsym
node[9]: ../../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x7fe9ec255d69 node::Abort() [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 2: 0x7fe9ec255dfb  [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 3: 0x7fe9ec2cd2dd node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 4: 0x7fe9ec2cd3e7 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 5: 0x7fe9ec211fd7  [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 6: 0x7fe9ec214104 node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 7: 0x7fe9ec2148d3 node::Start(int, char**) [/opt/conda/envs/fmriprep/bin/../lib/libnode.so.108]
 8: 0x7fe9eb7cad90  [/usr/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x7fe9eb7cae40 __libc_start_main [/usr/lib/x86_64-linux-gnu/libc.so.6]
10: 0x55f8a87f807f  [node]
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/bin/fmriprep", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/run.py", line 40, in main
    parse_args()
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/cli/parser.py", line 828, in parse_args
    validate_input_dir(config.environment.exec_env, opts.bids_dir, opts.participant_label)
  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/fmriprep/utils/bids.py", line 237, in validate_input_dir
    subprocess.check_call(['bids-validator', str(bids_dir), '-c', temp.name])
  File "/opt/conda/envs/fmriprep/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', '/data', '-c', '/tmp/tmpslslstgg.json']' died with <Signals.SIGABRT: 6>.
fMRIPrep: Please report errors to https://github.com/nipreps/fmriprep/issues
```

**Comment by mgxd** [comment]
Looks like you are hitting https://github.com/nodejs/node/issues/43064 - skimming through that thread, updating Docker could help

**Comment by Yingjuan** [comment]
Hello,
I encountered the same issue. Could you please share how you resolved it? Thank you!
- Mary
