### ISSUE TITLE
Installation of FSL with conda potentially incomplete

### ISSUE THREAD

**Issue by oesteban** [nipreps/fmriprep#3334]
### What happened?

In a bare-metal environment, I installed dependencies following the Dockerfile steps. Once everything is ready, I consistently hit the following error:

```
Traceback (most recent call last):
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fast.

Cmdline:
	fast -N -p -g -S 1 /home/oesteban/tmp/hcph-fmriprep/work/fmriprep_24_1_wf/sub_001_wf/anat_fit_wf/fast/sub-001_ses-001_acq-undistorted_T1w_noise_corrected_ras_template_corrected_xform_masked.nii.gz
Stdout:

Stderr:
	terminate called after throwing an instance of 'std::logic_error'
	  what():  basic_string: construction from null is not valid
	Aborted (core dumped)
```

The error occurs when running the command line independently too:

```
fast -N -p -g -S 1 /home/oesteban/tmp/hcph-fmriprep/work/fmriprep_24_1_wf/sub_001_wf/anat_fit_wf/fast/sub-001_ses-001_acq-undistorted_T1w_noise_corrected_ras_template_corrected_xform_masked.nii.gz
```

Seems like `fast` is failing to properly parse the command line.

When trying to determine the version of fsl installed, the installation seems incomplete:

```
(prompt) $ fslversion
$FSLDIR is not set - aborting
```
Manually setting `$FSLDIR` does not resolve the issue as the text file with the version string is not found within the conda environment.

Installing the latest FSL following their recommendation for containers (https://fsl.fmrib.ox.ac.uk/fsl/docs/#/install/container) seems to do the trick:

- `fast` parses the command line properly
- `$FSLDIR` is properly defined and `fslversion` reports the expected output.

### What command did you use?

```shell
fmriprep /data/datasets/hcph/ /data/derivatives/hcph-fmriprep participant --participant-label 001 --bids-database-dir /data/datasets/hcph/.bids-index/ --nprocs 8 --omp-nthreads 12 -w work -vv --skip-bids-validation --anat-only 2> errors.txt > log.txt
```
```


### What version of fMRIPrep are you running?

master

### How are you running fMRIPrep?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
Node: fmriprep_24_1_wf.sub_001_wf.anat_fit_wf.fast
Working directory: /home/oesteban/tmp/hcph-fmriprep/work/fmriprep_24_1_wf/sub_001_wf/anat_fit_wf/fast

Node inputs:

args = <undefined>
bias_iters = <undefined>
bias_lowpass = <undefined>
environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
hyper = <undefined>
img_type = <undefined>
in_files = <undefined>
init_seg_smooth = <undefined>
init_transform = <undefined>
iters_afterbias = <undefined>
manual_seg = <undefined>
mixel_smooth = <undefined>
no_bias = True
no_pve = <undefined>
number_classes = <undefined>
other_priors = <undefined>
out_basename = <undefined>
output_biascorrected = <undefined>
output_biasfield = <undefined>
output_type = NIFTI_GZ
probability_maps = True
segment_iters = <undefined>
segments = True
use_priors = <undefined>
verbose = <undefined>

Traceback (most recent call last):
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fast.

Cmdline:
	fast -N -p -g -S 1 /home/oesteban/tmp/hcph-fmriprep/work/fmriprep_24_1_wf/sub_001_wf/anat_fit_wf/fast/sub-001_ses-001_acq-undistorted_T1w_noise_corrected_ras_template_corrected_xform_masked.nii.gz
Stdout:

Stderr:
	terminate called after throwing an instance of 'std::logic_error'
	  what():  basic_string: construction from null is not valid
	Aborted (core dumped)
Traceback:
	Traceback (most recent call last):
	  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'tissue_class_map' trait of a FASTOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/home/oesteban/tmp/hcph-fmriprep/work/fmriprep_24_1_wf/sub_001_wf/anat_fit_wf/fast/sub-001_ses-001_acq-undistorted_T1w_noise_corrected_ras_template_corrected_xform_masked_seg.nii.gz' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/oesteban/.miniconda3/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/home/oesteban/tmp/hcph-fmriprep/work/fmriprep_24_1_wf/sub_001_wf/anat_fit_wf/fast/sub-001_ses-001_acq-undistorted_T1w_noise_corrected_ras_template_corrected_xform_masked_seg.nii.gz' for output 'tissue_class_map' of a FAST interface
```
```


### Additional information / screenshots

_No response_

**Comment by effigies** [comment]
Does this work?

```
conda env config vars set -n fmriprep FSLDIR=$(conda activate fmriprep && echo $CONDA_PREFIX)
```

Will go into effect next time fmriprep is activated.

**Comment by oesteban** [comment]
I'm setting variables that way. Haven't tested whether fast works with
FSLDIR properly set.

**Comment by oesteban** [comment]
I think FSLDIR was the culprit. Closing for the time being.
