### ISSUE TITLE
Module ds_std_volumes_wf has no input called inputnode.t1w_preproc

### ISSUE THREAD

**Issue by CogBrainHealthLab** [nipreps/fmriprep#3342]
### What happened?

I've recently upgraded from 23.2.0 to 24.0.1 and i encountered the error, described in the log below, when doing a fresh run (deleted output and work dirs) on a subject that was preprocessed successfully in fmriprep 23.2.0. 

### What command did you use?

```shell
fmriprep 06_BIDS output participant--skip_bids_validation --output-spaces MNI152NLin6Asym --participant-label $d --nthreads 2
```

### What version of fMRIPrep are you running?

24.0.1

### How are you running fMRIPrep?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
2024-08-12 12:14:01,124 [ WARNING] Previous output generated by version 23.1.4 found.
2024-08-12 12:14:01,397 [IMPORTANT] Building fMRIPrep's workflow:
           * BIDS dataset path: /home/junhong.yu/SPRENG/06_BIDS.
           * Participant list: ['06'].
           * Run identifier: 20240812-121336_8e5e0f06-337d-4328-8a0c-e7e5f52b7434.
           * Output spaces: MNI152NLin6Asym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /home/junhong.yu/SPRENG/output/sourcedata/freesurfer.
2024-08-12 12:14:03,039 [    INFO] ANAT Stage 1: Adding template workflow
2024-08-12 12:14:03,072 [ WARNING] WARNING: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
2024-08-12 12:14:03,072 [ WARNING] WARNING: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
2024-08-12 12:14:03,348 [    INFO] ANAT Stage 2: Preparing brain extraction workflow
2024-08-12 12:14:03,447 [    INFO] ANAT Stage 3: Preparing segmentation workflow
2024-08-12 12:14:03,447 [ WARNING] FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2024-08-12 12:14:03,447 [ WARNING] FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2024-08-12 12:14:03,452 [    INFO] ANAT Stage 4: Preparing normalization workflow for ['MNI152NLin6Asym', 'MNI152NLin2009cAsym']
2024-08-12 12:14:03,462 [    INFO] ANAT Stage 5: Preparing surface reconstruction workflow
2024-08-12 12:14:03,488 [    INFO] ANAT Stage 6: Preparing mask refinement workflow
2024-08-12 12:14:03,490 [ WARNING] FSLOUTPUTTYPE environment variable is not set. Setting FSLOUTPUTTYPE=NIFTI
2024-08-12 12:14:03,491 [    INFO] ANAT No T2w images provided - skipping Stage 7
2024-08-12 12:14:03,491 [    INFO] ANAT Stage 8: Creating GIFTI surfaces for ['white', 'pial', 'midthickness', 'sphere_reg', 'sphere']
2024-08-12 12:14:03,508 [    INFO] ANAT Stage 8: Creating GIFTI metrics for ['thickness', 'sulc']
2024-08-12 12:14:03,515 [    INFO] ANAT Stage 8a: Creating cortical ribbon mask
2024-08-12 12:14:03,519 [    INFO] ANAT Stage 9: Creating fsLR registration sphere
2024-08-12 12:14:03,522 [    INFO] ANAT Stage 10: Creating MSM-Sulc registration sphere
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/fmriprep/cli/workflow.py", line 126, in build_workflow
    retval['workflow'] = init_fmriprep_wf()
                         ^^^^^^^^^^^^^^^^^^
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/fmriprep/workflows/base.py", line 94, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/fmriprep/workflows/base.py", line 383, in init_single_subject_wf
    workflow.connect([
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/nipype/pipeline/engine/workflows.py", line 239, in connect
    raise Exception("\n".join(["Some connections were not found"] + infostr))
Exception: Some connections were not found
Module ds_std_volumes_wf has no input called inputnode.t1w_preproc

Module ds_std_volumes_wf has no input called inputnode.t1w_mask

Module ds_std_volumes_wf has no input called inputnode.t1w_dseg

Module ds_std_volumes_wf has no input called inputnode.t1w_tpms
```

**Comment by tsalo** [comment]
My guess is you're using a more recent version of smriprep (~0.16.0). You should use an older version of smriprep from before they switched from T1w-specific language to the more generic "anat".

**Comment by CogBrainHealthLab** [comment]
how do i do that? because i imagine my smriprep was basically the one that came along with fmriprep when i pip install fmriprep.

**Comment by effigies** [comment]
```
curl -sSLO https://raw.githubusercontent.com/nipreps/fmriprep/24.0.1/requirements.txt
pip install -r requirements.txt
```

**Comment by CogBrainHealthLab** [comment]
> ```
> curl -sSLO https://raw.githubusercontent.com/nipreps/fmriprep/24.0.1/requirements.txt
> pip install -r requirements.txt
> ```

oh yes this resolves the issue. thanks
