### ISSUE TITLE
Got StopIteration: ('/data', [], []) error 

### ISSUE THREAD

**Issue by withsecco** [nipreps/fmriprep#3396]
### What happened?

Hi, I tried to run fmriprep on Mac OS (M1 chip), but I got this error: `StopIteration: ('/data', [], [])` when I ran the following command `fmriprep-docker /Volumes/Elements/ReadingBrain/L1Data /Volumes/Elements/processedData participant --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt`

I verified that I have the correct access to the data by running the following commands: `docker run --rm -v /Volumes/Elements/ReadingBrain/L1Data:/data:ro ubuntu` and `ls -l /Volumes/Elements/ReadingBrain/L1Data` . I was able to see all the files. 

I downloaded the dataset from OpenNeuro, and it's BIDS validated .

Apologies, as I'm new to Docker and the terminal. Any help is appreciated,  the full log is:

``` Shell
fmriprep-docker /Volumes/Elements/ReadingBrain/L1Data /Volumes/Elements/processedData participant --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=27.3.1 -it -v /Users/qiyu/FREESURFER_HOME/license.txt:/opt/freesurfer/license.txt:ro -v /Volumes/Elements/ReadingBrain/L1Data:/data:ro -v /Volumes/Elements/processedData:/out nipreps/fmriprep:24.1.1 /data /out participant --participant-label 01
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2024-11-12 15:13:56,010 [ WARNING] WARNING: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#socks-proxies
Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/bin/fmriprep", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/fmriprep/cli/run.py", line 40, in main
    parse_args()
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/fmriprep/cli/parser.py", line 878, in parse_args
    config.from_dict({})
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/fmriprep/config.py", line 729, in from_dict
    execution.load(settings, init=initialize('execution'), ignore=ignore)
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/fmriprep/config.py", line 240, in load
    cls.init()
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/fmriprep/config.py", line 503, in init
    cls._layout = BIDSLayout(
                  ^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/bids/layout/layout.py", line 177, in __init__
    _indexer(self)
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/bids/layout/index.py", line 148, in __call__
    all_bfs, all_tag_dicts = self._index_dir(self._layout._root, self._config)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/bids/layout/index.py", line 208, in _index_dir
    _, dirnames, filenames = next(path.fs.walk(path.path))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration: ('/data', [], [])
```

I also tried this but I got the same error. 
``` Shell
docker run -ti --rm \
    --platform linux/amd64 \
    -v /Volumes/Elements/ReadingBrain/L1Data:/data:ro \
    -v /Volumes/Elements/processedData:/out \
    -v /Volumes/Elements/processing:/work \
    -v /Users/qiyu/FREESURFER_HOME/license.txt:/opt/freesurfer/license.txt \
    nipreps/fmriprep:latest /data /out participant \
    --participant-label 01 \
    --work-dir /work \
    --nthreads 1 \
    --mem_mb 12
```

### What command did you use?

```shell
fmriprep-docker /Volumes/Elements/ReadingBrain/L1Data /Volumes/Elements/processedData participant --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=27.3.1 -it -v /Users/qiyu/FREESURFER_HOME/license.txt:/opt/freesurfer/license.txt:ro -v /Volumes/Elements/ReadingBrain/L1Data:/data:ro -v /Volumes/Elements/processedData:/out nipreps/fmriprep:24.1.1 /data /out participant --participant-label 01
```

### What version of fMRIPrep are you running?

24.1.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by mgxd** [comment]
Looks like the data is not being mounted within the container. Can you add `--shell` to your `fmriprep-docker` command, which starts an interactive session within the container and check the following files/directories:

- `/data`
- `/out`
- `/opt/freesurfer/license.txt`

Also, what is the output of `docker version`?

**Comment by withsecco** [comment]
Thank you, @mgxd
 
Here is the output of docker version:
`docker --version
Docker version 27.3.1, build ce12230`

I ran `fmriprep-docker /Volumes/Elements/ReadingBrain/L1Data /Volumes/Elements/processedData participant --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt --shell`

and then ` ls /data` , `ls /out`, `ls /opt/freesurfer/license.txt`

All the outputs are correct. Looks like my data is successfully mounted

 <img width="850" alt="截屏2024-11-13 09 58 03" src="https://github.com/user-attachments/assets/96b7f695-bcfe-4a81-b7e4-9a380cb7ccd5">

But the error persists. 
<img width="892" alt="截屏2024-11-13 10 00 17" src="https://github.com/user-attachments/assets/8c6518d2-e24c-4b18-b116-58f00b2278f8">

**Comment by withsecco** [comment]
Based on #2435 , I tried the following

``` Shell
git clone https://github.com/nipreps/fmriprep.git
git -C fmriprep fetch origin pull/2435/head
git -C fmriprep checkout FETCH_HEAD
```
And this command, 

`fmriprep-docker /Volumes/Elements/ReadingBrain/L1Data /Volumes/Elements/processedData participant --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt --patch fmriprep=fmriprep/fmriprep
`

But I still got this error`StopIteration: ('/data', [], [])`

**Comment by mgxd** [comment]
Sounds like there was an issue with the mounting of the `/Volumes/...` path - glad to hear you got it working!
