### ISSUE TITLE
Crashes and nipype.workflow ERROR

### ISSUE THREAD

**Issue by withsecco** [nipreps/fmriprep#3399]
### What happened?

Hi, after I finished running `conf_plot` I encountered the following errors

``` Shell
2024-11-14 15:06:00,862 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.dvars
241114-15:06:00,872 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.tcompcor
2024-11-14 15:06:00,872 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.tcompcor
241114-15:06:00,875 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.crowncompcor
2024-11-14 15:06:00,875 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.crowncompcor
241114-15:06:00,878 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.acompcor
2024-11-14 15:06:00,878 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.acompcor
```

<img width="688" alt="截屏2024-11-14 23 43 11" src="https://github.com/user-attachments/assets/bebe66d9-a587-410c-bb42-8c61aa31ba81">

``` Shell
Node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.dvars
Working directory: /scratch/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_confounds_wf/dvars

Node inputs:

figdpi = 100
figformat = png
figsize = (11.7, 2.3)
in_file = <undefined>
in_mask = <undefined>
intensity_normalization = 1000.0
remove_zerovariance = True
save_all = False
save_nstd = True
save_plot = False
save_std = True
save_vxstd = False
series_tr = <undefined>
variance_tol = 1e-07

Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node dvars.

Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/algorithms/confounds.py", line 171, in _run_interface
	    dvars = compute_dvars(
	            ^^^^^^^^^^^^^^
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/algorithms/confounds.py", line 1049, in compute_dvars
	    func = np.float32(nb.load(in_file).dataobj)
	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nibabel/arrayproxy.py", line 457, in __array__
	    arr = self._get_scaled(dtype=dtype, slicer=())
	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nibabel/arrayproxy.py", line 424, in _get_scaled
	    scaled = apply_read_scaling(self._get_unscaled(slicer=slicer), scl_slope, scl_inter)
	                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nibabel/arrayproxy.py", line 394, in _get_unscaled
	    return array_from_file(
	           ^^^^^^^^^^^^^^^^
	  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nibabel/volumeutils.py", line 465, in array_from_file
	    n_read = infile.readinto(data_bytes)
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "indexed_gzip/indexed_gzip.pyx", line 804, in indexed_gzip.indexed_gzip._IndexedGzipFile.readinto
	indexed_gzip.indexed_gzip.ZranError: zran_read returned error: ZRAN_READ_FAIL (file: /scratch/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_native_wf/boldref_bold/sub-01_task-read_run-1_bold_tshift_xformresampled.nii.gz)

```

### What command did you use?

```shell
fmriprep-docker L1Data /Volumes/Elements/L1Data_output participant -w /Volumes/Elements/L1Data_processing --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt --mem 12 --nthreads 4 --fs-no-reconall --output-space MNI152NLin2009cAsym
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=27.3.1 -it -v /Users/qiyu/FREESURFER_HOME/license.txt:/opt/freesurfer/license.txt:ro -v /Users/qiyu/L1Data:/data:ro -v /Volumes/Elements/L1Data_output:/out -v /Volumes/Elements/L1Data_processing:/scratch nipreps/fmriprep:24.1.1 /data /out participant --participant-label 01 --mem 12 --nthreads 4 --fs-no-reconall -w /scratch --output-spaces MNI152NLin2009cAsym
```

### What version of fMRIPrep are you running?

24.1.1

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
241114-15:05:58,336 nipype.workflow INFO:
	 [Node] Finished "conf_plot", elapsed time 2.8613150000000003s.
2024-11-14 15:05:58,336 [    INFO] [Node] Finished "conf_plot", elapsed time 2.8613150000000003s.
241114-15:06:00,862 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.dvars
2024-11-14 15:06:00,862 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.dvars
241114-15:06:00,872 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.tcompcor
2024-11-14 15:06:00,872 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.tcompcor
241114-15:06:00,875 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.crowncompcor
2024-11-14 15:06:00,875 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.crowncompcor
241114-15:06:00,878 nipype.workflow ERROR:
	 could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.acompcor
2024-11-14 15:06:00,878 [   ERROR] could not run node: fmriprep_24_1_wf.sub_01_wf.bold_task_read_run_1_wf.bold_confounds_wf.acompcor
2024-11-14 15:06:01,080 [ WARNING] WARNING: sentry_sdk.push_scope is deprecated and will be removed in the next major version. Please consult our migration guide to learn how to migrate to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#scope-pushing
2024-11-14 15:06:01,104 [ WARNING] WARNING: sentry_sdk.push_scope is deprecated and will be removed in the next major version. Please consult our migration guide to learn how to migrate to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#scope-pushing
2024-11-14 15:06:01,130 [ WARNING] WARNING: sentry_sdk.push_scope is deprecated and will be removed in the next major version. Please consult our migration guide to learn how to migrate to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#scope-pushing
2024-11-14 15:06:01,151 [ WARNING] WARNING: sentry_sdk.push_scope is deprecated and will be removed in the next major version. Please consult our migration guide to learn how to migrate to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x#scope-pushing
241114-15:06:01,168 nipype.workflow CRITICAL:
	 fMRIPrep failed: 4 raised. Re-raising first.
2024-11-14 15:06:01,168 [CRITICAL] fMRIPrep failed: 4 raised. Re-raising first.
```

**Comment by withsecco** [comment]
I'm also curious about how to resume the preprocessing if it hangs, and I would like to run it in a new terminal. I referred to this guide: https://fmriprep.org/en/stable/faq.html#can-fmriprep-continue-to-run-after-encountering-an-error

To try this, I ran the following command that included the path to my working directory:

`fmriprep-docker L1Data /Volumes/Elements/L1Data_output participant -w /Volumes/Elements/L1Data_processing --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt --mem 12 --nthreads 4 --fs-no-reconall --output-space MNI152NLin2009cAsym`

But it ended up fetching old files from a previous run and reported a `StopIteration` error

**Comment by effigies** [comment]
I would guess that you're running out of space in your scratch directory so you have a truncated file. Can you try reading the whole file `/Volumes/Elements/L1Data_processing/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_native_wf/boldref_bold/sub-01_task-read_run-1_bold_tshift_xformresampled.nii.gz`?

You can use [miniqc](https://github.com/openneuroorg/miniqc):

```
uvx miniqc /Volumes/Elements/L1Data_processing/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_native_wf/boldref_bold/sub-01_task-read_run-1_bold_tshift_xformresampled.nii.gz
```

**Comment by withsecco** [comment]
Thank you, @effigies 

I got a `ZranError`

``` Shell
(base) qiyu@transfinite ~ % miniqc /Volumes/Elements/L1Data_processing/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_native_wf/boldref_bold/sub-01_task-read_run-1_bold_tshift_xformresampled.nii.gz
[
  [
    "/Volumes/Elements/L1Data_processing/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_native_wf/boldref_bold/sub-01_task-read_run-1_bold_tshift_xformresampled.nii.gz",
    "ZranError",
    "zran_seek returned error: ZRAN_SEEK_FAIL (file: /Volumes/Elements/L1Data_processing/fmriprep_24_1_wf/sub_01_wf/bold_task_read_run_1_wf/bold_native_wf/boldref_bold/sub-01_task-read_run-1_bold_tshift_xformresampled.nii.gz)"
  ]
]
```

**Comment by effigies** [comment]
Try using an environment that does not have `indexed_gzip` installed. If you use `pipx` or `uvx`, it will install into a one-off environment.

**Comment by withsecco** [comment]
Thank you! The issue is fixed. 
 
I have one more question 

> I'm also curious about how to resume the preprocessing if it hangs, and I would like to run it in a new terminal. I referred to this guide: https://fmriprep.org/en/stable/faq.html#can-fmriprep-continue-to-run-after-encountering-an-error
> 
> To try this, I ran the following command that included the path to my working directory:
> 
> `fmriprep-docker L1Data /Volumes/Elements/L1Data_output participant -w /Volumes/Elements/L1Data_processing --participant-label 01 --fs-license-file /Users/qiyu/FREESURFER_HOME/license.txt --mem 12 --nthreads 4 --fs-no-reconall --output-space MNI152NLin2009cAsym`
> 
> But it ended up fetching file (named such as "20241114-125020_41f8fe77-2ff2-4ec7-8720-0a66cf0605e3") from the initial run, and reported a `StopIteration` error
> 
> Thank you for your help
